### ISSUE TITLE
.delete() doesn't trigger .willDelete() or .didDelete() in Models

### ISSUE THREAD

**Issue by cainoct** [vapor/fluent#100]
Deleting a model object with `.delete()` will not trigger `willDelete()` or `didDelete()`, but the model's data is still deleted from the database.

Example:

```
final class Thing: Model {
    
    [...]

    func willDelete() {
        print("willDelete") // doesn't get printed on deletion.
    }

    func didDelete() {
        print("didDelete") // doesn't get printed on deletion.
    }

    [...]

}
```

**Comment by natebird** [comment]
@cainoct can you submit a pull request with a test for this? Or better yet, a code change to fix it along with a test. 😉

**Comment by tannernelson** [comment]
@cainoct `willDelete` and `didDelete` will only be called if you delete a single model. These won't be called if you create a query that deletes models.

For example, this will _not_ call the `didDelete`, `willDelete` methods:
```swift
try User.query().find("name", "Foo").delete()
```

Like @sroebert mentioned, that would require pulling the data from the DB first.

If you want this functionality, you can do something like:

```
let users = User.query().filter("name", "Foo").all()
try users.map { try $0.delete() }
```

That would call `willDelete` and `didDelete` on the users.

**Comment by cainoct** [comment]
As far as I know, I was deleting a single model:

```
drop.delete("delete") { req in
    guard let id = req.data["id"]?.int else {
        throw Abort.custom(status: .badRequest, message: "You have to give an ID.")
    }
    
    guard let thing = try Thing.find(Node(id)) else {
        throw Abort.custom(status: .badRequest, message: "That ID was invalid.")
    }
    
    try thing.delete()
    
    return "that was deleted."
    
}
```

I did try the code that you suggested @tannernelson but that resulted in the same issue:

```
drop.delete("delete") { req in
    guard let id = req.data["id"]?.int else {
        throw Abort.custom(status: .badRequest, message: "You have to give an ID.")
    }

    let thing = try Thing.query().filter("id", Node(id)).all()
    try thing.map { try $0.delete() }

    return "that was deleted."
    
}
```

Just in case, I've also tried manually invoking willDelete() alongside delete() to see if it was the functions inside the model that were the problem somehow, but they work.

(I'm sorry if I am barking up the wrong tree or something, I am relatively new to this stuff, but everything I'm doing does seem fine from a setup standpoint and I've been looking through documentation and calls and definitions in the framework to the best of my ability and it seems like it should work the way I've programmed it :S)
