### ISSUE TITLE
Schema support for Timestamp database type

### ISSUE THREAD

**Issue by cwoloszynski** [vapor/fluent#103]
# Enhancement
# Type Timestamp in Schema
- Author(s): Charlie Woloszynski (https://github.com/cwoloszynski)
- Status: [Awaiting review]
## Introduction

Schema support for SQL Timestamp types is needed to allow for efficient database indexing on timestamp types
## Motivation

Fluent currently supports a small number of database types (INT, DOUBLE, STRING, ID, DATA, and BOOL).  I am working on an application that needs to keep a table sorted by date/time of events so queries can efficiently be processed.  The current design does not allow me to use native swift date values and store them in the database in a format that the database can efficiently process.
## Proposed solution

Add in Fluent the support for a .timestamp() Schema entry
## Impact

This will need to be implemented by appropriate Providers to complete the implementation of this feature
## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by cwoloszynski** [comment]
The code change would look like: 

From e368eb2d4fa2f281f754a1bcd3b2185d13469697 Mon Sep 17 00:00:00 2001
From: Charlie Woloszynski <charles.woloszynski@handheldmedia.us>
Date: Fri, 30 Sep 2016 10:41:17 +0100
Subject: [PATCH] - Add basic timestamp support into Fluent

---
 Sources/Fluent/SQL/GeneralSQLSerializer.swift |  4 ++++
 Sources/Fluent/Schema/Schema+Creator.swift    | 15 +++++++++++++++
 Sources/Fluent/Schema/Schema+Field.swift      |  2 ++
 3 files changed, 21 insertions(+)

diff --git a/Sources/Fluent/SQL/GeneralSQLSerializer.swift b/Sources/Fluent/SQL/GeneralSQLSerializer.swift
index f5b0e56..9e44a57 100644
--- a/Sources/Fluent/SQL/GeneralSQLSerializer.swift
+++ b/Sources/Fluent/SQL/GeneralSQLSerializer.swift
@@ -363,6 +363,10 @@ open class GeneralSQLSerializer: SQLSerializer {
             return "BOOL"
         case .data:
             return "BLOB"
+        case .timestamp:
+            return "TIMESTAMP"
+        case .datetime:
+            return "DATETIME"
         }
     }
 
diff --git a/Sources/Fluent/Schema/Schema+Creator.swift b/Sources/Fluent/Schema/Schema+Creator.swift
index 36d5328..46e23f5 100644
--- a/Sources/Fluent/Schema/Schema+Creator.swift
+++ b/Sources/Fluent/Schema/Schema+Creator.swift
@@ -56,6 +56,21 @@ extension Schema {
             fields += Field(name: name, type: .data, optional: optional)
         }
 
+        public func timestamp(
+            _ name: String,
+            optional: Bool = false
+            ) {
+            fields += Field(name: name, type: .timestamp, optional: optional)
+        }
+        
+        
+        public func datetime(
+            _ name: String,
+            optional: Bool = false
+            ) {
+            fields += Field(name: name, type: .datetime, optional: optional)
+        }
+
         public var schema: Schema {
             return .create(entity: entity, create: fields)
         }
diff --git a/Sources/Fluent/Schema/Schema+Field.swift b/Sources/Fluent/Schema/Schema+Field.swift
index 1fdda7f..27b6e64 100644
--- a/Sources/Fluent/Schema/Schema+Field.swift
+++ b/Sources/Fluent/Schema/Schema+Field.swift
@@ -15,6 +15,8 @@ extension Schema {
             case double
             case bool
             case data
+            case timestamp
+            case datetime
         }
 
         public init(name: String, type: DataType, optional: Bool = false) {
-- 
1.8.4.2

**Comment by natebird** [comment]
This seems like a reasonable proposal and a good enhancement to the the general serializer. I'd be glad to support this in the PostgreSQL-Driver.

**Comment by harlanhaskins** [comment]
I'd be really happy to have this. +1 from me.

**Comment by rafiki270** [comment]
I store my date as a timestamp and do this: self.created = Date.init(timeIntervalSince1970: try node.extract("created")) ... that wouldn't solve your issue?

**Comment by harlanhaskins** [comment]
That's what I've had to do here, but most SQL DBs have a native datetime type that could be more specific than a UTC Second value. It would be nice to have Vapor marshall these data types for us too.

**Comment by BrettRToomey** [comment]
Dates are now supported in Vapor 2.0. Thanks.
