### ISSUE TITLE
UUID support for IDs

### ISSUE THREAD

**Issue by sroebert** [vapor/fluent#107]
I would like to see support for `id`s of different types (e.g. `UUID`). Currently fluent assumes the `id` is not set when saving a non-existing entity and takes the `id` from the created query as an `Int`. It would be nice if it is possible to have `UUID` support, where the `UUID` can be set in the `init` method of the entity.

**Comment by natebird** [comment]
I would also like to see this. 👍

**Comment by sroebert** [comment]
I'll have a look at making a pull request for this, already having something working locally.

**Comment by kdawgwilk** [comment]
@sroebert Is your current solution for using UUIDs publicly available?

**Comment by kdawgwilk** [comment]
This feature is required for any API that wishes to support offline compatible apps in order to allow syncing when the device comes back online

**Comment by sroebert** [comment]
The main problem here is that it doesn't work with the current `id` structure of Fluent. I had to make some changes there to make it work. I'll have to find some time to clean it up for it to be useful to someone else.

**Comment by mz2** [comment]
@sroebert I have the need for the same. Are your changes somewhere public? I'd like to avoid hacking something to this end myself that then becomes quickly obsolete.

**Comment by tanner0101** [comment]
This has been added in master and will be tagged with Fluent 2.0.
