### ISSUE TITLE
Conflict on Entity.find and Schema.Creator.id

### ISSUE THREAD

**Issue by zarghol** [vapor/fluent#129]
Hi ! 
I found a bug with Fluent :

inside a Model, I create the table with an id but with a custom name :
   ```
 static func prepare(_ database: Database) throws {
        try database.create("rooms") { rooms in
            rooms.id("roomNumber")
        }
 }
```

In my init, I have :
`self.id = try node.extract("roomNumber")`

The error is when I try to use Room.find().
It doesn't work because inside the implementation of this method, It use 
`database?.driver.idKey`
this variable is in sqlite and mySql 'id', so It doesn't work with my custom idKey...

Is this a bug, or a normal behavior ?

Thanks !

**Comment by tannernelson** [comment]
That's the normal behavior. If you want to use your custom ID, you can do: 

```swift
Foo.filter("roomNumber", x).first()
```

**Comment by zarghol** [comment]
oh ok, I thought it had to work because it is an id, created, with .id() method, so function working with a basic id should work with a custom one :)
Thanks for your answer
