### ISSUE TITLE
Purpose of exists?

### ISSUE THREAD

**Issue by scottrhoyt** [vapor/fluent#134]
Hey all. I've just started playing around with Fluent, and I had a question for you. What is the purpose of the `Model.exists` property? As I understand it, it denotes whether or not the model was retrieved from the database. But with `id` being a `Node?`, can't you just do a null check or optional bind on `id` to check whether or not the model exists in the database? Maybe the intention is to support setting a custom `id` before the model has been saved the first time? Perhaps that can be solved with an `UPSERT`?

**Comment by tannernelson** [comment]
> Maybe the intention is to support setting a custom id before the model has been saved the first time?

Yes, this is one of the reasons. If you look at any other ORM they will have something similar to an `exists` property.

Hopefully Swift will allow us to have stored properties in extensions soon and we can implement it behind the scenes.
