### ISSUE TITLE
Siblings ability to set Entity name

### ISSUE THREAD

**Issue by theobouwman** [vapor/fluent#136]
The ability to set the entity name

**Comment by tannernelson** [comment]
Do you mean you would like the option to override the table name used for the Pivot?

**Comment by theobouwman** [comment]
Yes

**Comment by Mordil** [comment]
What's the status on this? Is it a part of the open PR #178?

**Comment by tanner0101** [comment]
This has been added to master and will be tagged with Fluent 2.0.
