### ISSUE TITLE
Extract Query, Filter, SQL etc from Fluent and make them not dependent on Entity

### ISSUE THREAD

**Issue by Evertt** [vapor/fluent#139]
You guys have done an awesome job of writing an abstraction layer between swift and any sql-database. I'm writing a doctrine clone in swift and I would love to use the code that you guys have written to communicate with sql-databases.

The only issue is that the way you've written it right now has created a tight coupling between the DBAL and your entity / model protocols. In my doctrine clone I also have an entity protocol, which is defined differently than yours is. So I can't use your `Query` class for example, because your `Query` class depends on your `Entity` protocol. Same goes for your `Filter` struct.

So I wonder, would you guys be willing to totally separate your DBAL into a different repo? One which doesn't depend on anything vapor-specific? I'm willing to help with that.

**Comment by tannernelson** [comment]
Could you map out what that might look like? Fluent tries to be completely independent from Vapor. The only module it imports is `Node`.

**Comment by Evertt** [comment]
Indeed which is already really great. But now the trouble is that the Query class and the Filter struct depend on the Entity protocol. Which means that if anyone wants to build a different ORM using different kinds of Entity protocols, they can't use Fluent.

I would divide Fluent into two parts. One is the DBAL part, which strictly and only deals with providing a thin abstraction layer on top of the database. It contains classes like Query and Filter, but it doesn't rely on any Entity protocol. Instead, when the Query and Filter require information like a table-name (or a document name / collection name for MongoDB), it will just ask for a String type.

And then the second part would be the Fluent part, which provides the Entity protocol, the Model protocol and maybe a QueryBuilder if that's desirable. This is how laravel does it, they have a Database layer and a separate Eloquent layer which uses the Database layer. Same for symfony, which has a Doctrine DBAL layer and a Doctrine ORM layer which again uses the DBAL layer.

Do you see? That way I can use your DBAL without having to use the same Entity protocol. Since I intend to use a different Entity protocol.

**Comment by tannernelson** [comment]
Yeah, that makes sense. We'd have to take a look at how much the Query part is relying on entity right now. I think it's a lot. It uses at least the id and table name in addition to calling makeNode() and init(node: Node) to serialize and parse the models.

**Comment by tannernelson** [comment]
I think to achieve this we would just need one additional protocol (maybe `Queryable`) in between entity and query. 

This protocol would just require table name. And maybe NodeConvertible (since data comes from drivers as node). 

Then we could have entity conform to that. And we could even add further convenience methods where the queryabls type is specifically an entity.

**Comment by C0deH4cker** [comment]
@tanner0101: Will this issue be resolved by Fluent 2.0?

**Comment by tanner0101** [comment]
@C0deH4cker Most of the information in the entity protocol is required for Query to work properly. Especially the ability for something like `Query<User>(...).all()` to return an actual `[User]` array.

**Comment by BrettRToomey** [comment]
I think Entity and Query are too entangled and this won't make it into 2.0. Closing for now.
