### ISSUE TITLE
Custom Column Name?

### ISSUE THREAD

**Issue by michaellatman** [vapor/fluent#140]
# Bugs / Enhancement 

Can we get a way to set our own column name from primaryKey per Entity? 

Currently I am working with a legacy database that has other applications running so I can't rename my primary keys to the required `id` field that the mysql fluent driver requires. 

An idea I had was to have a protocol that would have to be included in entities with custom column names. But my lack of knowledge with swift is making it difficult for me to implement on my own. 

Thanks

**Comment by tannernelson** [comment]
Right now that's not possible. Whatever the `idKey` property is from the driver you are using will be used.

We can keep this issue open for the next major release of Fluent where we could add this functionality.

**Comment by LuizZak** [comment]
Relevant pull request: #175

**Comment by LoganWright** [comment]
This is now supported after the PR @LuizZak wrote and mentioned above 👍
