### ISSUE TITLE
Custom named relations

### ISSUE THREAD

**Issue by Ponyboy47** [vapor/fluent#141]
If I understand the .parent function correctly, when we set up a relation it will automatically name the field with the entity name _id. The problem I see/have with this is that I occasionally have multiple relations to the same table. Not allowing us to set the relation's field restricts the functionality of relations in Vapor.

**Comment by tannernelson** [comment]
This will be addressed in the next version of Fluent. Check out the https://github.com/vapor/fluent/issues/125. 

Mainly:
> Allow custom fields on Pivots.

Feel free to add other things you'd like to see in the next version of Fluent to that list.
