### ISSUE TITLE
Missing NULL filter  fx .filter("column", .isNull) & .filter("column", .isNotNull)

### ISSUE THREAD

**Issue by Casperhr** [vapor/fluent#143]
Querying database for NULL values seems impossible with Vapor. Need to use raw querying to achieve this. A query comparison filter .isNull could be an elegant solution (as well as an .isNotNull filter)

**Comment by Casperhr** [comment]
Model.query().raw("WHERE BLA BLA").first()

the raw("") is also needed

**Comment by BrettRToomey** [comment]
I spoke to tanner about this a few days ago. It can be accomplished by one of the following:

```swift
.filter("field", Node.null)
.filter("field", .equals, Node.null)
.filter("field", .notEquals, Node.null)
```

According to Tanner, `nil` should work, but the compiler was having a rough time trying to disambiguate it. I may have to do a PR.
