### ISSUE TITLE
Modify model data on will*() hooks

### ISSUE THREAD

**Issue by Skyback** [vapor/fluent#153]
# Enhancement: Modify model data on will*() hooks

* Author(s): [Pedro Coutinho](https://github.com/Skyback)
* Status: **[Awaiting review](#rationale)**

## Introduction

It makes sense to be able to edit model data on the hooks provided, but if we change the model data on them the current implementation ignores the changes. This is due to the `data` being  extracted at the beginning of the save() method (https://github.com/vapor/fluent/blob/master/Sources/Fluent/Query/Query.swift#L198).

## Motivation

This kind of hooks would be ideal for `created_at` and `updated_at` timestamps.

## Proposed solution

Move the data extraction jus before calling the `will*()` methods.

```
public func save(_ model: inout T) throws {
        let query = try makeQuery()
       
        if let _ = model.id, model.exists {
            model.willUpdate()
            let data = try model.makeNode()
            try modify(data)
            model.didUpdate()
        } else {
            model.willCreate()
            let data = try model.makeNode()
            model.id = try query.create(data)
            model.didCreate()
        }
        model.exists = true
    }
```

Will try to make a PR as soon as possible.

**Comment by raulriera** [comment]
I believe you and I did the same thing. The fix was merged today https://github.com/vapor/fluent/pull/148
