### ISSUE TITLE
Date type for Fluent MySQL model

### ISSUE THREAD

**Issue by kikolobo** [vapor/fluent#156]
Sorry if I am using this place to post questions, specially when they are newbie questions. But I don't find a suitable forum and slack seems a luck adventure when asking questions. So...

Is there support the Date type or DateTime properties in a fluent model to be stored in a MySQL database?

I am trying to create a time stamp in the model, where in the initialization it will be set to Date(). However i am having some issues with the model in the representable protocol methods.

I need this not only for time stamps but also for birthdays.

My question is is the Date type supported in fluent models and how to implement reading to convert to my client requeried format (string).  

Another question is:
If I use dateFormatter will it work on Linux compiles where Cocoa and NS Lobraries are not available?

**Comment by tannernelson** [comment]
[Node](https://github.com/vapor/node) doesn't support dates natively since integers, doubles, and strings can all supports dates without loss of precision.

So really it's up to you how you want to hold the data in your model and up to MySQL how the data should be retrieved and stored.

Since I've seen this question a few times, I though I'd throw together an example project using MySQL's `DATETIME`.

## main.swift

```swift
import Vapor
import VaporMySQL

let drop = Droplet()

try drop.addProvider(VaporMySQL.Provider.self)

drop.preparations.append(Comment.self)

drop.get("comments") { req in
    let comments = try Comment.all().map { try $0.makeJSON() }
    return JSON(comments)
}

drop.post("comments") { req in
    guard let form = req.formURLEncoded else {
        throw Abort.badRequest
    }
    
    var comment = try Comment(node: form)
    
    try comment.save()
    
    return comment
}

drop.run()
```

## Comment.swift

```swift
import Vapor
import Foundation
import FluentMySQL

private var _df: DateFormatter?
private var dateFormatter: DateFormatter {
    if let df = _df {
        return df
    }
    
    let df = DateFormatter()
    df.dateFormat = "yyyy-MM-dd HH:mm:ss"
    _df = df
    return df
}

final class Comment: Model {
    var id: Node?
    var message: String
    var date: Date
    var exists: Bool
    
    enum Error: Swift.Error {
        case dateNotSupported
    }
    
    init(node: Node, in context: Context) throws {
        id = try node.extract("id")
        message = try node.extract("message")
        
        if let unix = node["date"]?.double {
            date = Date(timeIntervalSince1970: unix)
        } else if let raw = node["date"]?.string {
            guard let date = dateFormatter.date(from: raw) else {
                throw Error.dateNotSupported
            }
            
            self.date = date
        } else {
            throw Error.dateNotSupported
        }
        
        exists = false
    }
    
    func makeNode(context: Context) throws -> Node {
        return try Node(node: [
            "id": id,
            "message": message,
            "date": dateFormatter.string(from: date)
        ])
    }
    
    static func prepare(_ database: Database) throws {
        try database.create("comments") { comments in
            comments.id()
            comments.string("message")
            comments.custom("date", type: "DATETIME")
        }
    }
    
    static func revert(_ database: Database) throws {
        try database.delete("comments")
    }
}
```

**Comment by kikolobo** [comment]
Thank you for the code. It really helps. Let me study it more to comment on it.

In regards to the future: 
I think the best way is for the Fluent Provider (DB Driver)  to know how to convert a swift native Date data type to and from MySQL Date. From there, the model can take care of manually converting it to and from JSON in whatever the API is expecting.  Maybe it is already like that and I am not understanding it. So... let me give it a try and comment more.

**Comment by kikolobo** [comment]
Did Work!.. I used the willSave and willUpdate hooks in the model to set the date to the current date in the model and it serializes ok.

The approach is not bad. I am not sure if I would change the behavior.. maybe just the option to set the schema to timestamp to have mysql do it automatically for us..

**Comment by kjcolley7** [comment]
Vapor's MySQL module _does_ extend `Foundation.Date` with MySQL conveniences: https://github.com/vapor/mysql/blob/master/Sources/MySQL/MySQL%2BDate.swift#L17

There's a `public init(mysql date: String) throws {...}` and a `public var mysql: String {...}`

**Comment by BrettRToomey** [comment]
This is also fixed in Vapor 2. Thanks!

**Comment by AmirHossein1372** [comment]
Casting Vapor 3 Fluent String To Date:

`extension String {
    func convertToDate()->Date? {
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale(identifier: "en_US_POSIX")
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
        dateFormatter.timeZone = TimeZone(secondsFromGMT: 0)
        let date = dateFormatter.date(from: self)
        return date
    }
}`
