### ISSUE TITLE
Unable to customise `.parent` field names

### ISSUE THREAD

**Issue by bygri** [vapor/fluent#161]
In Fluent/Schema/Schema+Creator.swift, all fields can have their column names set except for `parent` which is fixed as `"\(entity.name)_id"`.

This means that [a model with two parent relations to the same entity](http://stackoverflow.com/q/41852726/284120) cannot be created using the `parent` field type - the column names collide.

**Comment by mz2** [comment]
Same thing confused me too. It'd be nice if the creator API allowed customising the foreign key name. You can however create the foreign key field as you please with the creator API (just don't use parent), and then use `parent(foreignId: Node, foreignKey: String?, child: Entity.Protocol) throws -> Parent<Entity>` when querying by that relation (or the equivalent children API if you want to query from that end of the relation).

**Comment by tanner0101** [comment]
This has been merged into master and will be tagged with Fluent 2.0
