### ISSUE TITLE
Fluent Memory Driver ignores Query Limits

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#162]
If you set an `Limit` on a `Query` when using the in-memory database (`MemoryDriver`), it does not respect this limit when returning data.

I'm preparing a PR to fix this bug, this issue is for visibility, or in case anyone already has a fix in place!

**Comment by 0xTim** [comment]
Fixed with #163 PR which is now in master

**Comment by tannernelson** [comment]
Tagged 1.3.4.
