### ISSUE TITLE
Fluent Prepare MySQL bug

### ISSUE THREAD

**Issue by swiftymarks** [vapor/fluent#166]
I tried this table modification for mySQL for my prepares apparently when I look on the MySQL table it doesn't update my table any guess? Though the tables were created earlier using create. 
```
  static func prepare(_ database: Database) throws {
    try database.modify("users", closure: { (avatar) in
      avatar.string("avatar", length: 255, optional: true, unique: false, default: nil)
    })
  }
```

Also it always prints out Database prepared

**Comment by swiftymarks** [comment]
I found it weird that I need to delete the auto generated fluent table in mysql database before the table I want to modify modifies

**Comment by vzsg** [comment]
Fluent decides if a given preparation has been applied or not by checking its name against the automatically generated table. If you modify your source code after applying once, it cannot be automatically reapplied.

**Comment by tannernelson** [comment]
`vapor run prepare --revert`
`vapor run serve` (will prepare again)

**Comment by swiftymarks** [comment]
That make sense, Thanks for the explanation. I'll close this issue now.
