### ISSUE TITLE
Mutating for Structs

### ISSUE THREAD

**Issue by mludi** [vapor/fluent#168]
Hi, I've a feature request. Would be nice to have the `willCreate()` function inside a Struct to have mutating. At the moment it's only possible to use `willCreate()` inside a function. So I can't modify attributes like a creation-date.

**Comment by tannernelson** [comment]
We just need to add `mutating` keyword here: https://github.com/vapor/fluent/blob/master/Sources/Fluent/Entity/Entity.swift#L43

This is a breaking change, though. It may need to wait until Fluent 2.0.

**Comment by BrettRToomey** [comment]
Fluent moved to reference types only in 2.0. Thanks!
