### ISSUE TITLE
Fluent save() to update existing row with new data

### ISSUE THREAD

**Issue by swiftymarks** [vapor/fluent#186]
🚀 Thanks for contributing!
# Bugs
For some reason when ever i update my data using .save() I kept on receiving this kind of error. Any hints? I can't check on how Fluent does it's actual query behind the scenes.

The current table row is like this 
![screen shot 2017-02-17 at 10 38 39 pm](https://cloud.githubusercontent.com/assets/9997430/23069323/eee41c8a-f561-11e6-90fe-10932af052e7.png)

And the data of the user before save is being called
![screen shot 2017-02-17 at 10 40 03 pm](https://cloud.githubusercontent.com/assets/9997430/23069390/35aa826c-f562-11e6-8acd-0fb3a2a6a146.png)

Table structure using Fluent is like this
![screen shot 2017-02-17 at 10 40 13 pm](https://cloud.githubusercontent.com/assets/9997430/23069367/24e3ebda-f562-11e6-9a47-cfebfc15a017.png)

` 
static func updateProfile( user: MeetupUser) throws -> User {
    var user = user
    do {
      try user.save()
    } catch let e {
      print(e)
    }
    return user
  }
`

prepare("You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 1")

**Comment by BrettRToomey** [comment]
There was a bug earlier that manually setting optional and default to would cause invalid MySQL. I believe this has been fixed. By the way, in Vapor 2 you can log MySQL queries. Please feel free to reopen if this is still an issue.
