### ISSUE TITLE
Case insensitive compare

### ISSUE THREAD

**Issue by rolandleth** [vapor/fluent#192]
# Feature, Enhancement, or Optimization

# Case insensitive compare

* Author(s): [Roland Leth](https://github.com/rolandleth)
* Status: **[Awaiting review](#rationale)**

## Introduction

Add a way to create a case insensitive compare. 

## Motivation

There is currently no way to create a case insensitive query, unless manually built, which is both cumbersome, and unsafe.

## Proposed solution

The better proposed solution would be to add an associated `Bool` to `.contains`. This would apply to `hasPrefix` and `hasSuffix` in exactly the same manner.

The simpler proposed solution would be to just use `ILIKE` instead of `LIKE`, but this would break current behaviour.

## Code snippets

Required changes:

```swift
// Comparison.swift: 15
public enum Comparison {
    [...]
    case contains(sensitive: Bool)
}

// GeneralSQLSerializer.swift: 274
open func sql(_ comparison: Filter.Comparison) -> String {
        switch comparison {
        [...]
        case .contains(let sensitive):
            return sensitive ? "LIKE" : "ILIKE"
        }
}

// QueryRepresentable: 124
@discardableResult
    public func filter(
        _ field: String,
        contains value: NodeRepresentable,
        sensitive: Bool
    ) throws -> Query<Self.T> {
		return try filter(T.self, field, .contains(sensitive: sensitive), value)
    }

// PostgreSQLSerializer.swift: 40
public override func sql(_ filter: Filter) -> (String, [Node]) {
    if case .equals = comparison, value == .null {
        [...]
    }
    else if case .notEquals = comparison, value == .null {
        [...]
    }
}
```

This would change the calls from:

```swift
.filter("field", .contains, "value")
.filter("field", contains: "value")
```

to

```swift
filter("field", .contains(sensitive: false), "value")
.filter("field", contains: "value", sensitive: false)
```

## Impact

* For the better solution the applications will stop compiling, but the changes would be pretty easy to fix.
  * If a default value of `false` is added to the `filter` helper, applications will still compile, the behaviour will stay the same, but the method would be slightly less explicit.

* For the simpler solution, the applications will still compile, but they will produce different behaviour.

## Alternatives considered

The current alternative is to raw query the database, and I don't see any other alternative at this point.

A slight alternative would be to name the parameter `insensitive`.

**Comment by BrettRToomey** [comment]
The main issue, unless I'm remembering incorrectly is that MySQL case sensitivity is dependent on a few factors. For instance the operating system and whether or not the table has case sensitivity enabled.

**Comment by rolandleth** [comment]
Sadly, that is outside my knowledge field. But if a table / OS has sensitivity enabled, this change would open the possibility to do both types of queries, and if it doesn't, then it won't matter what flag is used. It would be confusing, that's true, but a documentation mentioning these edge cases / restrictions would be enough, in my opinion.

**Comment by tanner0101** [comment]
@BrettRToomey we tried to implement this before, right? The actual implementation ended up being pretty database-dependant/hacky iirc. I think this might be best left for the `.raw` queries that will be added in Fluent 2.0.

**Comment by tanner0101** [comment]
We could also add some database-specific conveniences for it in the FluentMySQL, FluentPostgres, etc packages. Like we did with the MySQL column types.

**Comment by rolandleth** [comment]
Asking from my limited knowledge perspective, to understand the issue better, what would be the downsides to use either `LIKE` or `ILIKE` based on a flag?

On a side note, what would the ETA be for the `2.0` release? And on topic, how would the new `.raw` queries differ from the current `driver.raw(query)` ones?

**Comment by tanner0101** [comment]
@rolandleth is `LIKE` and `ILIKE` available for all flavors of SQL? If so, that changes things a bunch! 

Re: 2.0, we don't have a fixed time yet, but I think there will be a stable beta coming in a month or two.

The raw queries aren't finished yet, but they will work something like this:

```swift
let results = User
    .query()
    .filter("name", "Vapor")
    .raw(filter: "email = 'foo@vapor.codes'")
    .all()
```

So you could do 

```swift
.raw(filter: "name ILIKE 'vapor'")
```

**Comment by rolandleth** [comment]
@tanner0101 Oh, so a generic one, that returns the required data type. That's pretty neat!

From what I managed to find around, SQL only uses `LIKE` and if you need case insensitive, you just use `upper / lower` on both operands. Maybe that would be an alternative to adding `ILIKE`? This way both generic SQL and PostgreSQL would work with the same syntax. 

Based on the same flag, wrap both operands in `upper`, or not:

```swift
// GeneralSQLSerializer.swift: 197
open func sql(_ filter: Filter) -> (String, [Node]) {
    [...]
    switch filter.method {
    case .compare(let key, let comparison, let value):
        [...]
        switch comparison {
        [...]
        case .contains(let sensitive):
                    values += sql(contains: value, sensitive: sensitive)
        }
}

[...]: 313
open func sql(contains value: Node, sensitive: Bool) -> Node {
    [...]
    var operand = "%\(string)%"
    if sensitive {
        operand = "upper(" + operand + ")"
    }
    return .string(operand)
}
```

**Comment by rolandleth** [comment]
Is there any way to use my own forks? I forked all the required components, and made the required changes, tagged them, but `swift build` can't create a proper output, since other libraries depend on `Fluent` as well, and when it tries to download my version of `Fluent` (or vice-versa), the folder already exists :(

**Comment by tanner0101** [comment]
@rolandleth unfortunately spm doesn't support using forks :(

**Comment by rolandleth** [comment]
@tanner0101 That's unfortunate :( Guess I'll give the beta a try in a while. 

Hoping a non-raw approach will be possible, at some point, too. Let me know if the suggestion is feasible and if I can help in any way.

**Comment by tanner0101** [comment]
The `upper()`/`lower()` seems nice, but gets confusing when working with non-English characters. `ILIKE` would be great, but that's no available in SQLite. Also it seems that `LIKE` may be case-insensitive already in SQLite. 

I'll add this to my list to take a look at before 2.0 is released. If we can't find a one size fits all solution, we can always leave it up to the individual SQL serializers.

**Comment by rolandleth** [comment]
Awesome! When the time comes, let me know if I can be of help, just that my knowledge is rather limited on this matter.

**Comment by tanner0101** [comment]
For MySQL at least, a good fix is using a `*_ci` collate (for case insensitive). Given that there is no good solution for all DBs, I'm going to close for now. Feel free to re-open if we can find a better solution.
