### ISSUE TITLE
Table name that include 'underscore' in its name it parsed wrong.

### ISSUE THREAD

**Issue by lucianboboc** [vapor/fluent#196]
I have a parent-child relation from a `User` table to a `MagicPassword` table.
In the preparation i have used the `magic_passwords` name.
When i create a MagicPassword model and save it, i get this error:
```
{
    "code": 500,
    "error": true,
    "message": "DatabaseError: invalidSQL(\"ERROR:  relation \\\"magicpasswords\\\" does not exist\\nLINE 1: INSERT INTO magicpasswords (expiration_date, value, user_id)...\\n                    ^\\n\")",
    "metadata": null
}
```

It looks like the table name is parsed wrong, it doesn't include the `_` character. `INSERT INTO magicpasswords`.
I tested with both drivers MySQL and PostgreSQL to.
For MySQL the error has this format:

`prepare("Table \'swift.magicpasswords\' doesn\'t exist")`

Steps to reproduce:
1. Create a parent-child relation.
2. The child relation table name should have an underscore in it's name.
3. Create a child model, associate it with the parent id and save it.

Expected result:
The save should succeed.

Actual result:
An error is received and the `INSERT INTO` statement has the table name without the underscore and it is not found.

**Comment by vzsg** [comment]
I cannot reproduce this. After creating a User and a MagicPassword class (entity names hardcoded to `user_account` and `magic_password` respectively, to try both sides), saving and querying both work as expected.

Are you 100% sure, you don't have a typo somewhere in your code? Perhaps you forgot to add the underscore somewhere?

**Comment by lucianboboc** [comment]
@vzsg I'm using "magic_passwords" plural tble name in the prepare method where the schema creator will add all table fields.
Is there any other property i need to set?

**Comment by vzsg** [comment]
Actually yes. The default table name is "lowercase class name + s", which you need to overide if you want an undersckre in there.

For example:

```swift
class MagicPassword: Entity {
    static var entity = "magic_passwords"
    ...
}
```

**Comment by lucianboboc** [comment]
@vzsg Ok, it makes sense, thank you.
I thought the entity name is singular and the param for `database.create` is plural to have the table name plural.
I checked the whole flow and the value from `database.create` was used to create the table name.
```
database.create(entity)
	Schema.Creator(entity)
		self.entity = entity
			

driver.schema(creator.schema)
       return .create(entity: entity, create: fields)
                 SQL.init(schema: Schema)
                         .create(let entity, let fields):
                         table = entity
```
The problem is when a `save` method is called, the `entity` property was checked and if that not set, it was using the class name lowercased (which in my case didn't include the underscore). If the `entity` property was set, in my case it was not plural and that's why the table name was not found when `save` method was called.
I find it a little confusing allowing the table name to be configured using the `entity` name but also as a param in `database.create` because in my case this 2 had different values and that caused the issue. I think this 2 should be a single value, maybe one of them removed.
Thanks for your help.
