### ISSUE TITLE
crash when alter table in sqlite

### ISSUE THREAD

**Issue by linqingmo** [vapor/fluent#201]
# Bugs

[sqlite alter table](http://www.sqlite.org/lang_altertable.html)

sqlite alter table dosn't support `alter table drop columnName`

**Comment by tanner0101** [comment]
Looks like sqlite doesn't support dropping columns.

http://stackoverflow.com/questions/5938048/delete-column-from-sqlite-table/5987838#5987838

We should throw a better error for that from the sql serializer or attempt to support it.
