### ISSUE TITLE
Allow custom querying for entity/model

### ISSUE THREAD

**Issue by joshdholtz** [vapor/fluent#205]
# Feature, Enhancement, or Optimization

# Allow custom querying for entity/model

* Author(s): [Developer](https://github.com/joshdholtz)
* Status: **Need to develop/Need help/feedback**

## Introduction

I have a Postgres table that contains a pgarray - `text[]`. In postgres, a pgarary is stored in a format of `{value1,value2}` (or if the value contains commands, its stored like `{"value,1",value2}`. When querying, postgres returns the pgarray as a string in the value of the previous examples. My model/entity can easily consume this "string" but can't handle the parsing of that date easily.

**HOWEVER**, Postgres has a really nice build in function called `array_to_json` which will take the ugly string formats above and will convert it to JSON.

So what I am looking to add is a feature that allows my Fluent entity/model to have a custom `select` query (preferably by overriding something) so I can call the `array_to_json` on my column(s) that are of pgarray type.

```
climbon=# select id, name, images from routes where id = 2;
 id |  name  |            images            
----+--------+------------------------------
  2 | Slopey | {"image1,with,comma",image2}
```

```
climbon=# select id, name, array_to_json(images) as images from routes where id = 2;
 id |  name  |         images          
----+--------+--------------------------------
  2 | Slopey | ["image1,with,comma","image2"]
(1 row)
```

## Motivation

I can easily hack a solution around this myself (for now) but pgarrays and hstores are pretty widely used postgres datatypes that should be formatted nicely when an entity/model is querying itself.

## Proposed solution

😢 I do not have a technically proposed solution yet because I am not familiar with the Fluent 2 changes and if this is even close to possible/feasible. 

## Code snippets

Unknown currently (will update when I know more)

## Impact

Also unknown currently (will update when I know more)

## Alternatives considered

This is how I am _currently_ doing things to get around this problem. I do not like making a second query and this will not be trivial for other users of pgarrays or hstores to figure out 😇 

```swift
init(node: Node, in context: Context) throws {

	// Other init code here

	// Do a second query specifically for my pgarray column
	// Call the array_to_json function on the images column so
	// so I can handle properly in my model
	//
	// This is not great though because I have to do a second query
	if let id = id?.int,
		let postgres = Route.database?.driver as? PostgreSQLDriver {
		let result = try postgres.raw("select array_to_json(images) as images from routes where id = \(id);")
		images = try result.nodeArray?.first?.extract("images")
	}
}
```

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tanner0101** [comment]
This would be possible through a raw column names in fetch queries. I think this might be rather difficult to implement but I'll see what I can do.

Thanks for the detailed feature request!

**Comment by hhanesand** [comment]
@joshdholtz I don't use posgresql, but I do have arrays with data in them, and I override the row initializer to serialize json :
```swift
public init(row: Row) throws {
    key = try row.extract("key")

    let parsed = try JSON(serialized: row.extract("value") as String)
    value = parsed.converted(to: Node.self)

    expiration = try? row.extract("expiration")
}
```

Could this work for you? It would avoid the extra query and it handles all properly formatted json. You wouldn't be able to use the array column, however.

**Comment by joshdholtz** [comment]
@hhanesand This would work but **only** if I could override the SQL being generated for the fetch of a column. The **raw** column will get fetched with a value like...
```
{"image1,with,comma",image2}
```

In order to get a value in a JSON format (which your solution works for), I need to be able to do a query like `select id, name, array_to_json(images) as images from routes where id = 2;` (the important part being the **array_to_json** function) which then gives a JSON value like...
```
["image1,with,comma","image2"]
```

The issue isn't what to do with the data once its in the Swift side of things. The issue is _getting_ it to the proper format by allowing a custom "select" query to apply the `array_to_json` function on the PGArray column.

**Comment by hhanesand** [comment]
@joshdholtz You would be able to fix that by converting to a string column type and serializing the value to valid JSON before saving that. Want an example?

Not sure how this conversion would affect other queries that you are running.

**Comment by joshdholtz** [comment]
@hhanesand That is an option but that does make things less efficient from Postgres's side of things. Is there no way to override how a model is queried in Fluent? I'm not looking to have this built **INTO** Fluent yet, but it would be nice if I could override how my model's SQL query gets generated.

**Comment by hhanesand** [comment]
No not that I'm aware of, no.

**Comment by joshdholtz** [comment]
@hhanesand Well, I'll keep doing my hack then until I something else get's designed in or I get familiar enough with the codebase to suggest changes to architecture of things 😇  Thanks for looking into this! ❤️

**Comment by tanner0101** [comment]
What would you guys think about something like this:

```swift
extension User {
    static var computedFields: [ComputedField] { 
        return [
             ComputedField(raw: "array_to_json(images)", key: "images"),
             ComputedField(raw: "sum(age + luckyNumber) ", key: "foo")
        ]
    }
}
```

These fields would then be used in the models init like so:

```swift
final class User: Entity {
    ...
 
    init(row: Row) {
        images = try row.get("images")
        foo = try row.get("foo")
    }   
}
```

**Comment by joshdholtz** [comment]
@tanner0101 I would love something like that ❤️

**Comment by hhanesand** [comment]
That looks like a great addition! However, wouldn't it be better if we could sink this functionality into the database instead of having to generate the sql for the statement on every select? For example, on mysql, one can do the following :

```sql
CREATE TABLE triangle (
  sidea DOUBLE,
  sideb DOUBLE,
  sidec DOUBLE AS (SQRT(sidea * sidea + sideb * sideb))
);
INSERT INTO triangle (sidea, sideb) VALUES(1,1),(3,4),(6,8);
```

This allows the database to handle the computed field. I'm not sure if this change would affect the feature set this would support, however.

**Comment by tanner0101** [comment]
@hhanesand that seems like a feature in its own right (and also something that would take more research to see what each sql flavor supports). #253 allows per query and per entity computed fields. Per-schema computed fields could fit nicely on top of that.
