### ISSUE TITLE
Proposal: Decoupling Entity from Database

### ISSUE THREAD

**Issue by vzsg** [vapor/fluent#206]
# Design Proposal: Decoupling Entity from Database

* Author(s): [Zsolt Váradi](https://github.com/vzsg)
* Status: **[Awaiting review](#rationale)**

## Introduction

Currently, the Fluent Entity subclasses are over-powerful god classes. This proposal describes an opinion on cleaning that up. 

## Motivation

As of Fluent 1, Entity classes have multiple responsibilities:
- they act as models with conversion methods to different representations (NodeRepresentable)
- they implement their own DB schema migrations (Preparation)
- they act as their own repositories or query helpers (via static functions attached to the Entity class).

While this might feel convenient, these features have internal dependencies, which are not clearly communicated and error-prone.

Case in point: the repository functionality depends on adding the class to the Droplet's `preparations` array, otherwise the static `database` field does not get set, leading up to `EntityError.noDatabase` errors getting thrown when using the `all()` method. (And a repeating question in [#help](http://vapor.team).)

## Proposed solution

I argue that the `database` static field and the `noDatabase` error should be completely removed, breaking the dependency on both the Droplet and a specific Database instance. I see two possible options for enabling the query helper functionality in a cleaner way.

They both start with deleting the `database` field from Entity, the `EntityError.noDatabase` and _all_ related logic completely.

Then the next step is either:
- Add a `Database` mandatory argument to the Entity CRUD extensions (save, delete, all, find, query). `User.all()` becomes `User.all(in: database)`

- Move these methods to type-safe extensions on the Database protocol. `User.all()` becomes `database.all<User>()`

- Don't add anything, just enforce the use of the `Query<User>(database)` syntax, which is already available.

## Impact

It is apparent how this incision cleans up the internal dependencies, but there is more:
- Entity (thus Vapor's Model) no longer _need_ to comply with the Preparation protocol, so developers with existing databases or manually managed migrations no longer _need_ to add empty prepare/revert functions to their code. But functionality is not lost here, it just becomes _optional_.
- Having the database explicit allows the same Entity classes with multiple databases, enabling a polyglot setup.

The downsides:
- Applying this in any way will break source compatibility with any application that relies on Fluent. Tutorials and guides would also become obsolete.
- The database instance has to be injected to the classes that previously relied on the static field. I.e. a Controller needs to get access to the database itself. (This is not necessarily a bad thing.)

## Alternatives considered

Keep everything as it is now, since Fluent becomes an optional dependency with Vapor 2's new changes.

**Comment by tanner0101** [comment]
+1 To removing `Preparation` from the entity protocol. This syntax looks a lot better:

```swift
extension User: Preparation {
    ...
}
```

As for multiple databases, I kind of like this idea. I do think the ability to do `User.all()` should remain possible for single database (this is most situations). This could be possible through something like a `defaultDatabase: Database?` property. 

```swift
func all(_ database: Database? = defaultDatabase) {
    // assert a database was passed
}
```

However, it's worth noting that this is currently possible through creating Query objects manually.

```swift
_ = Query<User>(databaseA).all()
_ = Query<User>(databaseB).all()
```

**Comment by vzsg** [comment]
Oh, I forgot about the Query syntax, even though it was one of the things that pushed me to write this :) I added it as a third option.

The problem only with this `defaultDatabase` is its storage. Entity subclasses are not the right place as it needs initialization (and we would be back at square one.)
