### ISSUE TITLE
Support for custom `idKey` in `.parent` relation  

### ISSUE THREAD

**Issue by skyweb07** [vapor/fluent#236]
# Enhancement

# Name of Feature

* Author(s): [Developer](https://github.com/skyweb07)
* Status: **[Awaiting review](#rationale)**

## Introduction

It would be really nice to have the custom idKey support back from `.parent` builder options because we can't add custom keys for relation fields like before

```
creator.parent(idKey: "myCustomIdKey", idType: .uuid, optional: true, unique: false, default: nil)
```

## Motivation

Right now you can't have multiple parent models because by default the model it's using the same static property for idKey, for example:

When creating a model like this we should have different `idKeys` for those different parent references but as now us using the same idKey it's impossible to do this kind of relation

`UserModel` with `profileImageId` and  `posterImageId`

If we could get back the custom `idKey` it would be really simple `parent` relation using custom reference identifier for both `UserModel` properties

## Proposed solution

Extends the schema [`Builder` `parent`](https://github.com/vapor/fluent/blob/master/Sources/Fluent/Schema/Builder.swift#L156) function to accept a custom `idKey` for parent fields

```swift
    public func foreignId<E: Entity>(
        for entityType: E.Type,
        idKey: String = E.foreignIdKey,
        optional: Bool = false,
        unique: Bool = false
        ) {
        let field = Field(
            name: idKey,
            type: .id(type: E.idType),
            optional: optional,
            unique: unique
        )
        self.field(field)
        
        if autoForeignKeys {
            foreignKey(
                for: E.self,
                idKey: idKey
            )
        }
    }
    
    public func foreignKey<E: Entity>(
        for: E.Type = E.self,
        idKey: String = E.foreignIdKey
        ) {
        foreignKey(
            idKey,
            references: E.idKey,
            on: E.self
        )
    }
    
    public func parent<E: Entity>(
        _ entity: E.Type = E.self,
        idKey: String,
        optional: Bool = false,
        unique: Bool = false
        ) {
        foreignId(
            for: E.self,
            idKey: idKey,
            optional: optional,
            unique: unique
        )
    }
````

## Impact

It shouldn't affect the api contract because we'll overload the parent method

## Alternatives considered
None atm

**Comment by BrettRToomey** [comment]
@tanner0101 thoughts?

**Comment by tanner0101** [comment]
We definitely need this for 2.0. This is also somewhat related to https://github.com/vapor/fluent/issues/242 (needing to be able to set custom keys)
