### ISSUE TITLE
SQLite Errors are very generic

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#245]
I'm using the `MemoryDriver` in my tests and creating a database and adding preparations like so:

```swift
let database = try Database(MemoryDriver())
BlogUser.database = database
try BlogUser.prepare(database)
```

However when running my tests, I'm hitting errors and the only error output I get in the console is
`<unknown>:0: error: -[SteamPressTests.LeafViewFactoryTests testParametersAreSetCorrectlyOnAllAuthorsPage] : failed: caught error: The operation couldn’t be completed. (SQLite.SQLite.SQLiteError error 4.)`

It would be good to print out the actual error message that is thrown by the driver or should this be the responsibility of the tests?

**Comment by tanner0101** [comment]
I think we should be able to get an actual error message out of SQLite. I'll look into this. Thanks!

**Comment by vzsg** [comment]
XCTests are a tricky situation, if a test throws an error and it escapes the test function, the runner will print the Error's localizedDescription (= the completely unhelpful message seen above).

**Comment by tanner0101** [comment]
Oh, I didn't realize this was XCTest output. @vzsg is right. I haven't found a way to get around having to do something like this in all of my tests:

```swift
do {
    try foo()
} catch {
    XCTFail("\(error)")
}
```

**Comment by tanner0101** [comment]
Going to close this here since this is an XCTest issue / more of a Swift bug. Feel free to re-open here if the fix I mentioned previously doesn't help.
