### ISSUE TITLE
Wrong id when storing models with `uuid` identifier type

### ISSUE THREAD

**Issue by skyweb07** [vapor/fluent#250]
I think I found a bug on Fluent beta

When saving a model into database with custom `idType: IdentifierType = .uuid` after the `.save()` call if we print the `Model.id` it will return a numeric one (default), even if in the db is stored as the correct `uuid`, this is problematic because if we want to store and return the Model `id` it will be incorrect, also `.parent` relations  won't work the first time we call because it's trying to get the parent with the numeric `id` instead of the `uuid`. It's reproducible with the current version and MySQLDriver for example.

**Comment by natebird** [comment]
Can you replicate it in a test case? That is the quickest way to get it fixed.

**Comment by tanner0101** [comment]
This seems like it could be a problem with your model? Can you supply some code that will allow us to recreate the bug?

**Comment by tanner0101** [comment]
@skyweb07 please re-open when you add the information to reproduce and we can take it from there. Thanks!
