### ISSUE TITLE
pass multiple filters per call

### ISSUE THREAD

**Issue by matheusmcardoso** [vapor/fluent#256]
# Feature, Enhancement, or Optimization

# Pass multiple filters per call

* Author(s): [Matheus Martins](https://github.com/matheusmcardoso)
* Status: **[Awaiting review](#rationale)**

## Introduction

Provide a way to pass multiple filters to a single function call for the Query object.

## Motivation

The chaining of filters can add noise without providing any additional meaning:

```swift
Book.makeQuery().filter("genre", "scifi").filter("target", "children").filter("language", "en")
```

## Proposed solution

Extend the Query class with methods that allow the passing of multiple filters.
```swift
extension Query {
    func filter(
        _ filters: [(field: String, value: NodeRepresentable?)]
        ) throws -> Query<E> {
        var query = self
        try filters.forEach {
            query = try query.filter($0.field, $0.value)
        }
        return query
    }
}
```

Additionally, extend Entity to allow filter passing for active lookups:
```swift
extension Entity {
    static func all(
        with filters: [(field: String, value: NodeRepresentable?)]
        ) throws -> [Self] {
        return try makeQuery().filter(filters).all()
    }
    
    static func first(
        with filters: [(field: String, value: NodeRepresentable?)]
        ) throws -> Self? {
        return try all(with: filters).first
    }
}
```

## Code snippets

For lazy lookups:
```swift
Book.makeQuery().filter([("genre", "scifi"),("target", "children"),("language", "en")])
```

For active lookups:
```swift
Book.all(with: [("genre", "scifi"),("target", "children"),("language", "en")])
```

```swift
Book.first(with: [("genre", "scifi"),("target", "children"),("language", "en")])
```

## Impact

There should be no impact on current existing code.
I'd be happy to make a pull request if any of my suggestions are accepted.

## Decision (For Moderator Use)

**Comment by tanner0101** [comment]
Hi @matheusmcardoso, thanks for the contribution. Since this is a convenience feature that can be achieved solely through extensions, it should not be in the fluent core. A design goal of fluent is to be the minimum viable product that:
- allows developers to build on top of it,
- and makes the API easier to maintain.
