### ISSUE TITLE
struct Identifier missing

### ISSUE THREAD

**Issue by ChasonTang** [vapor/fluent#258]
# Bugs

Cannot build project with fluent 2.0.0.

## Introduction

Fluent Parent class is still use Identifier struct,so the build is failed
https://github.com/vapor/fluent/commit/b5315c93e24fe4170ce51f5cac2a51debfb7452d
https://github.com/vapor/fluent/blob/master/Sources/Fluent/Relations/Parent.swift#L9

## Proposed solution

Add the struct again,and tag it.

## Code snippets

```
/// Represents a database row identifier.
/// Uses the same context as Row.
public struct Identifier: StructuredDataWrapper {
    public static let defaultContext = rowContext
    public var wrapped: StructuredData
    public let context: Context

    public init(_ wrapped: StructuredData, in context: Context?) {
        self.wrapped = wrapped
        self.context = context ?? rowContext
    }

    public init() {
        self.init([:])
    }
}
```

**Comment by LoganWright** [comment]
@ChasonTang I just did a fresh build of fluent without issues, you might've ended in a weird place, run `rm -rf .build; rm -rf Package.pins;vapor build;`to try again. I just pulled and tested a fresh build and all ran fine.

Feel free to reopen if you're still seeing the issue 👍

**Comment by ChasonTang** [comment]
ok, thx i'll try again

**Comment by ChasonTang** [comment]
thx, i got it, it's my fault,disregard above
