### ISSUE TITLE
save() can potentially override UUID-type entity ID

### ISSUE THREAD

**Issue by ptsochantaris** [vapor/fluent#259]
I believe I have spotted a bug, that can be reproduced when using SQLite under Vapor 2.0 and Fluent 2.0. I believe it's quite simple to describe, but if you prefer I'll be happy to create a failing project to demonstrate the issue. The problem (unless I'm mistaken) lies in the `save()` method in the `QueryRepresentable.swift` file: 

Background: In this method, when creating a new entity, the method correctly checks if the ID field is nil, and if UUID identifiers are being used for this entity, then it correctly auto-generates a random UUID field (or if one is already provided, it correctly doesn't create one, but still recognises that an entity needs to be created with the existing ID, so all is good up until now).

However *(and I'm not sure if this is SQLite specific, it may be)* later on the method takes the raw return data from the creation of the row (`query.create(row)`) and, given that it's not nil, assigns the returned value to the ID field of the created entity.

It does this always, even if an ID is already present in the field, or even if the method has just auto-generated a UUID earlier on.

This can be a problem if the call to `query.create(row)` does not return the actual new ID, but returns something else, like the new row count of the table of the entity, that some DB systems (and I'm guessing SQLite is one of them) do after creating a new row.

So for instance, if we have an Entity called `User` and it's using a UUID-based ID system, then when we do:
```
let u = User()
u.save()
// u.id will be something like '47' instead of something like 'FC269DCA-2C23-4497-861A-57CF2B0F9A29'
// Meanwhile, the DB does hold the correct UUID value in the appropriate column for this record
// If the app is restarted and the model accessed, it WILL return the correct UUID value for this record, and not '47'
// It seems the numeric value is only temporary, and an artefact of this stage of record storage
```

I have fixed this locally with a very simple addition - by assigning the new ID returned by `query.create(row)` only if the ID field is nil in the first place, otherwise, the code respects what ID value is there in the first place. A simple screenshot of the change in `QueryRepresentable.swift`:

<img width="942" alt="screen shot 2017-05-20 at 00 41 03" src="https://cloud.githubusercontent.com/assets/521581/26270702/0c8ebf76-3cf5-11e7-8c4d-61f4013738f5.png">

I hope this gives you a decent amount of information about the issue. Sorry I haven't provided a test project to demonstrate it, but it's been a crazy week :) I hope the issue is simple enough that it's self-evident by my description and the screenshot.

More than happy to provide more info or create a minimal test project to demonstrate the problem more accurately later on if you prefer, let me know.

**Comment by tanner0101** [comment]
Hi @ptsochantaris. Thanks for reporting. This is likely a bug with the included SQLite driver. It should be returning the newly created ID (like [mysql does](https://github.com/vapor/mysql-driver/blob/master/Sources/MySQLDriver/MySQLConnection.swift#L34-L43)).

The problem with doing what you supplied is that things can happen to the value after it is saved, like being truncated. Just because the save was successful doesn't mean we know for sure the ID we supplied ended up being the entity's ID.

**Comment by ptsochantaris** [comment]
Hi @tanner0101 and thanks for taking the time to explain the logic behind that assignment. I guess that in the case of IDs, the pre-supplied or auto-generated UUIDs are only a suggestion to the DB system and some systems can and do alter it after saving. So my hack basically would only my usage scenario for now :)

I'll be more than happy to create an issue on the appropriate repo for this bug, but there are quite a few fluent/swift related repos out there it seems, and some are deprecated. If you'll excuse a possibly silly-sounding question, could you point me to the appropriate repo I should create this issue in?

Thanks again for your reply, and thank you for the amazing project that is Vapor!

**Comment by tanner0101** [comment]
Thanks! This is actually the correct repo since the SQLite Driver is included w/ Fluent. :)

**Comment by ptsochantaris** [comment]
Ah, awesome! I'll try out that PR locally ASAP and see if it corrects the issue, so I can add a review on the PR to confirm, in case it helps :)

**Comment by ptsochantaris** [comment]
Works great 👍 I've added a comment in the PR mentioning this in case it helps. Thanks again for the quick response. I've applied the patch locally for this to replace my hack, looking forward to the 2.0.1 update.

(PS Not sure if I should be the one to close the issue or you, so I'm leaving it open for you to close whenever you think it's best)
