### ISSUE TITLE
SQLLite transactions don't flush to disk

### ISSUE THREAD

**Issue by cutz** [vapor/fluent#266]
I'm using the `sqlite` driver and using transactions via the `Transactable` protocol.  Insertions done with the connection provided to the transaction closure persist correctly for future transactions so long as vapor is not restarted.  However the database never persists to disk and after restarting vapor the the data created in the transaction closure is lost.

I notice that that the driver is using named save points rather than `begin/commit/rollback transaction`.  When save points are used do I need to do something to manually flush the database to disk?

Reimplementing `transaction` to use `begin/commit/rollback transaction`, with no other code changes,  fixes the issue I am seeing and the data survives a restart of vapor. However, that means calls to `transaction` can't be nested.

**Comment by tanner0101** [comment]
Is it possible you are nested in a `SAVEPOINT` that is not being released?

> If a RELEASE command releases the outermost savepoint, so that the transaction stack becomes empty, then RELEASE is the same as COMMIT. 

According to SQLite `RELEASE` should work exactly like `COMMIT` if it is the top level `SAVEPOINT` being released. 

Possibly you could share the Fluent code that is causing this issue so I can reproduce on my machine?

**Comment by cutz** [comment]
Sorry I haven't had much time to look at this recently. I'll try to put together a reproducible test case.

**Comment by tanner0101** [comment]
Thanks!

**Comment by cutz** [comment]
Sorry, it's taken me a while to get back to this.  At this point I'm unable to reproduce this on what I thought was the same code.  All I can think of is that I had some stale code/framework linked in somehow.  Sorry for the noise here.
