### ISSUE TITLE
opt-out of metadata [required by benchmarks]

### ISSUE THREAD

**Issue by LoganWright** [vapor/fluent#267]
A use case here w/ tech empower benchmarks or other read-only databases:

https://github.com/kimdv/FrameworkBenchmarks/tree/vapor-2/frameworks/Swift/vapor

Need a way to opt out of metadata table, see `Database+Preparation.swift`

**Comment by tanner0101** [comment]
I'll look into this soon so that we can make it into the Techempower benchmark

**Comment by kimdv** [comment]
Poke to me when it is done, so I can continue on the benchmark 💯

**Comment by tanner0101** [comment]
@kimdv this was fixed in https://github.com/vapor/fluent-provider/releases/tag/1.1.0. Setting the `migrationEntityName` to `null` in the `fluent.json` file (as it appears you already have) should cause the preparations to be skipped. Let me know if you need any additional help.

**Comment by kimdv** [comment]
@tanner0101 

It seems that Fluent still tries to create a table called `Fluent`?

```
Setup vapor: Production mode enabled, disabling informational logs.
Setup vapor: fatal error: Error raised at top level: MySQL Error: CREATE command denied to user 'benchmarkdbuser'@'localhost' for table 'fluent'
Setup vapor: 
Setup vapor: Identifier: MySQL.MySQLError.1142 (tableaccessDeniedError)
Setup vapor: 
Setup vapor: Vapor's documentation talks about this: 
Setup vapor: - https://dev.mysql.com/doc/refman/5.7/en/error-messages-client.html
Setup vapor: - https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html: file /home/buildnode/disk2/workspace/oss-swift-3.1-package-linux-ubuntu-14_04/swift/stdlib/public/core/ErrorType.swift, line 188
```

**Comment by tanner0101** [comment]
@kimdv are you sure you have Fluent Provider 1.1.0? 

In the tests I've run the following query:

```swift
        let tables = try drop.assertDatabase().raw("SELECT * FROM sqlite_master WHERE type='table';")
        print(tables)
```

And it returned an empty set. No tables created. 

Maybe try explicitly setting the entity name to null on the config object before passing it to the droplet?

```swift
try config.set("fluent.migrationEntityName", Node.null)
```
