### ISSUE TITLE
Retrieving A List of Column Values 

### ISSUE THREAD

**Issue by t3ndai** [vapor/fluent#268]
🚀 Thanks for contributing!

# Feature, Enhancement, or Optimization

# Name of Feature

* Author(s): [Developer](https://github.com/t3ndai)
* Status: **[Awaiting review](#rationale)**

## Introduction

A method to retrieve a Collection containing the values of single column or specified columns.

## Motivation

Describe the problems that this proposal seeks to address. If the problem is that some common pattern is currently hard to express, show how one can currently get a similar effect and describe its drawbacks. If it's completely new functionality that cannot be emulated, motivate why this new functionality would help Fluent be a better framework.

Most Relational Databases support a way to retrieve only the values of single column or specified columns via SQL e.g 

```sql
SELECT first_name,
FROM customer;
```

Therefore could Fluent be enhanced to support such a feature as it's standard on most databases engines.
Since Vapor is heavily influenced by Laravel [0] and considering larval already has such a feature, implementation might not be such an issue. 

[0] https://laravel.com/docs/5.4/queries

## Proposed solution

Describe your solution to the problem. Provide examples and describe how they work. Show how your solution is better than current workarounds: is it cleaner, safer, or more efficient?

Since Fluent already supports a query in this form: 
```swift

let majorSet = try? Job.makeQuery().filter("college", .greaterThan, "").all().makeJson()

```
Instead of returning all the rows matching that query we only return the values of the specified column in the table. 

## Impact

Faster Queries and cleaner code as some users might just want to retrieve values of a single column and manipulate them for different use cases e.g a Ranking system where the results of the single column can be composed to be a Redis set. 

## Alternatives considered

Describe alternative approaches to addressing the same problem, and why you chose this approach instead.

Right now the solution to this problem is resorting to raw Queries. More Swift Less SQL. 

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by t3ndai** [comment]
on the solution we could have something like the implementation i.e pluck they've in major frameworks like Rails, Laravel 
```swift
Table.pluck("column1", column2")
```
and return the values as a Dictionary

**Comment by tanner0101** [comment]
Hi @t3ndai. Thanks for the detailed proposal. This idea has been proposed before, please see: https://github.com/vapor/vapor/issues/1032
