### ISSUE TITLE
Extract FluentTester to a separate project

### ISSUE THREAD

**Issue by vzsg** [vapor/fluent#273]
Currently FluentTester is a regular framework module, which ends up included and compiled into any Vapor application project. It's not much of a waste and it doesn't do anything; but still, it is meant for testing Fluent and Driver implementations, so it shouldn't be included.

SPM 3 allows for `testDependencies`, i.e. packages that are only used for tests, not for the build targets. It would make sense to move FluentTester into a separate repository, and pull it in as a test dependency both in this repo, and all the driver repositories.

(This is however a breaking change to the Fluent package's public interface, even if it's unrelated to the _real_ functionality. Tread carefully.)

**Comment by tanner0101** [comment]
This is no longer a problem since SPM PackageDescription v4 has explicit dependencies.

Output from `swift build` on API template shows no `FluentBenchmarker` being build:

```sh
Compile Swift Module 'COperatingSystem' (1 sources)
Compile Swift Module 'Debugging' (6 sources)
Compile Swift Module 'Bits' (5 sources)
Compile Swift Module 'Logging' (3 sources)
Compile Swift Module 'SQL' (21 sources)
Compile Swift Module 'Async' (45 sources)
Compile Swift Module 'Service' (17 sources)
Compile Swift Module 'TCP' (12 sources)
Compile Swift Module 'CodableKit' (24 sources)
Compile Swift Module 'Crypto' (29 sources)
Compile Swift Module 'DatabaseKit' (17 sources)
Compile Swift Module 'Console' (21 sources)
Compile Swift Module 'TLS' (6 sources)
Compile Swift Module 'ServerSecurity' (1 sources)
Compile Swift Module 'HTTP' (36 sources)
Compile Swift Module 'AppleTLS' (5 sources)
Compile Swift Module 'SQLite' (22 sources)
Compile Swift Module 'TemplateKit' (38 sources)
Compile Swift Module 'Command' (11 sources)
Compile Swift Module 'Fluent' (47 sources)
Compile Swift Module 'WebSocket' (9 sources)
Compile Swift Module 'Multipart' (5 sources)
Compile Swift Module 'FormURLEncoded' (13 sources)
Compile Swift Module 'FluentSQL' (13 sources)
Compile Swift Module 'FluentSQLite' (9 sources)
Compile Swift Module 'Routing' (9 sources)
Compile Swift Module 'Vapor' (60 sources)
Compile Swift Module 'App' (5 sources)
Compile Swift Module 'Run' (1 sources)
```
