### ISSUE TITLE
[Feature Request] Unique compound index creation

### ISSUE THREAD

**Issue by gperdomor** [vapor/fluent#287]
Please, add support for unique indexes...

Something like this: `try database.index(["field_A", "field_B"], for: MY_ENTITY, unique: true)`

to avoid this: `try database.raw("ALTER TABLE 'MY_TABLE' ADD UNIQUE INDEX 'ix_fA_fB' ('field_A', 'field_B')")`

**Comment by tanner0101** [comment]
@gperdomor i'm not entirely sure what this means. Can you provide more information about what is currently missing in the API?

**Comment by gperdomor** [comment]
Sure...

Now you can do this: `try database.index(["field_A", "field_B"], for: MY_ENTITY)` which in a RAW query is something like this `ALTER TABLE 'MY_TABLE' ADD INDEX 'ix_fA_fB' ('field_A', 'field_B')` but this allow two rows with the same values in that fields, for example `RowA = (field_A = 1 and field_B = 1=` and `RowB = field_A = 1 and field_B = 1`

With a unique index, you can have `RowA = (field_A = 1 and field_B = 1)` and `RowB = (field_A = 1 and field_B = 2)`, if you try to add a new row with the same combination of field A and B, in this case (1,1) or (1,2), the DB should throws an error

**Comment by tanner0101** [comment]
Hmm, that's what `database.index` _should_ do when given multiple fields. This seems like a bug in the SQL serialization.

**Comment by gperdomor** [comment]
👍

**Comment by Andrewangeta** [comment]
@tanner0101 Did you ever consider this to be a feature request or is it just a bug?
