### ISSUE TITLE
Compile error on Siblings.add() function in a specific case

### ISSUE THREAD

**Issue by truemetal** [vapor/fluent#288]
Issue opened by @tanner0101 's request. Please consider the code below, line `try b.aList.add(A())` produces compile error

```
import FluentProvider

final class A: Model
{
    let storage = Storage()
    func makeRow() throws -> Row { return Row() }
    init(row: Row) throws {}
    init() {}
    var bList: Siblings<A, B, Pivot<A, B>> { return siblings() }
}

final class B: Model
{
    let storage = Storage()
    func makeRow() throws -> Row { return Row() }
    init(row: Row) throws {}
    init() {}
    var aList: Siblings<B, A, Pivot<A, B>> { return siblings() }
}

let a = A()
let b = B()

try a.bList.add(B())
try b.aList.add(A())

```

![screen shot 2017-06-13 at 00 08 04](https://user-images.githubusercontent.com/2472186/27055335-bf332f6a-4fcc-11e7-936c-7aa362f1b692.png)

**Comment by hhanesand** [comment]
You have to change the type of the `aList` variable.

`var aList: Siblings<B, A, Pivot<B, A>> { return siblings() }`

This might cause problems with the pivot table, but I'm not sure.
