### ISSUE TITLE
[Feature] Pre-loaded Relations

### ISSUE THREAD

**Issue by stjernegard** [vapor/fluent#293]
# Pre-loaded Relations

Pre-loaded relations (or Eager loading) are core features in other ORMs such as Active Record and Laravel Query Builder and the solution to one of the most common problems slowing page-loads down – the N+1 query.

## Motivation

I found a bit of talk about this kind of functionality in both https://github.com/vapor/fluent/issues/37 and https://github.com/vapor/fluent/issues/125, but it doesn't seem like it was ever implemented.

Imaging a simple scenario with a blog.
Post, references a list of Comments and Comment, references the User who wrote the comment.

To render a list of comments below the blogpost, I will need the username of each `comment.user`, but when I loop over `post.comments`, each call to `comment.user` will create a new database query to get the user object.

With only a few comments on a blogpost this will quickly mean a huge amount of time being spent on database communication.

With pre-loading I would have been able to specify my need for the User object outside the loop and fetch all of the necessary content in a single query.

## Proposed solution

I am not specifying a design for this proposal, but some amounts of inspiration might be possible to find in [Rails' Active Record #includes method](https://apidock.com/rails/ActiveRecord/QueryMethods/includes) or [Laravel's ::with() method](https://laravel.com/docs/master/eloquent-relationships#eager-loading) even though designing a typed implementation could prove a challenge.

Possibly some storage can be added to the relation classes so they can be optionally initialized from `init(row:)` instead of them being only proxies to the database.

## Impact

Depending on implementation, this change could easily break code compatibility with previous versions.

**Comment by tanner0101** [comment]
Totally agree with this. The groundwork for this feature was laid out in Fluent 2.0--there just hasn't been enough time to implement. It should be coming soon!

**Comment by ipodishima** [comment]
On the meantime, do you guys have any clue of how to do it? I'm looking on raw query but there might be something better to do?

**Comment by abbasmousavi** [comment]
Can this pre-loading be recursive?

**Comment by tanner0101** [comment]
Here's what I have working so far:

```swift
let eagerPets = User.eagerLoad(children: \Pet.userID)
let users = try User.query(on: conn).all(eagerLoading: eagerPets.request).wait()
for user in users {
    let pets = try user.pets.get(from: eagerPets.cache)
    print(pets)
}
```

And the corresponding SQL output:

```sql
SELECT * FROM `User #1` []
SELECT * FROM `Pet #1` WHERE (`Pet #1`.`userID` = ?) ["integer8(1)"]
```

**Comment by mcdappdev** [comment]
This solves the N+1 problem, yes? If so I like it. Although admittedly it’s a little more complex than my current solution which is just generating the “in” query using the ~~ operator.

**Comment by tanner0101** [comment]
@mcdappdev yup. And yeah, that's basically all it does. I'm not seeing a huge amount of utility in it after implementing. It's been on the TODO for a long time, but I'm wondering if we really need it.

**Comment by mcdappdev** [comment]
I don’t think it’s a bad addition. Especially if you look at Fluent from the lens of someone who doesn’t work with SQL on a normal basis, they might not understand that something can be accomplished using an IN query and having an ORM feature that abstracts that could possibly save them some performance. 

Those are just my two cents. I see what you mean though, at the end of the day it’s really just a wrapper around ~~ and Swift’s filter.

**Comment by stjernegard** [comment]
I have also started manually fetching all the relations, but it did take some getting used to, coming from dynamic ORMs.

Maybe adding an example use case in the docs would be a nice way to introduce the pattern to new users, which would also avoid a complicated implementation.

After all ~~ requires less in-depth understanding than the example above IMO

**Comment by tanner0101** [comment]
A possible solution to this problem was discussed in the Discord today. Posting here for posterity.

> I had a novel idea for the pre-fetching API. If Fluent were to implement a Codable layer in-between the QueryBuilder and the underlying driver, it could be possible to inject the related types directly into the model. For example:

```swift
struct Galaxy: Model {
    var id: UUID?
    var planets: Children<Galaxy, Planet>

    init() {
        self.id = nil
        self.planets = .init()
    }
}


let galaxies = Galaxy.query(on: db).with(\.planets).all().wait()
for galaxy in galaxies {
    print(galaxy) // Galaxy
    print(galaxy.planets.get()) // [Planet]
}
```

> The idea is that when the Galaxy model is decoded, the QueryBuilder will inject into the Children struct a reference to the pre-fetch cache. Once all of the galaxies have been loaded, the pre-fetch cache will be filled with by a second query. Then, when you go to access the relation, you will automatically get the related items from the cache.

**Comment by fatto** [comment]
Is there any work started on this?

**Comment by calebkleveter** [comment]
@fatto Yes. This feature will be landing with version 4. There are no estimated dates at this point, but the alphas should be coming soon™.

**Comment by tanner0101** [comment]
"Eager loading" has been available in Fluent 4 for a while now. Closing this.
