### ISSUE TITLE
Make Filter NodeConvertible

### ISSUE THREAD

**Issue by cardoso** [vapor/fluent#295]
related PR #296 

# Feature, Enhancement, or Optimization

# Make Filter NodeConvertible

* Author(s): [Matheus Cardoso](https://github.com/cardoso)
* Status: **[Awaiting review](#rationale)**

## Introduction

Make Filter NodeConvertible so Filters can be constructed from and made into Node objects.

## Motivation

This allows for easily adding powerful filtering mechanism in resource routes

## Proposed solution

This is how i achieved the effect i wanted in my project (unit tested):
https://github.com/cardoso/fluent-extended/blob/master/Sources/FluentExtended/Query/Filter/Filter%2BNode.swift

If this solution is acceptable, i can easily make a pull request

#### route
```swift
/// [GET] @ /users
/// Returns all users, optionally filtered by the request data.
func index(_ req: Request) throws -> ResponseRepresentable {
    if let filterString = req.query?["filter"]?.string {
        let filterJSON = try JSON(bytes: filterString.data(using: .utf8)?.makeBytes() ?? [])
        let filter = try Filter(node: Node(filterJSON))
        return try User.makeQuery().filter(filter).all().makeJSON()
    }
    
    return try User.all().makeJSON()
}
```

#### request
```json
[GET]  /users?filter={"entity":"StalkrCloud.User","method":{"type":"compare","comparison":"equals", "field":"username","value":"admin"}}
```

#### response
```json
[
  {
    "id": 1,
    "username": "admin",
    "password": "123456"
  }
]
```

## Impact

Nothing will stop compiling or produce different behavior with this proposition

**Comment by tanner0101** [comment]
This looks useful. Definitely submit a PR!

**Comment by cardoso** [comment]
Made the PR: #296 😃
