### ISSUE TITLE
SQLite Index names only use column name

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#300]
When creating an index on a database, the index name in SQLite only uses the column name which causes issues when you have two indexes on two different tables that have the same column name. Should the index name be something along the lines of `index _fluent_idx_entity_name_column_name`

**Comment by tanner0101** [comment]
The `Index` struct doesn't have access to entity information. We will need to add that. 

Use the `index(raw:)` method as a workaround in the meantime: https://github.com/vapor/fluent/blob/0285ff7eee58da247bc7ecc444307973d926e284/Sources/Fluent/Schema/Index.swift#L21-L25
