### ISSUE TITLE
Transactions bug on SQLiteDriver

### ISSUE THREAD

**Issue by hpeikemo** [vapor/fluent#306]
When using transactions with the `SQLiteDriver` after any one failed transaction (whereupon rollback was called,) any subsequent operation during the lifetime of the connection would not be committed to the database, whether within a transaction or not.

According to [the docs](https://sqlite.org/lang_savepoint.html) a savepoint still remains on the transaction stack when you roll back to it and that's likely the culprit

> The ROLLBACK command with a TO clause rolls back transactions going backwards in time back to the most recent SAVEPOINT with a matching name. The SAVEPOINT with the matching name remains on the transaction stack, but all database changes that occurred after that SAVEPOINT was created are rolled back. If the savepoint-name in a ROLLBACK TO command does not match any SAVEPOINT on the stack, then the ROLLBACK command fails with an error and leaves the state of the database unchanged.

The issue is resolved by releasing the savepoint right after the rollback

```patch
diff --git a/Sources/Fluent/SQLite/SQLiteDriver.swift b/Sources/Fluent/SQLite/SQLiteDriver.swift
index af2374f..5667b79 100755
--- a/Sources/Fluent/SQLite/SQLiteDriver.swift
+++ b/Sources/Fluent/SQLite/SQLiteDriver.swift
@@ -180,6 +180,7 @@
                 return value
             } catch {
                 try conn.raw("ROLLBACK TO SAVEPOINT \(name)")
+                try conn.raw("RELEASE SAVEPOINT \(name)")
                 throw error
             }
         }
```

**Comment by tanner0101** [comment]
@hpeikemo thanks for finding that :) Do you want to create a PR for it?

**Comment by hpeikemo** [comment]
@tanner0101 Very welcome. And sure thing; #307
