### ISSUE TITLE
Fluent preparation only checks using the type name

### ISSUE THREAD

**Issue by steffendsommer** [vapor/fluent#310]
Let's say you have two packages (Package A and Package B) that both comes with a `User` type that conforms to `Model`. To avoid name clashes in tables in the database, both types sets the static `name` property. Both packages wants to prepare their `User` model and adds it to the preparations through their providers. The result is that only one of the models (the first one being added) will be prepared.

The issue afaik is that Fluent only uses the name of type to check if something has already been prepared: https://github.com/vapor/fluent/blob/master/Sources/Fluent/Preparation/Database%2BPreparation.swift#L121

You will not get a warning/error since Fluent moves on thinking that it was just a preparation that already had been prepared.

In the longer term, I think Fluent could ensure uniqueness by using Module/Provider/Timestamp, but for now (as a patch release) to avoid breaking existing projects, maybe an optional field could be added to the `Preparation` protocol where one could overwrite the name of the preparation if needed.

Thoughts on this?

**Comment by tanner0101** [comment]
I think this would make the most sense as an optional parameter when configuring migrations through `MigrationConfig`
