### ISSUE TITLE
Model ids with config of "idType": "uuid" are lower cased

### ISSUE THREAD

**Issue by hyouuu** [vapor/fluent#312]
# Bugs

Having fluent.json with "idType": "uuid", and create a User Model something like this:

```
final class User: Model {
    let storage = Storage()

    // MARK: Properties and database keys

    var uname: String
}
```

Then the `id` field will read lower case, while in DB it's generated uppercase.

**Comment by tanner0101** [comment]
Can you elaborate more on what you mean by this?

**Comment by hyouuu** [comment]
For example, when I create a User, the UUID in postgres will be ABCD-DEFG, but user.id will be abcd-defg, and say I have a User to Pet table which stores userId and petId, then user.petId will be ABCD-DEFG - the cases are inconsistent, and for user.id in this case it should also return upper case

**Comment by tanner0101** [comment]
According to the [UUID spec](https://www.ietf.org/rfc/rfc4122.txt):

> The hexadecimal values "a" through "f" are output as
      lower case characters and are case insensitive on input.

If you want to compare UUIDs, you should do so using the `Foundation` UUID struct or, if they are strings, lowercase them first before comparing.

**Comment by tanner0101** [comment]
Fluent should store the UUID value as a `UUID` struct instead of a `String`. I'll keep this issue open to track progress there.

**Comment by hyouuu** [comment]
Exactly, that way Fluent will provide consistent UUID output rather than having end user convert it all the time. Thanks!

**Comment by tanner0101** [comment]
Fluent 3 properly stores UUIDs.
