### ISSUE TITLE
Receiving error message "Error: No builds found for debug configuration." when running vapor run prepare

### ISSUE THREAD

**Issue by shanemcquillan** [vapor/fluent#314]
My issue here is two-fold: I'm trying to create a database migration (simply following the directions to add SoftDelete functionality - https://docs.vapor.codes/2.0/fluent/model/#soft-delete)

Here's what I have in my Preparation extension:

```
extension Chart: SoftDeletable { }

extension Chart: Preparation {
    static func prepare(_ database: Database) throws {
        try database.create(self) { charts in
            charts.id()
            charts.string("name")
            charts.string("owner")
            charts.string("train")
            charts.string("area")
            charts.bool("is_hidden")
            charts.bool("is_created")
        }
        
        try database.modify(Chart.self) { builder in
            builder.date(Chart.deletedAtKey, optional: true)
        }
    }
    
    static func revert(_ database: Database) throws {
        try database.delete(self)
    }
}
```

This approach may be incorrect, it's unclear from the docs whether this snippet for the migration should go in the existing prepare:
```
        try database.modify(Chart.self) { builder in
            builder.date(Chart.deletedAtKey, optional: true)
        }
```

Either way, the  deleted_at column is not being added to my charts table when I relaunch the app, and I get the error message in the title when I try kicking of the preparation manually.

**Comment by vzsg** [comment]
The problem is that after a Preparation has been executed, you are not supposed to change it anymore, as Fluent only checks the name of the class. As you've seen from trial and error, it will not be executed again, no matter what you changed inside.

And manual running of the function causes a different error as the table already exists.

You have two options:
1. Nuke your database. You will lose all the data, but the next time the app runs, the new schema is created.
1. Follow the [migrations](https://docs.vapor.codes/2.0/fluent/database/#migrations) section of the docs to add a new class that (as a Preparation) will update the database.

**Comment by shanemcquillan** [comment]
Thanks for the speedy response. I resolved this by following the migrations section of the docs, but I think my initial source of confusion was that the docs were a little unclear. It's probably worth explicitly mentioning that you need to create a new class or struct, because existing ones will not be re-ran. Guidance on directory/file structure for migrations would be helpful too.

All of that said, whilst the migrations are successful and my application is up and running, when I call .delete() items in the DB are actually being completely removed rather than soft-deleted. All models conform to SoftDeletable (with the default deletedAtKey), so I'm confused on this one. Any ideas?

**Comment by shanemcquillan** [comment]
An update on this - I got soft deletion to work, but either the docs need to be updated or there's a bug -

If I call delete on a single model soft delete works as expected:

_ = try chartQuery.all().map { try $0.delete() }

However, if I call

try chartQuery.all().delete()

it's a hard delete. Is this expected behavior? If so, it would be good to mention it in the docs.

**Comment by shanemcquillan** [comment]
@tanner0101 Has this been resolved?

**Comment by tanner0101** [comment]
> "Error: No builds found for debug configuration." 

this is an SPM error not Fluent

**Comment by shanemcquillan** [comment]
@tanner0101 sorry, I forgot the original issue. Are you guys aware of the issue I mentioned in my last comment here? I can create a separate issue for that if needed:

"
An update on this - I got soft deletion to work, but either the docs need to be updated or there's a bug -

If I call delete on a single model soft delete works as expected:

_ = try chartQuery.all().map { try $0.delete() }

However, if I call

try chartQuery.all().delete()

it's a hard delete. Is this expected behavior? If so, it would be good to mention it in the docs.
"

**Comment by tanner0101** [comment]
@shanemcquillan oh, I see. Can you please create a new issue for that one? That behavior seems unexpected and not great. We should see what we can do for Fluent 2 and double check to make sure it doesn't happen in Vapor 3. Thanks!
