### ISSUE TITLE
Auto generated foreign key names can be too long when using pivots and MySQL

### ISSUE THREAD

**Issue by steffendsommer** [vapor/fluent#318]
Auto generated foreign key names can sometime end up being too long which can cause a MySQL error when trying to prepare the database. This can be avoided by supplying a custom `foreignKeyName` in `prepare(_)`, however when using `Pivot`s this becomes more challenging.

Currently as I see it there's no way to deal with this in a nice way when foreign key names are being auto generated for a `Pivot` preparation. I can set the table name, the field names or make the pivot manually as a model. These options are a bit cumbersome or annoying since I'm changing my db structure only due to the issue with the foreign key name being auto generated too long.

**Comment by tanner0101** [comment]
I think this is going to be a problem in Fluent 3 as well. We should hash the keys if they become too long (or perhaps just always). I'm not sure whether this issue falls under Fluent MySQL or just Fluent, but I'm leaning toward MySQL. cc @Joannis

**Comment by rdaneshvar95** [comment]
@tanner0101 Any fixes?

**Comment by rdaneshvar95** [comment]
My searches lead me to this solution:
in ForeignKey.swift file

if  "_fluent_fk_\(entity.entity).\(field)-\(foreignEntity.entity).\(foreignField)".characters.count < 64 {
   self.name = name ?? "_fluent_fk_\(entity.entity).\(field)-\(foreignEntity.entity).\(foreignField)"
} else {
   let e1 = String("\(entity.entity)".characters.prefix(12))
   let e2 = String("\(foreignEntity.entity)".characters.prefix(12))
   let f1 = String("\(field)".characters.prefix(12))
   let f2 = String("\(foreignField)".characters.prefix(12))
   self.name = name ?? "\(e1).\(f1)-\(e2).\(f2)"
}

**Comment by tanner0101** [comment]
@rdaneshvar95 just using the prefix will lead to ambiguity in many cases. I think the best option here is to hash the name.

**Comment by tanner0101** [comment]
Moved to fluent-mysql
