### ISSUE TITLE
Add static lifecycle hooks for SoftDeletable and maybe other extensions

### ISSUE THREAD

**Issue by Evertt** [vapor/fluent#319]
Entities have lifecycle hooks, both statically (to hook in for _every_ entity) and on the instance (to hook in for a specific entity).

However, I noticed SoftDeletable (and maybe other extensions) don't have the static variants yet on their added lifecycle events (like `restored`). Would be nice to have them there too.

**Comment by tanner0101** [comment]
Fixed in #482, thanks!
