### ISSUE TITLE
Use sourcery to generate type-safe model keys?

### ISSUE THREAD

**Issue by Evertt** [vapor/fluent#320]
# Generating type-safe model keys with sourcery for filtering in Query\<Entity\>

* Author: [Evert van Brussel](https://github.com/Evertt)
* Status: **[Awaiting review](#rationale)**

## Introduction

This feature would make it possible to instead of filtering like this:

```swift
try User.makeQuery().filter("age" >= 21)
```

To filter like this:

```swift
User.makeQuery().filter(User.age >= 21)
```

Which is type-safe in two ways:

1. The compiler can check that you're filtering on User's columns and not on columns of another model.
2. The compiler can check that you're filtering `User.age` on indeed an `Int`, and not a `String`.

Now you might be thinking, but sometimes I do want to filter on columns of another model, namely when I want to filter on columns of a related model. Well you could still do that with what I'm offering, like this:

```swift
User.makeQuery().filter(User.posts.filter(Post.title == "Foo").count > 1)
```

## Motivation

Simple, more compiler-checked-type-safety is just better, isn't it?

## Code snippets

I've been tinkering with this for a while in my own hobby project and to be honest, the implementation of this is a bit too complicated to shortly show here. However, you can have a look at my repo. I apologize upfront for the mess, because it's a bit of a mess. And it's not even fully functional.

I would advise you to clone [my repo](https://github.com/Evertt/swift-doctrine) and build it and run the test to see that it builds successfully. And then the most interesting things to look at it [this file](https://github.com/Evertt/swift-doctrine/blob/4.0/Tests/ORMTests/EntityMapTests.swift#L22) from lines 22 to 31. If you tinker with that file you can see that the types are actually checked by the compiler.

And also check out [this file](https://github.com/Evertt/swift-doctrine/blob/4.0/Tests/ORMTests/TestEntities.swift). There it's important to note that my idea is to make all those `User`, `Post` and `Address` extensions, wherein the static properties for the columns are defined, be automatically generated by sourcery.

## Impact

This is possibly a considerable rewrite of fluent, but I think that's okay for a major release.

## Alternatives considered

We can continue what we're doing, using strings as keys instead.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by Joannis** [comment]
I like this :) I'd prefer a slightly different implementation though.

```swift
protocol FluentKey {
    var keyName: String
    var type: <???>
}

extension User {
  struct FluentKeys {
    struct Comparable: ExpressibleByStringLiteral {
        ....
        
        static let age: User.FluentKeys.Comparable = "age"
    }
  }
}

func >=(lhs: User.FluentKeys.Comparable, rhs: Int) { ... }
func >=(lhs: User.FluentKeys.Comparable, rhs: Date) { ... }
...
```

```swift
User.makeQuery().filter(.age >= 10).filter(.something < Date())
```

**Comment by Evertt** [comment]
Yeah, that looks way better!

**Comment by tanner0101** [comment]
@Evertt I've implemented something like this using key paths already in Fluent 3.

It looks something like this:

```swift
filter(\User.age >= 10).filter(\User.something < Date())
```

**Comment by Evertt** [comment]
@tanner0101 What? How? I thought it wasn't possible to find out what the actual path was of a `KeyPath` ?! Holy shit that's awesome.

So uh, does it type-check in the same way my code does? I guess it does right? In that case, wouldn't you be able to write a query like this?

```swift
try User.makeQuery().filter(\.age >= 21)
```

In other words, can you omit the `User` ?

**Comment by Joannis** [comment]
Yes, you can omit `User`. And yes, it does type checking 👍

**Comment by tanner0101** [comment]
@Evertt there is no way to get the string path from a key path that I know of (that was also blocking me) but we figured that the type safety is worth some extra boilerplate up front so you're not repeating strings everywhere in code.

Here's what a Fluent 3 model looks like (as of right now):

```swift
final class User: Model {
    typealias Database = SQLiteDatabase
    typealias ID = UUID

    static let keyFieldMap: KeyFieldMap = [
        key(\.id): field("id"),
        key(\.name): field("name"),
        key(\.age): field("age"),
    ]

    static let idKey = \User.id

    var id: UUID?
    var name: String
    var age: Double

    init(name: String, age: Double) {
        self.name = name
        self.age = age
    }

    var pets: Children<User, Pet> {
        return children(\.ownerID)
    }
}
```

I would love to have sourcery auto gen the `keyFieldMap` in the future. Let me know if you'd be interested in helping us figure that out!

**Comment by Joannis** [comment]
Really? I was pretty sure we had that one nailed down (omitting the type)

**Comment by tanner0101** [comment]
`.filter(...)` is really the only place that you can't. Everywhere else that accepts a key path (schema builder, relations, sort, etc) all support omitting the type name.

**Comment by tanner0101** [comment]
We're using key paths now in Fluent 3!
