### ISSUE TITLE
Expirable entity

### ISSUE THREAD

**Issue by rkreutz** [vapor/fluent#321]
# Feature, Enhancement, or Optimization

# Expirable

* Author: [Developer](https://github.com/rkreutz)
* Status: **[Awaiting review](#rationale)**

## Introduction

The main idea would be to create a new `protocol` to denote an expirable entity, which after a given time will be expired and should be removed or not used anymore. It makes sense to be used on authentication tokens, which might expire after some time for security purposes.

## Motivation

As I've said before, I believe the main purpose for this entity would be for authentication tokens that have expiration times. Might be used on other type of entities as well.

## Proposed solution

This entity would inherent from `Timestampable` so it would be possible to check when it was created and with the expiration time determine if it is expired.

## Code snippets

```swift
import Foundation

fileprivate var _expirationTime: TimeInterval = .infinity

public protocol Expirable: Timestampable {
    static var expirationTime: TimeInterval { get set }
}

public extension Expirable {
    static var expirationTime: TimeInterval {
        set { _expirationTime = newValue }
        get { return _expirationTime }
    }
}

public extension Entity where Self: Expirable {
    public static func removeExpiredElements() throws {
        try Self.makeQuery()
            .filter(Self.createdAtKey, .lessThanOrEquals, Date(timeIntervalSinceNow: -Self.expirationTime))
            .delete()
    }
}
```

## Impact

Wouldn't have any impact, since we are adding only adding a new entity and methods.

## Alternatives considered

I didn't actually thought on anything else.

Thanks

**Comment by tanner0101** [comment]
What would differentiate this from using `SoftDeletable` and setting a deletedAt in the future? 🤔
