### ISSUE TITLE
Deleting Siblings generates invalid SQL + concept is unclear

### ISSUE THREAD

**Issue by vzsg** [vapor/fluent#322]
Consider two model classes that are in a many-to-many relationship using the Siblings wrapper, like Atom and Compound in the FluentTester module.

The unit tests cover saving and retrieving related items (yay), but no other mutating operations.

Most importantly, calling `delete()` on a Siblings will throw an invalid SQL error with SQLite, MySQL and PostgreSQL as well.

What?
---

>The behavior is easier to reproduce in FluentTester if you add `try sugar.atoms.delete()` in Tester+PivotsAndRelations.swift, but I don't have the SQL log for that with me.

Here's a broken SQL example from an [experiment](https://github.com/MartinLasek/vaporberlinBE/blob/1d7557f6c23db2d2aaf3ad8b84dab95dd2494f2e/Sources/App/Backend/User/Controller/UserController.swift#L129) in the VaporBerlinBE project:

```
try user.votes.delete() // votes is Siblings<User, Topic, Pivot<User, Topic>> 
```

Generates:

```
DELETE "topics" FROM "topics"
INNER JOIN "topic_user" ON "topics"."id" = "topic_user"."topic_id"
WHERE "topic_user"."user_id" = $1
```

Boom!
---

This technical issue is actually pretty clear: in GeneralSQLSerializer.swift, the [following lines](https://github.com/vapor/fluent/blob/master/Sources/Fluent/SQL/GeneralSQLSerializer.swift#L171-L179) generate an SQL command that is not valid in any dialect. `DELETE FROM` never takes arguments between the two keywords, and regular inner joins don't apply either.

The query correctly should be either using a subselect (works in any dialect incl. SQLite):

```
DELETE FROM topics
WHERE id IN (SELECT topic_id FROM topic_user WHERE user_id = $1)
```

Or in MySQL and Postgres (and possibly others), the USING keyword:

```
DELETE FROM topics USING topic_user
WHERE topics.id = topic_user.topic_id AND topic_user.user_id = $1
```

As far as I can tell, neither query is reconstructible from the joins+filters arrays inside the Query object...

But!
---

Notice that Fluent is trying to delete *connected entities* (Topics), not the links!

If it wasn't for foreign key violations (my fixed queries will fail as well thanks to the safeguard), executing the query would cause unexpected destruction in the database. This might not be the intent of the developer, despite _implicitly_ becoming a query of entities...

So.
---

I think it would make sense to allow both shallow (links only) and deep deletes (links + linked entities in a single step). But even without adding a new feature, both the confusing interface and the invalid SQL should be fixed at least in v3.

Let's make it clear on the interface what a delete operation means. For example, remove the QueryRepresentable compliance from Siblings, and expose separate functions for all possible operations – effectively making it impossible to do a "rawish" delete() query –, just like the current add/detach functions. This is a serious breaking change.

For the technical part, consider throwing an "unsupported" error in GeneralSQLSerializer.delete() if there are joins in the query. It's not like it will succeed anyway. This wouldn't be a breaking change as the interface is the same and it never worked right.

**Comment by tanner0101** [comment]
### Fixing confusing `.delete`

`QueryRepresentable` has already been removed in Fluent 3 so hopefully that will prevent confusing the existing `.delete` for deleting the relation. As it exists now, you'd need to do something like this:

```swift
user.votes.query(on: db).delete()
```

which would then error that joins are not supported on `DELETE` statements.

### Allowing Siblings detach

There are methods for detaching an instance you have `user.votes.detach(voteA)`, but not for detaching all. I will look into implementing this (and probably attach, and isAttached for arrays for parity).

**Comment by tanner0101** [comment]
There's now a `detachAll(on:)` method and a new `pivots(on:)` method for creating a query on the pivot models.
