### ISSUE TITLE
[bug] inconsistent implementation of `computedFields`

### ISSUE THREAD

**Issue by jimmya** [vapor/fluent#327]
Hi,

I noticed that the implementation of `computedFields` seems inconsistent.
When looking at the `all()` function there is a property `computedFields` ([link](https://github.com/vapor/fluent/blob/master/Sources/Fluent/Query/QueryRepresentable.swift#L20)). This property is also present on the function `first()` ([link](https://github.com/vapor/fluent/blob/master/Sources/Fluent/Query/QueryRepresentable.swift#L65)). But when looking at the implementation of `first()` the property `computedFields` is not passed through to the `all()` function. Effectively ignoring the property.

So my guess is that when calling `first()` with `computedFields` the computed fields are ignored. The computed fields is also missing in the pagination functions. So my suggestion is to also add them there.

Sample code:
```swift
final class Test: Model, Preparation {
    
    let storage = Storage()
    
    var title: String?
    var computed: Bool = false
    
    init(row: Row) throws {
        title = try row.get("title")
        computed = try row.get("computed")
    }
    
    func makeRow() throws -> Row {
        var row = Row()
        try row.set("title", title)
        return row
    }
    
    static func prepare(_ database: Database) throws {
        try database.create(self, closure: { (builder) in
            builder.id()
            builder.string("title")
        })
    }
    
    static func revert(_ database: Database) throws {
        fatalError("unimplemented \(#function)")
    }
    
    static func fetchFirst() throws {
        let firstWithoutComputed = try! Test.makeQuery().first()!
        print(firstWithoutComputed.computed) // prints false
        let firstWithComputed = try! Test.makeQuery().first([RawOr.raw("true AS computed", [])])!
        print(firstWithComputed.computed) // prints false but should print true
    }
}
```

Please correct my if my thoughts are wrong. I noticed this inconsistency when trying to use `computedFields` with pagination.

Best regards,
Jimmy

**Comment by tanner0101** [comment]
Computed fields have been removed in Fluent 3 as there isn't a great fit with Fluent's model of codable serialization to concrete structs/classes. 

However, I would like to investigate this issue more and see if perhaps we can create separate/computed models that could be serialized. There is also the issue of selecting two models from a join that I would like to tackle before release if there is time. (This would be somewhat related to that)

**Comment by tanner0101** [comment]
`customSQL(_:)` should be a great alternative to this 👍
