### ISSUE TITLE
filter operators

### ISSUE THREAD

**Issue by Evertt** [vapor/fluent#33]
#32

So right now the only major filter that hasn't been implemented yet is `between`, I think. And I'm doubting how to do it.

Right now if I would write:

``` swift
let filter: Filter = "id" ~= 1...10
```

It generates `id in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. But maybe it should actually generate `id between 1 and 10`, because a range never increments more than 1 right?

But for some reason, in the case of `between`, to me `><` would look like a more obvious operator than `~=`. When I see `><` I almost read it as saying `between`:

``` swift
let filter: Filter = "id" >< 1...10
```

Then again, the `~=` operator already exists and the `><` does not AFAIK. What do you guys think? And if we would go for `><` then what would be the most logical operator for `not between`?

Would it be `<>` or `!><` ?

**edit** Okay right now I implemented it with the `~=` operator, but I would still like to get some opinions from you guys. :-)

**Comment by Joannis** [comment]
I'm not sure here.. I don't like the `><` and `~=` operators honestly. And I think if you're going for the `><` operator you NEED to use `!><` for the not-in. `<>` is silly.

I think this is a case where you should use an extension on String.
`"id".in(1...10)` where it'll return a Filter.

**Comment by Evertt** [comment]
> I'm not sure here.. I don't like the >< and ~= operators honestly. And I think if you're going for the >< operator you NEED to use !>< for the not-in. <> is silly.

I agree about the `><` and the `<>`. Actually I'm now leaning towards `~=`, because it's already an existing operator in swift with a similar function that I want to use it for.

```swift
let a: Bool = 1...5 ~= 2 // valid swift code which evaluates to true
```

> I think this is a case where you should use an extension on String.
"id".in(1...10) where it'll return a Filter.

I don't like mixing operators and extension-functions. I would prefer using 100% operators or 100% extension-functions.

> EDIT:
You can't cover all cases with operators since you'd need to be using keywords. For more advanced operation there's no problem resorting to extensions. They're a critical part of our language for a reason.

Can you give an example of what we're still missing that would need to be expressed via extension-functions?

**Comment by Joannis** [comment]
I'm not familiar enough with SQL to answer to you what is still missing... but I do know that MongoDB has too many operations/operators for this.

**Comment by tannernelson** [comment]
I personally prefer function calls over operators since Xcode is better able to assist with code completion. But I understand that a lot of people prefer the operators, especially after having used a framework for a while and becoming proficient. 

If this is something we still want we can add it to the roadmap.

**Comment by tannernelson** [comment]
Just noticed #32 :)

**Comment by tannernelson** [comment]
We can revisit this. I'd personally prefer to let consumers of the package implement operators themselves, but if there is a big desire for operators we can include them.

**Comment by BrettRToomey** [comment]
This has been fixed :)
