### ISSUE TITLE
MongoDB roadblocks

### ISSUE THREAD

**Issue by Joannis** [vapor/fluent#338]
- `KeyStringDecoder` crashes on arrays
- `KeyStringDecoder` crashes when an `enum XYZ: String, Codable` doesn't support the string `"0"` or `"1"`
- `Int` and similar types are not incremented in MongoDB
- MongoDB doesn't require a `MigrationConfig`, yet an error is thrown if the `MigrationConfig` is missing

**Comment by tanner0101** [comment]
> KeyStringDecoder crashes on arrays
this needs fixed
> KeyStringDecoder crashes when an enum XYZ: String, Codable doesn't support the string "0" or "1"
the type must conform to `KeyStringDecodable`
> Int and similar types are not incremented in MongoDB
This should be fixed as of the recent "id type" update. Try implementing it now :)
> MongoDB doesn't require a MigrationConfig, yet an error is thrown if the MigrationConfig is missing
the mongodb provider should register an empty migration config. this way, users of other fluent drivers will get the error properly

**Comment by Joannis** [comment]
This should all work now. Updating MongoKitten ATM, will open a new issue if necessary
