### ISSUE TITLE
Fluent 3 Save should return self

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#342]
As per the discussion on Slack, when `save()` is called on a model it should return the saved model instead of nothing. So change the return type from `Future<Void>` to `Future<Self>`

This will make it easier to return the saved model rather than relying on references and make it a bit clearer for things that need to happen after the save

**Comment by twof** [comment]
I think `Future<Self>` should also be returned from the other CRUD operations. Take this for example:

```

**Comment by Joannis** [comment]
@twof are you using `blockingAwait` for the sake of this example, or in general?

**Comment by twof** [comment]
For the sake of example, but I think I'm misusing it. Does it wait for the `Future<Reservation>` to resolve and then return the resulting `Reservation`?

**Comment by 0xTim** [comment]
Implemented!
