### ISSUE TITLE
Fluent 3 SQLite does not support Bool columns

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#346]
If you have a model that you are saving in SQLite that contains a property of type `Bool` then you hit a fatal error during migrations and it crashes. Fails here:
https://github.com/vapor/fluent/blob/beta/Sources/FluentSQLite/SQLiteDatabase%2BSchema.swift#L67

**Comment by twof** [comment]
It looks like booleans are stored as integers:
https://www.tutorialspoint.com/sqlite/sqlite_data_types.htm

"SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true)."

They should still be handled though

**Comment by 0xTim** [comment]
So looks like whilst this will work for preparations, there is still an issue when retrieving data (saving data works) - it crashes here https://github.com/vapor/fluent/blob/beta/Sources/SQLite/Row/DecodingContainer.swift#L43

**Comment by 0xTim** [comment]
Have updated the PR
