### ISSUE TITLE
Aggregating distinct queries produces wrong results

### ISSUE THREAD

**Issue by stjernegard** [vapor/fluent#348]
In the current version of Fluent (2.5.0), aggregate queries do not correctly work on `DISTINCT` queries.

Calling `count()` on a query with `isDistinct = true` will be serialized as
```
SELECT DISTINCT COUNT(*) as _fluent_aggregate FROM "table" [...]
````
while running `all()` on the same query will be serialized as
```
SELECT DISTINCT "table".* FROM "table [...]
```
In these two examples, the `DISTINCT` is being applied to different parts of the query, yielding different results.

In the first example, the `DISTINCT` is even entirely non-functional because it's being applied on the aggregate instead of the underlying data and the aggregate will only ever return a single row.

To correctly count the underlying query, the SQL should be
```
SELECT COUNT(DISTINCT "table".*) as _fluent_aggregate FROM "table" [...]
```

**Comment by tanner0101** [comment]
thanks :)
