### ISSUE TITLE
Add convenience method that allows custom type for referenced tables - V3

### ISSUE THREAD

**Issue by rafiki270** [vapor/fluent#354]
in a scenario when table has custom columns ala:
`schema.addField(type: ColumnType.int32(length: 11), name: "id", isOptional: false)`

From convenience point of view I think the best we could get is an enum ala `CodingKeys` which would contain all columns and on some you could specify the exact type ... that way you could get the info about a column from any foreign model etc ...

But obviously I'll be super happy just for the types :)

**Comment by rafiki270** [comment]
Ondrej Rafaj [3 minutes ago]
```    public protocol Referable {
        var foreignKey: ColumnType { get } // .int32(length: 11, "team_id", default: 0, optional: true)
    }```


Ondrej Rafaj [3 minutes ago]
so you know what the counterpart has


Ondrej Rafaj [2 minutes ago]
and than on model you could specify keys like:


Ondrej Rafaj [< 1 minute ago]
```var customKeys: [Field: ColumnType] = [
        \User.teamId: .int32(length: 11, "team_id", default: 0, optional: true)
    ]```


Ondrej Rafaj [< 1 minute ago]
so that way the builder could just autogenerate what it doesn’t have info for and the rest you can customise super easily

**Comment by tanner0101** [comment]
@rafiki270 this can be done more easily with a custom migration now thanks to `addProperties(to:)` (see https://github.com/vapor/fluent/releases/tag/3.0.0-beta.2). Let me know if that seems like a good solution.
