### ISSUE TITLE
Limit `select *` usage

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#363]
Models should only request the columns that are present in the model, instead of `select *`, enabling the ability to create separate structs with a smaller set of columns for different contexts.

**Comment by tanner0101** [comment]
I don't know if this will make it into Fluent 3, but I'm hoping it does. This is related to selecting joined models.

**Comment by tanner0101** [comment]
Fluent 4 does not use `SELECT *` anymore.
