### ISSUE TITLE
Optional JOIN overloads

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent#364]
Currently, when you try to create a JOIN on a table's field that is not an optional, you get a very ambiguous compiler error:

```
Type '_' has no member '<PROPERTY_NAME>'
```

We should create proper overloads for the `.join` method so they work with non-optional types. While we are at it, how about we change `ReferenceWritableKeyPath` to `KeyPath` so constants work?

**Comment by tanner0101** [comment]
This should be fixed by this: https://github.com/vapor/fluent/commit/ba9e8a00ed00aab504afaaa3a399700946b0d0d7
