### ISSUE TITLE
Raw APIs in Fluent

### ISSUE THREAD

**Issue by Joannis** [vapor/fluent#366]
The old `raw` API wasn't ideal because it showed too many limitations. Although, I believe we can now create a `RawQuerySupporting` protocol that a connection or database can rely upon. That way the raw queries can still be supported using generics. 

For MongoDB:

```swift
extension MongoDB: RawQuerySupporting {
  typealias Raw = Document

  func raw(_ query: Raw) -> Stream<RawResults> { ... }
}
```

For SQL:

```swift
extension MySQL: RawQuerySupporting {
  typealias Raw = String

  func raw(_ query: Raw) -> Stream<RawResults> { ... }
}
```

I don't know for sure if this is a must-have, but it'd definitely improve complex (officially unsupported) situations a bit.

**Comment by tanner0101** [comment]
Check out `customSQL(_:)`
