### ISSUE TITLE
Fluent should pass the keyPath (or codingPath) while resolving which column type to use for a field. 

### ISSUE THREAD

**Issue by patchthecode** [vapor/fluent#369]
# Feature, Enhancement, or Optimization

# Name of Feature

* Author(s): [PatchheCode](https://github.com/patchthecode)
* Status: **[Awaiting review](#rationale)**

## Introduction

1: Fluent should pass the keyPath (or codingPath) while resolving which column type to use for a field. 
2: the drivers can then use this key path to check against an array of fields that should be unique

## Motivation

not sure if this is an update that can be added to Vapor or not (or if i have missed something) But

in your `migration.swift` file we have this function:

```public static func prepare(on connection: Database.Connection) -> Future<Void> {
        let idCodingPath = Self.codingPath(forKey: idKey)
        let properties = Self.properties()
        return Database.create(self, on: connection) { schema in
            for property in properties {
                guard property.codingPath.count == 1 else {
                    continue
                }
                try schema.addField(
                    type: Database.fieldType(for: property.type),
                    name: property.codingPath[0].stringValue,
                    isOptional: property.isOptional,
                    isIdentifier: property.codingPath.equals(idCodingPath)
                )
            }
        }
    }
```

I have a case where i need a number or variables to be unique

i wish tere was some way for me to add these unique keyPaths to an array, that your code will pick up and make unique on the table of the database

because right now, since i need mroe than one variable to be unique, i am forced to write my custom `preparation` function

which defeated the purpose and ease of not having to write preparation in vapor3

## Proposed solution

1. probably provide some static var where I can store an array of unique keys?
2. Also since I am doing this for the SQLiteDatabase, i do not think (or know) that your drivers support adding unique columns for Vapor3Beta SQLiteDatabase
## Impact

Not sure

## Alternatives considered

None

**Comment by tanner0101** [comment]
There's a static method now `addProperties` that will take care of auto-generating most of the model. This way you can implement prepare to add some custom stuff like indexes without having to implement everything. 👍
