### ISSUE TITLE
`Parent` should accept optional values

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#370]
Creating a property on a model to access a relationship looks like this:

```swift
var propertyName: Parent<ThisModel, OtherModel> {
    return parent(\.other_model_id)
}
```

However, if `other_model_id` is optional, the above does does not work, and neither does making the `Parent` type optional.

**Comment by tanner0101** [comment]
This has been fixed :)

**Comment by mcdappdev** [comment]
Thank you! :)
