### ISSUE TITLE
entity collections

### ISSUE THREAD

**Issue by Evertt** [vapor/fluent#38]
# Create an immutable `EntityCollection<T: Entity>`

* Author(s): [Evertt](https://github.com/Evertt)
* Status: **[Awaiting review](#rationale)**

## Introduction & Motivation

I understand that most frameworks use an Active-Record style of ORM, because it's just the easiest to understand and get started with. The Data-Mapper ORM, while being very useful for separating concerns in bigger projects, is also more complicated to learn and more work to get started with. So I propose a middle way, using EntityCollections.

## Proposed solution

As far as the developer is concerned, the `EntityCollection<T: Entity>` is precisely a collection of a certain type of `Entity` which they can iterate over and which has some convenient functions to further filter-down the collection based on some conditions.

Underneath however, the collection can be smart about optimizing when it uses the `Query` class to get the entities it needs or whether it works with the entities it has already loaded in memory.

Also I recommend we make the `EntityCollection` completely immutable, so that every time you add a new filter, it just returns a new instance of `Self` with the new filter applied.

## Code snippets

```swift
class UsersController {
    let app: Application
    let users: EntityCollection<User>

    init(app: Application, users: EntityCollection<User>) {
        self.app = app
        self.users = users
    }

    func someAction(request: Request) -> ResponseRepresentable {
        let adultUsers = users.filtered(by: "age" > 18)
        // `adultUsers` is now a new instance of EntityCollection<User>,
        // and `users` itself is unchanged.
        // And the database has not been queried yet.

        for user in adultUsers {
            // Only now that we started iterating over adultUsers,
            // will the class start querying the database.
            // The collection can optimize how often to query the DB, what batch-sizes to use,
            // and the developer does not need to know about any of that.
            user.active = false
            app.email(user).with(template: "kids-hour.html", data: ["name": user.name])
        }

        // Any DB-related methods can only be called on the collection,
        // not on the entities themselves.
        adultUsers.save()

        return Json(["status": "ok"])
    }
}
```

Of course the developer is free to extend `EntityCollection` to add their own convenience methods:

```swift
class UserCollection: EntityCollection<User> {
    func getAdultUsers() -> Self {
        return filtered(by: "age" > 18)
    }
}
```

Although I'm not sure yet whether to do it like that, or to use a protocol:

```swift
protocol EntityCollection: Collection {
    associatedtype T: Entity

    internal var entities: [T] { get set }
    internal var query: Query<T> { get }

    init(_ query: Query<T>)
}

extension EntityCollection {
    func filtered(by filter: Filter) -> Self {
        return Self(query.filter(by: filter))
    }

    func sorted(by column: String, _ direction: Direction) -> Self {
        return Self(query.sort(by: column, direction))
    }

    // Here we could add all the code necessary for conforming
    // to the Collection protocol, like subscripts and whatnot.
}

class CollectionOf<T: Entity>: EntityCollection {
    let query: Query<T>

    init(_ query: Query<T>) {
        self.query = query
    }
}

class UserCollection: EntityCollection {
    let query: Query<User>

    init(_ query: Query<User>) {
        self.query = query
    }

    func getAdultUsers() -> Self {
        return filtered(by: "age" > 18)
    }
}
```

### Another interesting thought

Doctrine's `EntityManager` has a `flush()` method which basically means that all of the creating and updating of entities is queued and won't be executed until you call `flush()`. That way `EntityManager` can figure out how to persist all changes with as few queries as possible.

I like that and yet I hate having to call `flush()` all the time. But right now I'm doing more or less the same thing when I call `adultUsers.save()`. But what if we would use the `deinit {}` method for that? If `EntityCollection` automatically persists when it's deallocated then you can truly use it as any other collection without having to worry about how and when to persist to the DB.

And of course we could add a method or variable with which you can prevent this behavior like `users.persistChanges = false` or whatever. The point is that I think it will probably be much more common that you **do** want to persist changes than that you *don't* want to persist changes. But I'm not 100% sure about that, so maybe we'd need to try it out in an example project.

## Impact

This is strictly additive.

## Alternatives considered

Either only supporting Active-Record style ORM, which I really don't prefer. Or building a full-fledged Doctrine-like DataMapper style ORM which I think costs a lot of time and energy and I'm not sure if the pay-off is that much better than this proposed solution.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tannernelson** [comment]
This looks interesting. We definitely need something like:

```swift
class UserCollection: EntityCollection<User> {
    func getAdultUsers() -> Self {
        return filtered(by: "age" > 18)
    }
}
```

But I wonder if it would make more sense in syntax to call 

```swift
let adultsNamedJohn = User.adults.filter("name", .equals, "john").all()
```

Where it would look something like:

```swift

extension User {
    var adults: Query<User> {
        return User.filter("age", .greaterThan, 18)
    }

```

**Comment by Evertt** [comment]
> But I wonder if it would make more sense in syntax to call
```
let adultsNamedJohn = User.adults.filter("name", .equals, "john").all()
```
Where it would look something like:
```
extension User {
    var adults: Query<User> {
        return User.filter("age", .greaterThan, 18)
    }
}
```

For me that makes less sense, because I see `User` and `UserCollection` as two very different things. `UserCollection` represents the users-table and has knowledge about all the rows in the table. A `User` represents a single row on the table and so should have no knowledge about the other rows in the same table. That's why only a `UserCollection` can be responsible for filtering and sorting the table, not the `User`.

Of course you *could* do it like you said. Again, that is indeed how Active Record style ORMs work. However, the reason I created this proposal is exactly because I want to move away from a 100% Active Record style ORM. Because it breaks SOLID principles which eventually makes for messier code that's harder to maintain.

**Comment by Prince2k3** [comment]
Well the implementation I had for Fluent before removing to get out a stable build was to add the **one to one, one to many, many to many**, methods that Entity should use for these situations. For example ...

```public var comments: [Comment] {
       return self.hasMany(Comment.self)
}```


This would essentially run `Query<User>` in the back giving your a collection or an empty collection of Comments. This would also remove the need for another struct/class with a protocol. You can have a more clean looking Model/Entity setup

**Comment by Evertt** [comment]
@Prince2k3 funny I made a similar proposition [here](https://github.com/qutheory/fluent/issues/37#issuecomment-219677018).

And yes that does allow for some pretty syntax in the entity I agree. So yes I myself am a bit confused about what to do with that. On the one hand I really really want to honor SOLID principles, because it makes code so much more maintainable and making the `Entity` responsible for fetching other entities breaks that principle. On the other hand I do really really like that syntax for expressing entity-relationships.

So I'm leaning towards doing a bit of both, even though that might seem a bit hypocritical. And by doing a bit of both I mean **AND** allowing that syntax for expressing relationships **AND** for all the other stuff using the `EntityCollection` to handle anything table-related.

**Comment by Prince2k3** [comment]
Could be put in the ```Model``` since that is what it does anyway. I feel there would really be a no need to do EntityCollection since Query class does the hard work already. For instance before the decision to pull out the code for doing Model Association. it looked like this 

```
 public func hasOne<T: Model>(table: T.Type, foreignKey: String? = nil) -> T? {
        let q = Query<T>()
        let fkey = foreignKey ?? "\(Self.entity)_id"
        return q.with(fkey, .Equals, id!).first()
    }
    
    public func hasMany<T: Model>(table: T.Type, foreignKey: String? = nil) -> [T]? {
        let q = Query<T>()
        let fkey = foreignKey ?? "\(Self.entity)_id"
        return q.with(fkey, .Equals, id!).all()
    }
    
    public func belongsTo<T: Model>(table: T.Type, foreignKey: String? = nil, otherKey: String? = nil) -> T? {
        let q = Query<T>()
        let fkey = foreignKey ?? "\(table.entity)_id"
        let other = otherKey ?? "id"
        return q.with(other, .Equals, fkey).first()
    }
```
I totally disagree with the need to create EntityCollection.

**Comment by tannernelson** [comment]
I think these will work best added onto the model itself.

```swift
extension User {
    var adults: Query<User> {
        return try query().filter("age", .greaterThan, 18)
    }
}
```
