### ISSUE TITLE
Query.limit().chunk() does not respect the limit()

### ISSUE THREAD

**Issue by bygri** [vapor/fluent#384]
A query such as:

```swift
Object.makeQuery().limit(300).chunk(32) { objects in
  …
}
```

will ignore the `limit(300)` and keep running through every row in the table, in 32-row chunks.

This is because both [`.limit(_:offset:)`](https://github.com/vapor/fluent/blob/84b0d96a61b66168f2a61ec788581e0a2ab6f9c3/Sources/Fluent/Query/Limit.swift#L22) and [`.chunk(_:)`](https://github.com/vapor/fluent/blob/84b0d96a61b66168f2a61ec788581e0a2ab6f9c3/Sources/Fluent/Query/Chunk.swift#L2) end up calling the same function which [overwrites all previous Limits](https://github.com/vapor/fluent/blob/84b0d96a61b66168f2a61ec788581e0a2ab6f9c3/Sources/Fluent/Query/Limit.swift#L32).

**Comment by tanner0101** [comment]
This is fixed in Fluent 3 now with streaming query results. 👍
