### ISSUE TITLE
Can i use timestamp and soft delete?

### ISSUE THREAD

**Issue by roma86** [vapor/fluent#389]
Hello.

Is there are way to use [fluent-provider 1.3.0](https://github.com/vapor/fluent-provider) with Fluent 3.0.0 RC 1 in my new Vapor 2.4.4 project?

**Comment by 0xTim** [comment]
@roma86 you can use the Fluent Provider 1.3.0 in your Vapor 2 project - it will pull in a Fluent 2 release though - Fluent 3 is only compatible with Vapor 3. Both versions of Fluent have Timestamp and Soft Delete
