### ISSUE TITLE
Table name for pivot models should not contain `+` symbol 

### ISSUE THREAD

**Issue by jonny7** [vapor/fluent#393]
I'm just raising this based on the slack discussions with @0xTim 

If I use migrations to build a Postgres pivot model, the table name is created as `tablea+tableb`. It works as I can see the table inside PGAdmin. But I was having trouble importing the new schema into a GUI, because of the `+` symbol. 

I just looked at both MySQL docs:
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html 
and PostgreSQL docs:
https://www.postgresql.org/docs/9.2/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS 

and I read them to both say that the `+` symbol isn't in the list of allowed characters. This seems to be the default behaviour of Vapor if the entity name is generated.

**Comment by tanner0101** [comment]
Any symbol is allowed if you escape it (backtick on mysql, double quotes on psql). The identifier was configurable in Fluent 2 and we should do the same for 3. However we probably need to keep the default the same to preserve backward compatibility.

**Comment by jonny7** [comment]
Yes agreed about any symbol and escaping them. `_` makes sense as a pivot table, but the `+` symbol although it looks fine and it's meaning is understandable at a higher level. I think as a default it has the potential for some problems down the line, because of the need for escaping and definitely some tooling problems. I couldn't import my schema due to the `+`. But you do seem to use the `_` in Vapor 2. :-)

Anyway, just wanted to put it on your radar in case :-)

**Comment by abbasmousavi** [comment]
The `+` in the name also causes some problems for Postgres and MySql GUI clients.
See: https://github.com/vapor/fluent/pull/422
