### ISSUE TITLE
Models with uninitialized optional fields cannot be saved nor updated in MySQL

### ISSUE THREAD

**Issue by SandorDobi** [vapor/fluent#396]
Hi,
The MySQL driver inproperly preaparing a fluent save or update query when the model have some uninitialized optional fields.

The problem in MySQLDatabase+Query.swift file in the execute method.
1. In the first part of the method the Model is encoded with CodingPathPreEncoder() and the keys returns only those keys which are not nil in the model, based on this  the sqlStatement is serialized
2. In the second part the method tries to bound all model fields to this statement even those which are nil, hence the error.
`[ ERROR ] MySQLError.tooManyParametersBound: More parameters were bound than specified in the query`
 
Proposed fix:
Make the sqlStatement in that way it includes all the model fields even those which are in the particular entity nils

**Comment by tanner0101** [comment]
This is very likely already fixed on the NIO branch, but I will double check.
