### ISSUE TITLE
Can not update existing model with NULL (dupe)

### ISSUE THREAD

**Issue by athletecf** [vapor/fluent#404]
I do not know is it known issue or not, so you may link it to the dupe if any

[My be related to 396](https://github.com/vapor/fluent/issues/396)

[Looks like a dupe of 379](https://github.com/vapor/fluent/issues/379)

When i tried to `update` or `save` an object with some property equals `nil` it just ignored and does not set to `NULL` in database.

<img width="1087" alt="screen shot 2018-03-12 at 17 35 37" src="https://user-images.githubusercontent.com/36819516/37291834-95d3fe26-2620-11e8-98fa-33b3e81aa3a3.png">

```
.package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc.1.1"),

.package(url: "https://github.com/vapor/fluent-postgresql.git", .exact("1.0.0-rc.1.1")),
```

**Comment by tanner0101** [comment]
@athletecf I believe this is already fixed on the NIO branch which will be merging soon. I will double check!
