### ISSUE TITLE
filter in empty array problem

### ISSUE THREAD

**Issue by rafiki270** [vapor/fluent#407]
If the values are empty, the query fails so I suggest we create either a throw or just ignore the filter? Please let me know if we can do something with it, happy to put up a pr whatever the desired solution might be

```swift
extension QueryBuilder {
    /// Subset `in` filter.
    @discardableResult
    public func filter<T>(_ field: KeyPath<Model, T>, in values: [Model.Database.QueryDataConvertible]) throws -> Self where T: KeyStringDecodable {
        return try filter(field, .in, .array(values))
    }

    /// Subset `notIn` filter.
    @discardableResult
    public func filter<T>(_ field: KeyPath<Model, T>, notIn values: [T]) throws -> Self where T: KeyStringDecodable {
        return try filter(field, .notIn, .array(values))
    }
}
```

**Comment by vzsg** [comment]
There was a similar issue in Fluent 2.

Simply ignoring the filter is only valid for `notIn`, an `in` filter with an empty array should return an empty result set. At least that's what I still think.

**Comment by rafiki270** [comment]
@vzsg @tanner0101 Yeah, I agree ... just saying the app shouldn't throw an error really ... maybe we could even skip querying and maybe return a prepopulated future on the 'in' scenario with an empty array saving the system a query?

**Comment by BrettRToomey** [comment]
In Laravel, if the array is empty they add a filter that'll always cause the query to return nothing. I think it was something like `where true == false`

**Comment by tanner0101** [comment]
Yup. If the array is empty, it should add a `false` or `true`. (https://github.com/vapor/fluent/blob/2.5.1/Sources/Fluent/SQL/GeneralSQLSerializer.swift#L571-L581)
