### ISSUE TITLE
standardize `filter(_:)` overloads

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent#429]
Come up with a standardized set of filter overloads, probably these:

- [x] `filter(_: Operator)`
- [x] `filter(_: Joined.Type, _: Operator)`
- [x] `filter(_: Field, _: Filter, _: Value)`
- [x] `filter(_: Joined.Type, _: Field, _: Filter, _: Value)`

**Comment by pedantix** [comment]
I am a big fan! In the same vein I think we could do conditional joins... I know this sounds goofy but it becomes more important down the line as we do more complex things with our data

**Comment by tanner0101** [comment]
Done in #482, standardized syntax is to use a fully-qualified key path.
