### ISSUE TITLE
Make QueryDataDecoder Public

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent#431]
Currently, the `QueryDataDecoder` class is internal to Fluent. It would be useful for those of us that have to dig into the internals of Fluent (pun intended, as they always should be) to have that marked `public` so we can easily decode the data we fetch from a given model type.

**Comment by rafiki270** [comment]
https://github.com/vapor/fluent/pull/434

**Comment by calebkleveter** [comment]
Closing in favor of driver specific coders.
