### ISSUE TITLE
didDelete and didCreate missing

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#433]
Vapor 2 had hooks for after deletion and creation. These are useful in a number situations - for example, deleting a parent after a child has been deleted since the parent can’t be deleted before the child when using database foreign keys. Similar hooks in Vapor 3 would be very useful.

**Comment by mcdappdev** [comment]
I’ve been thinking about this - instead of a static method that just gives the ID, why can’t it be called on the deleted object? Sure the ID might not exist, but the actual object hasn’t been purged, right? That would elimate the need for a static method, which is basically an anti-pattern in relation to the rest of the Fluent hooks.

**Comment by tanner0101** [comment]
These have been added back 👍
