### ISSUE TITLE
Fluent 2 -> 3 migration script

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#436]
Need to convert the fluent table ids from ints to UUIDs

**Comment by tanner0101** [comment]
> Looks like the only differences between fluent db in Vapor 3 vs 2 is id is UUID instead of Int. and the camelCase columns for createdAt and updatedAt

**Comment by tanner0101** [comment]
Upgrade queries have been added to this page: https://docs.vapor.codes/3.0/version/upgrading/, thanks!
