### ISSUE TITLE
Sorts can't be used without Groups

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/fluent#438]
Sorts require's the use of Groups in tandem.
`ERROR: column "categories.createdAt" must appear in the GROUP BY clause or be used in an aggregate function`

Using Groups and Sorts together results in a syntax error.
`ERROR: syntax error at or near "GROUP"`

## Example Code
```swift
var defaultPageSorts: [QuerySort] {
    return [
        QuerySort(field: QueryField(entity: Self.entity, name: "createdAt"), direction: .descending)
   ]
}
    
var defaultPageGroups: [QueryGroupBy] {
    return [
        QueryGroupBy.field(QueryField(entity: Self.entity, name: "createdAt"))
    ]
}
```

```swift
self.query.groups.append(contentsOf: defaultPageGroups)
self.query.sorts.append(contentsOf: defaultPageSorts)
```

```swift
let count = self.count()
```

## Result
`SELECT count(*) as "fluentAggregate" FROM "categories" WHERE ("categories"."canteenId" = $1) ORDER BY "categories"."createdAt" DESC GROUP BY "categories"."createdAt" LIMIT 10 OFFSET 0 ["UUID (binary) 7Y&Ë¤\u{1A}CdãërI#)"]`

## Expected
`SELECT count(*) as "fluentAggregate" FROM "categories" WHERE ("categories"."canteenId" = $1) GROUP BY "categories"."createdAt" ORDER BY "categories"."createdAt" DESC LIMIT 10 OFFSET 0 ["UUID (binary) 7Y&Ë¤\u{1A}CdãërI#)"]`

Rearranging the `GROUP BY` and `ORDER BY` alleviates this issue

**Comment by patchthecode** [comment]
added my self here to get status

**Comment by tanner0101** [comment]
This is related to https://github.com/vapor/sql/issues/2

**Comment by rafiki270** [comment]
fixed https://github.com/vapor/sql/pull/5
