### ISSUE TITLE
FluentError results in 500 when no model with id is found

### ISSUE THREAD

**Issue by damirstuhec** [vapor/fluent#440]
https://github.com/vapor/fluent/blob/eb63485dfd6fbd0773a25e1b94830fbcedaa8266/Sources/Fluent/Model/Model.swift#L265

I know Fluent and Vapor don't know anything about each other but in this particular case, it would make sense and moreover it would be _correct_ for this error to somehow result in 404. Currently, it results in 500, ie. `internalServerError`.

**Comment by damirstuhec** [comment]
cc @tanner0101

**Comment by tanner0101** [comment]
My working plan on how to fix this one is putting a `struct NotFound: Error { }` in Core that both Vapor & Fluent can know about. It's not the most beautiful solution but it will work and could potentially be re-used for things like FileManager, etc

**Comment by damirstuhec** [comment]
@tanner0101 I see. I think that would work.

**Comment by damirstuhec** [comment]
For anyone searching a temporary solution, I'm doing this until this gets fixed:
```
extension FluentError: AbortError {
    public var status: HTTPResponseStatus {
        return identifier == "modelNotFound" ? .notFound : .internalServerError
    }
}
```

**Comment by grosch** [comment]
@damirstuhec How do you use that?

**Comment by tanner0101** [comment]
This has been fixed. Fluent now throws a `NotFound` which should appear in Vapor as a 404.
