### ISSUE TITLE
Allow specification of uniqueness of a field

### ISSUE THREAD

**Issue by ScottRobbins** [vapor/fluent#448]
In Fluent 3, it looks like this _should_ be done when defining a custom migration for a model, using the `addProperties(to:)` function. However, this involves setting an array of `SchemaField`s, which do not have a `isUnique` function on them, or a way I can tell to specify that. 

If it's there and I just can't find it I apologize.

**Comment by pedantix** [comment]
@ScottRobbins would a unique index work for your purposes that is what I have always done, and that can definitely be done with Fluent

**Comment by ScottRobbins** [comment]
It was pointed out to me that I can use the `addIndex` function on the scheme builder to do this.
