### ISSUE TITLE
Aggregate queries that might not have a result (e.g. `max()` on an empty table) throw an error

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent#450]
A query like `User.query(...).max(\User.id)` should return `nil` when run on an empty table. Instead, it throws a `Fluent Error: No value found for key: CodingKeys(stringValue: "fluentAggregate", intValue: nil)`.

**Comment by MrMage** [comment]
FYI, even e.g. `let max: Int64? = try User.query(...).aggregate(.max, field: \User.id)` still throws, and I think it should return an optional instead of throwing.

**Comment by pedantix** [comment]
```
let max: Future<Int?> = try User.query(on: req)
   .aggregate(QueryAggregateMethod.max, field: \User.id, as: Int?.self)
```

this shoud work but does not is an issue with how aggregates are getting "mapped" great find as this sort of thing is easy to fail silently

**Comment by tanner0101** [comment]
Fluent 4 aggregates that may return NULL, like max, now support optionals. 

```swift
let maxName = try Planet.query(on: self.database)
    .max(\.$name).wait()
print(maxName) // String?
```
