### ISSUE TITLE
Option to convert to snake_case

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#454]
When I name my swift models I follow the normal swift naming convention, like OrderPoint.  That turns into a table called orderpoints.  Could we instead have that come through as order_points?

I know I can explicitly set the entity name, but it would be nice to have a flag or something that made this automatic.

**Comment by twof** [comment]
This is built into Swift's Codable right now, but unfortunately it didn't get ported to Linux in Swift 4.1
https://bugs.swift.org/browse/SR-7180

So you could wait until Swift 4.2, but someone also might be willing to add this to Fluent.

**Comment by 0xTim** [comment]
You can use `CodingKeys` as well

**Comment by grosch** [comment]
@0xTim Tim, that's what I'm doing now as it has to rename all the column names as well.  It's just painful to do that manually for every table.

**Comment by grosch** [comment]
@tanner0101 It's not feasiable to always assume that the ONLY way the data will be touched is from this one single application.  Or the database might already exist for example, and they used snake case because PostgreSQL doesn't play nice with camel case as you end up having to quote every single column name.

**Comment by tanner0101** [comment]
@grosch you can use `CodingKeys` or make your model's properties match the db names exactly. No need to be religious about casing IMO.

**Comment by vzsg** [comment]
In either case, it might make sense to have Fluent quote every column name, so at least there's one less thing to cause issues.

**Comment by tanner0101** [comment]
Closing this issue since it is unlikely to be something that Fluent itself supports since Codable offers a couple of solutions:

- Use snake_case when defining your property names.
- Use `CodingKeys` enum to specify snake_case names for camelCase properties. 
- Implement encode/decode methods manually using snake_case naming.
