### ISSUE TITLE
[Vapor 3] Allow for `*` in DataColumn.name

### ISSUE THREAD

**Issue by jimmya** [vapor/fluent#471]
Hi,

I'm trying to build the following query using Fluent:
```
SELECT
	events.*
FROM events
	JOIN followers ON events."userID" = followers."userID" 
WHERE followers."followerID" = 2
```
I only want all values from `event` returned. In order to achieve this I'm using the `.customSQL` function. There is however a limiting factor. The way it is currently serialized the `name` of a column is always escaped. Resulting in the following query (postgreSQL):
```
SELECT
	"events"."*"
```
which of course would lead to errors as `*` is not a column of `events`.

My suggestion is to modify `DataColumn.name` to enable either requesting all (`*`) or a custom column specified by name (which would be escaped).

**Comment by rafiki270** [comment]
can't you do it using customSql and setting `.all` in columns?

**Comment by jimmya** [comment]
That would result in:
```
SELECT
	*
FROM events
	JOIN followers ON events."userID" = followers."userID" 
WHERE followers."followerID" = 2
```
Which also includes all other values from the join.
