### ISSUE TITLE
transaction with resulting value

### ISSUE THREAD

**Issue by cyphactor** [vapor/fluent#474]
Currently it seems there is a problem where because `transaction()` returns a `EventLoopFuture<Void>` you can't get the resulting value of things that occur inside the transaciton.

For example lets say we are starting out with this `createAccount` action. It returns an `Account.AuthenticatedAccount` which it obtains by creating the `Account` in the database. It also creates an associated `Token` for the account.

However, lets say that the Token creation failed. We would then have the database in broken state where the Account exists but the associated token does not. Normally, in a non-async scenario I would address this by simply creating the Account and Token in the database using a transaction. Then when the transaction is completed I would return the Account.

```swift
    func createAccount(_ request: Request) throws -> Future<Account.AuthenticatedAccount> {
        let futureAccount = try request.content.decode(Account.self)

        return futureAccount.flatMap(to: Account.AuthenticatedAccount.self) { account in
            let hasher = try request.make(BCryptDigest.self)
            let hashedPassword = try hasher.hash(account.password)
            let newAccount = Account(email: account.email, password: hashedPassword)
            return newAccount.save(on: request).catchMap({ error in throw Abort(.badRequest) }).flatMap(to: Account.AuthenticatedAccount.self) { account in
                let authedAccount = try Account.AuthenticatedAccount(id: account.requireID(), email: account.email)
                let newToken = try Token(token: UUID().uuidString, accountId: account.requireID())
                return newToken.save(on: request).transform(to: authedAccount)
            }
        }
    }
```

When I try and use the `transaction()` API I get to the following and then run into the problem that the `EventLoopFuture<Void>` prevents me from accessing the `EventLoopFuture<Account.AuthenticatedAcount>` from inside the transaction.

```swift
    func createAccount(_ request: Request) throws -> Future<Account.AuthenticatedAccount> {
        let futureAccount = try request.content.decode(Account.self)

        return futureAccount.flatMap(to: Account.AuthenticatedAccount.self) { account in
            let hasher = try request.make(BCryptDigest.self)
            let hashedPassword = try hasher.hash(account.password)
            let newAccount = Account(email: account.email, password: hashedPassword)

            return request.requestPooledConnection(to: .psql).map(to: Account.AuthenticatedAccount.self) { dbConnection in
                return PostgreSQLDatabase.transaction(on: dbConnection) { transactionConnection in
                    // Do stuff in transaction, ideally the newAccount.save that is commented out below and all of that
                } // PROBLEM: here we have an EventLoopFuture<Void> and I need to somehow return the EventLoopFuture<Account.AuthenticatedAccount> from the save() call
            }

//            return newAccount.save(on: request).catchMap({ error in throw Abort(.badRequest) }).flatMap(to: Account.AuthenticatedAccount.self) { account in
//                let authedAccount = try Account.AuthenticatedAccount(id: account.requireID(), email: account.email)
//                let newToken = try Token(token: UUID().uuidString, accountId: account.requireID())
//                return newToken.save(on: request).transform(to: authedAccount)
//            }
        }
    }
```

Please tell me if I am just missing something stupid. From talking to people in chat it doesn't seem like I am missing anything.

**Comment by cyphactor** [comment]
@MihaelIsaev the account you are passing into the promise is not the correct promise. It neesd to be the authedAccount produced by the "//do stuff in transaction".

**Comment by cyphactor** [comment]
Also, something like this may end up being a work around. However, it seems to be completly counter to the async style as you are basically doing most everything inside the DispatchQueue synchronously. Seems like there should be an async way to do this with transactions in the API.

**Comment by MihaelIsaev** [comment]
Sorry, I just thought that it still async cause `.wait()` just means `wait until promise will be finished in another thread`, so it only looks like sync...

**Comment by MrMage** [comment]
Using `.wait()` is definitely a code smell. Also, I know from own experience that `PostgreSQLConnection` is **not thread safe** — even enqueuing queries from another thread can lead to data corruption and crashes.

What should work is the following:

        return futureAccount.flatMap(to: Account.AuthenticatedAccount.self) { account in
            let hasher = try request.make(BCryptDigest.self)
            let hashedPassword = try hasher.hash(account.password)
            let newAccount = Account(email: account.email, password: hashedPassword)

            var storedAccount: Account.AuthenticatedAccount?
            return request.requestPooledConnection(to: .psql).map(to: Account.AuthenticatedAccount.self) { dbConnection in
                return PostgreSQLDatabase.transaction(on: dbConnection) { transactionConnection in
                    return newAccount.save(on: request)
                        .catchMap({ error in throw Abort(.badRequest) })
                        .flatMap(to: Account.AuthenticatedAccount.self) { account in
                        storedAccount = account
                        let authedAccount = try Account.AuthenticatedAccount(id: account.requireID(), email: account.email)
                        let newToken = try Token(token: UUID().uuidString, accountId: account.requireID())
                        return newToken.save(on: request)
                    }
                }.transform(to: storedAccount!)
            }
        }

Notice how you are temporarily storing the created account in `storedAccount`, then transforming the _future_ to that account. However, I agree that the "proper" solution would be to modify `transaction()` into a generic that allows arbitrary return types.

**Comment by cyphactor** [comment]
Yep that version works @MrMage. It just doesn't seem fitting. Something like the following would make more sense I think.

```swift
PostgreSQLDatabase.transaction(to: Account.AuthenticationAccount.self, on: dbConnection) { transactionConnection in
...
}
```

What are your thoughts?

**Comment by MrMage** [comment]
I agree; see the last part of https://github.com/vapor/fluent/issues/474#issuecomment-386972257.

**Comment by MihaelIsaev** [comment]
Thanks @MrMage for turning me back to the right direction by phrase `Using .wait() is definitely a code smell` 💯 and thanks to @cyphactor too 🙂
Now I completely rewrote all my project to use `.map`, `.flatMap`, `.transform`, etc. instead of using `eventLoop.newPromise`+`DispatchQueue.global.async{}`+`.wait`+`.wait`+`.wait`+`.wait` and now my project looks and feels much more clean.

**Comment by tanner0101** [comment]
The transaction method now supports a generic `Future<T>` return type. There's also a new method on `DatabaseConnectable` for performing a transaction more easily:

```swift
let users = req.transaction(on: .psql) { conn in 
    return User.query(on: conn).all()
}
```
