### ISSUE TITLE
FluentProvider migrations essentially leak connections

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent#475]
`FluentProvider.didBoot` runs database migrations, which in `SchemaMigrationConfig.migrationPrepareBatch` call `container.withPooledConnection`, with `container` being the global `app` object in this case. Given that this happens on the main thread with the `app` object, this pooled connection will never be used again once the main server runs.

Given that in e.g. PostgreSQL each open connection is expensive for the database server, should we close this particular pooled connection once we can be sure that it is no longer used?

(Note that [`FluentPostgreSQLProvider.willBoot`](https://github.com/vapor/fluent-postgresql/blob/master/Sources/FluentPostgreSQL/FluentPostgreSQLProvider.swift) also uses this pooled connection once.)

**Comment by tanner0101** [comment]
This has been fixed in #482. Using `withNewConnection(...)` instead of a pool.

**Comment by MrMage** [comment]
Stupid question, but will the connection get closed automatically when it is deallocated? I think this is the case for `PostgreSQLConnection`, but not for [`MySQLConnection`](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Connection/MySQLConnection.swift).

**Comment by tanner0101** [comment]
@MrMage `withNewConnection(...)` calls `close(...)` after the inner closure has completed. https://github.com/vapor/database-kit/blob/master/Sources/DatabaseKit/Connection/Container%2BNewConnection.swift#L23
