### ISSUE TITLE
Using `update(_ data: [QueryField: Model.Database.QueryDataConvertible])` requires weird casts

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent#476]
I've been trying to use the following code snippet:

    var valuesToWrite: [QueryField: PostgreSQLDatabase.QueryDataConvertible] = [:]
    valuesToWrite[try \RefreshToken.lastPartialSyncServerID.makeQueryField()] = Int(lastPartialSyncServerID)

However, that fails with the errors:

    1. Ambiguous subscript with base type '[QueryField : PostgreSQLDatabase.QueryDataConvertible]' (aka 'Dictionary<QueryField, PostgreSQLDataConvertible>') and index type 'WritableKeyPath<_, _>'
    2. Invalid component of Swift key path

Explicitly casting the key path to `KeyPath` works:

    var valuesToWrite: [QueryField: PostgreSQLDatabase.QueryDataConvertible] = [:]
    valuesToWrite[try (\RefreshToken.lastPartialSyncServerID as KeyPath).makeQueryField()] = Int(lastPartialSyncServerID)

In related news, I think that `update(_ data: [QueryField: Model.Database.QueryDataConvertible])` is a great way of updating only some model properties rather than all of them. This is

a) more efficient;
b) avoids race conditions with two "full" updates where only one field changes in each update (with those fields being different in both updates). With full updates, there is a possibility that the original values from one update revert the changes made by the other update.

Lastly, I also think it should be even easier to use this method; ideally just:

    var valuesToWrite: [QueryField: PostgreSQLDatabase.QueryDataConvertible] = [:]
    valuesToWrite[\RefreshToken.lastPartialSyncServerID] = Int(lastPartialSyncServerID)

Maybe this can be done by somehow making `update` take a dictionary of `KeyPath`s to `Database.QueryDataConvertible`. However, I don't know if `KeyPath` can be made to conform to `Hashable`, and `makeQueryField()` throws which also might make this slightly more complicated.

Lastly, I think that given how useful `update(_ data: [QueryField: Model.Database.QueryDataConvertible])` is, it should be much easier to find. I only by chance found it in `Query+CRUD.swift` and it is currently not mentioned in the documentation.

**Comment by tanner0101** [comment]
The new `update(data:)` method accepts a simple `Codable` type now. This should be much easier to use 👍
