### ISSUE TITLE
There should be a `SELECT`/fetch equivalent of `update(_ data: [QueryField: Model.Database.QueryDataConvertible])`

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent#477]
Currently, Fluent only uses `SELECT *`, which fetches all properties. This is potentially costly. It would be very useful to have an analogue to `update(_ data: [QueryField: Model.Database.QueryDataConvertible])` that fetches only some properties.

Related: https://github.com/vapor/fluent/issues/476, which is also about `update(_ data: [QueryField: Model.Database.QueryDataConvertible])`.

**Comment by mcdappdev** [comment]
Related to: https://github.com/vapor/fluent/issues/363

**Comment by tanner0101** [comment]
Fluent 4 exposes `QueryBuilder.field` which lets you do partial selects. 

```swift
let planets = try Planet.query(on: self.database)
    .field(\.$name)
    .all().wait()
```
