### ISSUE TITLE
Running revert command runs migrations first

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#480]
Probably related to Vapor commands but if you run the revert command it will run the migrations first. This causes problems if you have a new migration that references a column that doesn't exist and you need to revert the database first. You get stuck in a catch-22 which can cause issues on platforms like Vapor Cloud

**Comment by tanner0101** [comment]
current working solution for this problem is as follows:
```swift
services.register(FluentProvider(autoMigrate: false))
```
This will disable migrating during boot, to migrate use: 
```sh
$ swift run Run migrate
```

**Comment by 0xTim** [comment]
One thing - I'm assuming this means that `migrate` is now a separate command. So for Vapor Cloud I do
```bash
vapor cloud deploy
vapor cloud run "Run migrate"
```
to get everything working?

**Comment by tanner0101** [comment]
@0xTim auto migration will still be enabled by default. If you choose to specify `autoMigrate: false`, then the only way to run migrations will be the `migrate` command. (In both cases, there will still be a new `migrate` command added).

You would do:
```swift
vapor cloud run migrate
```
