### ISSUE TITLE
Migration Batches

### ISSUE THREAD

**Issue by tomcomer** [vapor/fluent#483]
As far as I can tell, only 1 batch of changes for any given model will ever be applied. There doesn't seem to be a way within the model to tell Fluent a batch number. Also, in the ```MigrationContainer.prepareIfNeeded``` method, it calls the ```MigrationContainer.hasPrepared``` method. In hasPrepared, it does:

   ```
    MigrationLog<Database>
                .query(on: Future.map(on: connection) { connection })
                .filter(\.name, .equals, .data(self.name))
                .first()
                .map(to: Bool.self) { $0 != nil }
```

If the result of ```MigrationContainer.hasPrepared``` is true, ```MigrationContainer.prepareIfNeeded``` just does:

   ```
    if hasPrepared {
        return .done(on: connection)
    }
```

Which, as far as I can tell, causes the Model's prepare method to only ever be called once (when the table needs to first be created). It does not take into account which batch. So, currently, there seems to be no way to modify a model and update the Model's prepare method to add more columns to the backing table.

**Comment by tanner0101** [comment]
@tomcomer that's correct. That's how it is expected to work. If you are in a dev environment, you should drop or revert the db when your model changes. If you are in a production environment, you should create a new migration struct with just the changes that need to be applied (using an update query).

**Comment by tomcomer** [comment]
That makes sense now. Thank you for the clarification.
