### ISSUE TITLE
Model does not conform with JSONRepresentable

### ISSUE THREAD

**Issue by rugaard** [vapor/fluent#49]
After updating to Vapor `v0.12` I couldn't build my app due to:

> `Model` does not conform with `JSONRepresentable`

After diving a bit into the source it looks to be a simple type-error. In Fluent's `Model` it has a method named `MakeJSON` where the `JSONRepresentable` protocol expects a `MakeJson` method.

I would have made a pull-request, but I'm not sure how you wish to spell it. Either with caps or just a capitalized J. So figured it was best, to let you guys figure it out 😃

**Comment by tannernelson** [comment]
That should be all caps. That looks like the unfortunate result of a merge conflict. :(

**Comment by tannernelson** [comment]
makeJSON

**Comment by tannernelson** [comment]
This works now.
