### ISSUE TITLE
When updating existing table, `field(for:referencing:)` doesn’t add foreign key constraint

### ISSUE THREAD

**Issue by Cellane** [vapor/fluent#491]
When updating already existing table, `SchemaBuilder`’s `field(for:referencing:)` method only creates a field for holding the other table’s reference but doesn’t create the actual foreign key constraint. This goes against the documentation of the method, which says “Adds a field to the schema and creates a reference.”

I tried the following code on PostgreSQL and observed the described results, a coworker of mine observed the same behaviour with MySQL.

```swift
struct CategoryAddCreator: Migration {
    typealias Database = PostgreSQLDatabase

    static func prepare(on connection: PostgreSQLConnection) -> EventLoopFuture<Void> {
        return Database.update(Category.self, on: connection) { builder in
            try builder.field(for: \.creator, referencing: \User.id)
        }
    }

    static func revert(on connection: PostgreSQLConnection) -> EventLoopFuture<Void> {
        // …
    }
}
```

Table before running migration:

<img width="1062" alt="before" src="https://user-images.githubusercontent.com/171604/40474455-0b195c3e-5f7a-11e8-901d-035d092f45ba.png">

Table after running migration (fourth column should show foreign key constraint to `users.id`):

<img width="1062" alt="after" src="https://user-images.githubusercontent.com/171604/40474505-2ebaf666-5f7a-11e8-8178-4865647a484e.png">

**Comment by tanner0101** [comment]
@Cellane I recently fixed a bug in vapor/sql where ALTER queries were not serializing constraints. That seems highly likely to be what caused this. It will be released in Fluent 3.0.0 👍

**Comment by randomiser** [comment]
Could we have this example added to the vapor docs for fluent? 

It's not immediately obvious from the documentation how you can make arbitrary migrations like this.

**Comment by Cellane** [comment]
I suspect that the Fluent documentation will contain this and more once it’s finished with Fluent 3’s final release.

**Comment by Cellane** [comment]
I just tried to reproduce this issue in the latest version of Fluent and am happy to announce that it was, indeed, fixed! 🎉 

Closing the issue, I hope that’s fine.
