### ISSUE TITLE
simplify table name generation

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent#492]
Currently, Fluent just adds an `s` to the end of the lowercased type name to generate table names. This has better performance than trying to generate correct plural forms of the words, but is obviously not correct in all cases. It is also not as performant as it could be since it requires lowercasing the type name. It is awkwardly in between being correct sometimes and being performant. I propose two different solutions:

1. Just use the type name as the table name:

IMO, there's not a huge benefit to trying to transform the type name into a traditional SQL name. All strings in Fluent are escaped anyway. If we're being utilitarian, there's no reason to waste CPU resources generating "prettier" names you shouldn't have to interact with them directly anyway.

This would be a breaking change, but is easily remedied by implementing `static let entity: String` and would be much more performant.

2. Do a good job generating correct table names:

This would require quite a bit of work to get right--english is quite complex. Avoiding regex would be key. And ideally we would want to cache the result of the computation so that it doesn't affect performance. Although this is debatable since you could just implement the `static let entity: String` property if you wanted the extra performance. The key is implementing this is a nice, maintainable way. 

Thoughts?

**Comment by MrMage** [comment]
Also for option 1. If one wants to get fancy, they can still override the table name.

**Comment by grundoon** [comment]
The only winner in (2) is the grammar purist, and even then there is no One True Purity (persons vs people, fish vs fishes). Words whose plural is no change (sheep, deer). Words that **have no** plural (who, what). Model `AttorneyGeneral` sounds like fun.

(1) is the sensible, almost surely right, path. But breaking change... is it not possible to reflect an existing entity's name into `entity` on migration?

**Comment by grosch** [comment]
This seems strange to me.  I like the default of adding the 's' as it's right more often than not, at least in my use cases.  The one time it was wrong, I simply added the `static let entity` to the table and the problem was solved.
