### ISSUE TITLE
customSQL not modifying the query

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#495]
```swift
                let stations = try client.stations
                    .query(on: req)
                    .sort(\Station.name)
                    .customSQL { query in
                        if case .query(var dataQuery) = query {
                            dataQuery.columns = [
                                DataQueryColumn.column(DataColumn(table: nil, name: "name"), key: nil)
                            ]
                        }
                    }
                    .all()
                    .map(to: [String].self) { stations in
                        return stations.map { $0.name }
                    }
```

If I understand the customSQL properly that should result in just querying the name column but when I look at the debug log it says it's querying everything:

```sql
SELECT * FROM "stations" 
WHERE ("stations"."client_id" = $1 AND ("stations"."deleted" IS NULL OR "stations"."deleted" > $2))
ORDER BY "stations"."name" ASC
```

 ["BIGINT (binary) \0\0\0\0\0\0\0\u{1B})", "TIMESTAMP (binary) \0\u{02}\u{10}:cY¶`)"]

**Comment by rafiki270** [comment]
That should, I merged that change myself, can you show me your Package.swift?
The only thing that comes to mind is that the columns get reset when used on a relation, could you test this works directly on the table? If that works I might be a quick fix ...

**Comment by grosch** [comment]
```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "dts",
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.1"),
	.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc.2"),
	.package(url: "https://github.com/vapor/leaf.git", from: "3.0.0-rc.2")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentPostgreSQL", "Vapor", "Leaf"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```
 
I changed the code to be `Stations.query(on: req)...` but it still came back with a `SELECT *`

**Comment by grosch** [comment]
I just ran `vapor update -y` and then modified the code to have some prints:

```swift
 _ = Station.query(on: req).customSQL { query in
          print("In custom SQL")
          if case .query(var dataQuery) = query {
              print("Found a query")
              dataQuery.columns = [
                  DataQueryColumn.column(DataColumn(table: nil, name: "name"), key: nil)
              ]
              debugPrint(dataQuery.columns)
          }
        }
        .all()
```

This is what appears in Xcode's console:

> In custom SQL
Found a query
[SQL.DataQueryColumn.column(SQL.DataColumn(table: nil, name: "name"), key: nil)]
[psql] [2018-05-28 15:26:30 +0000] SELECT * FROM "stations" WHERE (("stations"."deleted" IS NULL OR "stations"."deleted" > $1)) ["TIMESTAMP (binary) \0\u{02}\u{10}D¯1\r)"]

**Comment by grosch** [comment]
```json
      {
        "package": "SQL",
        "repositoryURL": "https://github.com/vapor/sql.git",
        "state": {
          "branch": null,
          "revision": "1bb94271d8645b6d6983721080ad642aa35d749c",
          "version": "1.0.0"
        }
      }
```

That's what is in my Package.resolved for sql

**Comment by grosch** [comment]
@rafiki270 Any thoughts on what might be happening?

**Comment by tanner0101** [comment]
`customSQL` has been removed as there is no longer a need for it. You now have access to the SQL query being built via the query builder (`builder.query`). You should be able to add custom columns that way now 👍

**Comment by grosch** [comment]
@tanner0101 A sample would be a beautiful thing indeed :)

**Comment by grosch** [comment]
@tanner0101 builder.query doesn't mean anything to me.  Can you please show an example of using this?
