### ISSUE TITLE
Allow filters without variables

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#496]
I'm sorry if this is already supported.  I just couldn't find it anywhere, and I asked in the Discord channel too.   It seems like .filter() requires that the comparison include a variable in it.  I am wanting to do something like this:

```swift
try Order.query(on: req).filter(\Order.complete < \Order.wanted).all()
```

**Comment by tanner0101** [comment]
Agreed, that should work. I will see if we can add it 👍

**Comment by tanner0101** [comment]
This is supported in Fluent 4: https://github.com/vapor/fluent-kit/blob/master/Sources/FluentBenchmark/Tests/Filter.swift#L12
