### ISSUE TITLE
Database Schema other than public

### ISSUE THREAD

**Issue by RVijay007** [vapor/fluent#501]
Hi, I'm using Vapor 3 to build a swift server that connects to an existing db within our organization. I've read the docs on how to connect to an existing database, but I'm still unclear on how to hook up Models to a specific schema. It seems to always use the `public` db schema; how can I use a schema other than `public`?

We use Postgres as our database.

**Comment by 0xTim** [comment]
If you configure your Postgres DB as normal in Vapor and then set the `defaultDatabase` property on the model it should work. (Also, don’t use a migration)

Details here https://forums.swift.org/t/new-to-swift-and-vapor-returning-data-from-mysql/13088

**Comment by RVijay007** [comment]
I do that with a test db, but it is picking up only tables made in the `public` schema, and I'm not sure how to get it to use one of our other schema groupings instead.

**Comment by fwgreen** [comment]
@RVijay007 The [your issue is driver related](https://github.com/vapor/postgresql/issues/9) and is [finally](https://github.com/vapor-community/postgresql/issues/30) (hopefully) being addressed.

**Comment by tanner0101** [comment]
Closing here in favor of https://github.com/vapor/postgresql/issues/9. There are a couple of good solutions there 👍.
