### ISSUE TITLE
How to join on joined model?

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/fluent#502]
Is there a way to join on joined model key?
I have `Record` with relation to `User`, `User` has relation to `Autoshop`.

With raw sql query I can

```sql
SELECT
///
FROM "Records" as r
LEFT JOIN "Users" as owner ON r."idOwner" = owner.id
LEFT JOIN "Autoshops" as autoshop ON owner."idAutoshop" = autoshop.id
```

Trying to do the same with `QueryBuilder`

```swift
try Record.query(on: req).range(lower: 0, upper: 30)
    .join(field: \User.id, to: \Record.idOwner)
    .alsoDecode(User.self)
    //below won't compile
    .join(Autoshop.self, field: \User.idAutoshop, to: \Autoshop.id, method: .inner) 
    .alsoDecode(Autoshop.self)
```

but it won't compile this way

Is there a way to reach `User`'s `Autoshop` while fetching `Record`?
Or subquery for every record is the only way?

I believe that join on joined model is a very common future that should be supported by Fluent

**Comment by tanner0101** [comment]
@MihaelIsaev this can be done now like so:
```swift
join(\Autoshop.id, to: \User.idAutoshop)
```
