### ISSUE TITLE
Calling `restore()` on a query fails to restore deleted models

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#504]
Calling `restore()` on a single model like this succeeds in restoring the model: 

```swift
myModel.restore().wait()
```

However, calling `restore()` on a query of models does not successfully restore the models:

```swift
MyModel.query(on: req).filter(\.id ~~ [1, 2, 3]).restore()
```

The second example generates the following SQL:

```sql
UPDATE `my_model` SET `deletedAt` = ? WHERE (`my_model`.`deletedAt` IS NULL OR `my_model`.`deletedAt` > (?)) AND `my_model`.`id` = ? [null, time(MySQL.MySQLTime(year: 2018, month: 6, day: 15, hour: 15, minute: 11, second: 25, microsecond: 244897)), integer8(1), integer8(2), integer8(3)]
```

**Comment by tanner0101** [comment]
@mcdappdev I believe you need to do:

```swift
MyModel.query(on: req, withSoftDeleted: true).filter(\.id ~~ [1, 2, 3]).restore()
```

When you call `Model.restore()`, it internally creates a query builder that includes soft-deleted models (that flag set to true). When you create the query builder in the second example, the flag is defaulting to false which excludes soft-deleted models.

**Comment by mcdappdev** [comment]
Ahhhh, yeah that would make sense. I'll give that a shot

**Comment by mcdappdev** [comment]
That did it! Thanks
