### ISSUE TITLE
Typo in enableReferences method name

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#505]
Located in `DatabaseConfig+References.swift`

**Comment by ezfe** [comment]
https://github.com/vapor/fluent/blob/3b52f5c2124a40460418881ca64305eb39023e43/Sources/Fluent/Schema/DatabasesConfig%2BReferences.swift#L2

**Comment by mcdappdev** [comment]
@ezfe Thank you!

**Comment by ezfe** [comment]
Also
https://github.com/vapor/fluent-sqlite/blob/1ac281bba44f8a9bf2f5196e0fa082d7ce9ccf3c/Tests/FluentSQLiteTests/SQLiteBenchmarkTests.swift#L312
