### ISSUE TITLE
What's the key?

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#508]
Timestampable and SoftDeletable both say that they're supported by an optional static key...but don't specify what the key is or how to implement.

**Comment by grosch** [comment]
OK, found it's `createdAtKey`, `updatedAtKey` and `deletedAtKey`.  Would be good if the deprecation notice said that explicitly.

**Comment by tanner0101** [comment]
Sorry that was unclear. Glad you found the correct solution. To reiterate incase anyone else ends up here:

`Timestampable` and `SoftDeletable` were merged with `Model`. To opt-in to using timestamps, you just implement the timestamp keys you want. This allows for more fine-grain control over which fields you'd like to use.

### Deprecate

```swift
struct Planet: Model, Timestampable, SoftDeletable {
    static let createdAtKey: WriteableKeyPath<Planet, Date?> { return \.createdAt }
    static let updatedAtKey: WriteableKeyPath<Planet, Date?> { return \.updatedAt }
    static let deletedAtKey: WriteableKeyPath<Planet, Date?> { return \.deletedAt }
}
```

### New

```swift
struct Planet: Model {
    static let createdAtKey: WriteableKeyPath<Planet, Date?>? { return \.createdAt }
    static let updatedAtKey: WriteableKeyPath<Planet, Date?>? { return \.updatedAt }
    static let deletedAtKey: WriteableKeyPath<Planet, Date?>? { return \.deletedAt }
}
```

Notice that the `WriteableKeyPath` are now _optional_. They are `nil` by default. `nil` tells Fluent not to try and set that key path during create, save, etc.

### New w/ TimestampKey

There is also a new type-alias for `WriteableKeyPath<Self, Date?>` called `TimestampKey`.

```swift
struct Planet: Model {
    static let createdAtKey: TimestampKey? { return \.createdAt }
    static let updatedAtKey: TimestampKey? { return \.updatedAt }
    static let deletedAtKey: TimestampKey? { return \.deletedAt }
}
```
