### ISSUE TITLE
Siblings access control breaking change

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/fluent#513]
Previous to RC3 I had an extension on `Siblings` so I could get siblings sorted by an additional field in the pivot.

`relatedPivotField` and `basePivotField` have changed to `internal` access so it no longer works. `QuerySort` also seems to have changed.

If there is a better way or workaround to get this same functionality I would appreciated the help. Or possibly change those properties back to public, though I'm sure you had a good reason to change it.

```swift
extension Siblings where Base.Database: QuerySupporting {

	public func query(on conn: DatabaseConnectable, sortedBy field: QuerySort) throws -> QueryBuilder<Related, Related> {
		return try Related.query(on: conn)
			.sort(field)
			.join(field: relatedPivotField)
			.filter(Through.self, basePivotField, .equals, .data(base.requireID()))

	}
}
```

**Comment by tanner0101** [comment]
I think you could achieve that by doing something like:

```swift
extension Siblings {
    public func query<T>(on conn: DatabaseConnectable, sortedBy key: KeyPath<Related, T>) throws -> QueryBuilder<Related.Database, Related> {
        return try query(on: conn).sort(key)
    }
}
```

Not really sure if that adds much value though (maybe I'm misunderstanding the original issue?).

```swift
planet.moons.query(on: req).sort(\.name).all()
planet.moons.query(on: req, sortedBy: \.name).all()
```

Seems like just calling normally is actually less code. Hopefully that works!

Otherwise, if I'm missing something, let's re-open and figure out a solution. :)

**Comment by grahamburgsma** [comment]
Sorry, I left out what I'm trying to do. I'm trying to sort on a column in the pivot table. So, I have a `Trips` table and `Locations` table. A trip can have many locations, but they are ordered. So my pivot table has (`tripId`, `locationId`, `order`).

The solution you provided would only allow me to sort on a Location value. I need to sort on the pivot.

Hope that makes sense. Any ideas for how to accomplish this?
