### ISSUE TITLE
In Memory Storage

### ISSUE THREAD

**Issue by vdka** [vapor/fluent#52]
# In Memory Storage

* Author(s): [vdka](https://github.com/vdka)
* Status: **[Awaiting review](#rationale)**

## Introduction

An in memory storage mechanism for use with fluent would assist greatly during development.

## Motivation

While developing an application or experimenting with vapor it would be nice to have all of the niceness of fluent without the commitment of setting up a full persistence stack. In memory storage would make this possible.

In addition, in memory storage could also be helpful for an extremely basic cache layer.

**Comment by tannernelson** [comment]
This is a great idea. That would also solve the problem of needing to make the default database optional. The default could be memory.

**Comment by LoganWright** [comment]
I think we can all agree that this is approved, let's mark it and we'll see when we can get some devs on it.

**Comment by tannernelson** [comment]
This has been merged but not tagged yet.
