### ISSUE TITLE
Reflection incorrect with custom encoders/decoders

### ISSUE THREAD

**Issue by proggeramlug** [vapor/fluent#524]
This bug has kept me sleepless for a few nights now, I am not sure if this is a fluent bug or a swift bug.

Let's say we have a class:
```swift
class User: Content, MySQLModel { // or whatever
        var email: String
        var active: Bool

init(from decoder: Decoder)throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.email = try container.decode(String.self, forKey: .email)
        // this is causing problems
        self.active = try container.decodeIfPresent(Bool.self, forKey: .active) ?? false
        }
}
```

Now, if I run a query like this:
```swift
let users = User.query(on: request).filter(\.active == true).all()
```

The resulting actual mysql query looks like:
`SELECT * FROM `user` WHERE `user`.`email` = ? [integer1(1)]`

Which leads me to believe that somehow fluent is not getting the property right. So I looked at the reflected properties via `try User.reflectProperties(depth: 0)` and what I am getting this is:
```[email: <String>, active: Optional<Bool>]```

And this explains the problem: The reflection/fluent thinks that "active" is optional because I am parsing via `decodeIfPresent`. The actual variable `active` is not optional however, I am just not requiring it in my content decoder (for whatever reason).

So, my current work around is this:
```swift
    do {
         self.active = try container.decode(Bool.self, forKey: .active)
    }
    catch {
        self.active = false
    }
```

Which is much longer and requiring a do-catch block. I'd love for Fluent to just read the property correctly but the implementation is so complex that I was hoping @tanner0101 would have a great idea what could be the fix. :)

Note: If `active` was marked as `Bool?` everything would be fine, however for different reasons that is not what I can do here.
Note 2: This is copied from a real life project and reduced for simplicity. If helpful I can put together a sample project that illustrates this exactly.

**Comment by tanner0101** [comment]
Very interesting. (This is actually a problem with vapor/core, so I will move the issue there). 

The `decodeIfPresent` issue resulting in an optional is not really a bug, that's expected. The decoder is trying to detect what kind of data can _create_ an instance of your model. And it's accurately discovering that your model can be initialized by an optional bool at that key. 

If you don't want Fluent to migration a nullable column for that field, the solution would be to do a manual migration. 

The concerning part is that `filter(\.active == true)` is resulting in the wrong key name. I'll look into this and see what I can find.

**Comment by tanner0101** [comment]
Moved to https://github.com/vapor/core/issues/161.
