### ISSUE TITLE
Cannot use `children()` with a `let` foreign ID (RC 4.0.2)

### ISSUE THREAD

**Issue by bygri** [vapor/fluent#532]
Fluent 3.0.0 RC 4.0.2, Swift 4.1.

The following code fails to compile with the error "No 'children' candidates produce the expected contextual result type 'Children<User, Pet>" reported on the third-last line.

```swift
final class Pet: Model {
  let userID: UUID
  ...
}
final class User: Model {
  var id: UUID?
  ...
  var pets: Children<User, Pet> {
    return children(\.userID)
  }
}
```

However, if you change the `let` on the second line to `var`, the code compiles successfully.

**Comment by linqingmo** [comment]
It's because
```swift
public func children<Child>(_ parentID: WritableKeyPath<Child, Self.ID>) -> Fluent.Children<Self, Child> where Child : Model, Self.Database == Child.Database
```
```swift
children needs WritableKeyPath<Child, Self.ID>, so it cannot be a let value.
```

**Comment by bygri** [comment]
Cheers @linqingmo. I feel there's value in allowing `let` values to be children.

I had a look at making a PR but until Fluent has full test coverage I'm not comfortable making any changes. It appears, however, that `WriteableKeyPath` could be simply swapped out for `KeyPath` as the parent ID is never edited, or at least new cases added to `ParentIDStorage` to handle writeable and non-writeable key paths.

**Comment by linqingmo** [comment]
I think ```KeyPath``` is good.

**Comment by tanner0101** [comment]
Agreed, I think this is fine being just `KeyPath`.

**Comment by bygri** [comment]
@tanner0101 should I make the PR for this?
