### ISSUE TITLE
No support for UPDATE IGNORE

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#536]
It is possible to issue `INSERT IGNORE` queries (or the equivalent in non-MySQL databases) using Fluent's `create(orIgnore:on:)` API, used for silently ignoring duplicate key collisions when creating new models. MySQL and other databases also support the `UPDATE IGNORE` formulation, which is useful for ignoring similar collisions when updating existing models. As with `INSERT IGNORE`, `UPDATE IGNORE` combined with the query's affected row count forms the basis of various atomic operations thanks to the database's ACID guarantees.

**Comment by tanner0101** [comment]
Related to https://github.com/vapor/sql/issues/22. MySQL seems to be the only dialect that supports `INSERT/UPDATE IGNORE`, so we should probably add this to `FluentMySQL`. See https://github.com/vapor/fluent-mysql/blob/master/Sources/FluentMySQL/QueryBuilder%2BCreateIgnore.swift.

**Comment by tanner0101** [comment]
Track here: https://github.com/vapor/fluent-kit/issues/50
