### ISSUE TITLE
It is not possible to generically specify SchemaReferenceActions on a foreign key constraint

### ISSUE THREAD

**Issue by 0xTim** [vapor/fluent#538]
Because `SchemaReferenceAction` is purely an associated type on `SchemaSupporting` with no protocol constraint (especially, not linked to `SQLForeignKeyAction`), it is not possible to implement `Migration` generically over a given `Database: SchemaSupporting` in the presence of calls to `SchemaBuilder.reference(from:to:onUpdate:onDelete:)`, as there will be no concrete type for `SchemaReferenceAction` and therefore no possible actions to specify. A common set of actions available in all schema-supporting databases should be provided.

**Comment by tanner0101** [comment]
Agreed, this would be nice. In the interim, you can use `where SchemaReferenceAction: SQLForeignKeyAction` which will apply to SQLite, MySQL, and PostgreSQL.

**Comment by tanner0101** [comment]
Migration / DatabaseSchema is no longer generic in Fluent 4.
