### ISSUE TITLE
Bug: `addIndex` *always* creates a unique index, even if `isUnique: false` is set (the default)

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent#540]
https://github.com/vapor/fluent/blob/86eb8812415fa33674793e37482a9e6455be0a0f/Sources/Fluent/Utilities/Deprecated.swift#L106

just calls through to `unique(on: to)`, **thus always creating a unique index**.

This is behaving very differently from what is expected; if the deprecated method's behavior can no longer be provided, the method should be removed entirely instead of causing behavior different from what its contract promises.

Also, are there any plans to support non-unique indexes again in the future, or are we supposed to run raw SQL for this now? (Related to #534.)

**Comment by tanner0101** [comment]
Indexes are supported as separate queries now (which better matches how they work at the driver level). See:
- https://github.com/vapor/sql/pull/16
- https://github.com/vapor/fluent/issues/515

Basically in a migration you will do this:

```swift
conn.create(index: "test_idx", on: \Planet.name).unique.run()
conn.drop(index: "test_idx").run()
```

**Comment by MrMage** [comment]
I think we should still remove this old methods rather than keep them with _wrong_ behavior. If you ask to create a non-unique index, creating a unique one is still a bug, even if the called method is deprecated.

**Comment by tanner0101** [comment]
Agreed, I'll make sure that gets removed 👍

**Comment by tanner0101** [comment]
These old methods have been removed. Thanks @MrMage!
