### ISSUE TITLE
Computed values during an insert

### ISSUE THREAD

**Issue by Cellane** [vapor/fluent#542]
Even after issue #541 is resolved, the code linked there contains a possible race condition – the value of the `order` column should be calculated at the time of insertion, not before.

Having computed values as a part of insert statement is currently impossible in Fluent, but would be a nice addition. The resulting SQL coming out of Fluent would look something like this:

```sql
INSERT INTO ... (order, ...) VALUES (MAX(order) + 1, ...)
```

**Comment by tanner0101** [comment]
This should be possible in Fluent 4 using  `.custom`.

```swift
Order.query(on: db).set(\.$order, to: .custom("MAX(order)")).create()
```
