### ISSUE TITLE
remove auto migrate option

### ISSUE THREAD

**Issue by tanner0101** [vapor/fluent#546]
Currently the `FluentProvider` offers an `autoMigrate` option that defaults to `true`. When this is enabled, migrations will run each time the application boots. 

This setting can cause problems if you attempt to revert failing migrations using the `revert` command. Ideally this setting would be removed and migrations would be run explicitly using the `migrate` command. This would make Fluent function more similarly to other ORMs and give more control to the user. 

This would be a breaking change and should be considered for Fluent 4.

**Comment by pedantix** [comment]
here here!

**Comment by vzsg** [comment]
I think that instead of removing an otherwise useful feature, the `revert` command should be fixed to suppress forward migrations when being executed.

**Comment by tanner0101** [comment]
The problem with that approach is that there's no way to know if/when a revert is happening from a provider. There isn't reliable access to the run arguments (which would be dodgy anyway because `RevertCommand` can be registered as a string other than `"revert"`). The auto migrate lifecycle hook must also run _before_ commands (since we want it to happen before the never-returning serve command. 

To do this feature properly we would need to make some big changes to either providers or commands (or potentially both). IMO not worth it since those APIs seem to be working fine otherwise. 

There's also a question of scalability (should an app with potentially hundreds of migrations be running them each time the app boots during development?).

FWIW, It seems many other frameworks / ORMs do migration as a separate step.

**Comment by halfnibble** [comment]
From my experience working with Django, migrations work well as two separate commands.
1. `makemigrations`, which inspects a model in its current state, compares that to a description saved in the database, and automatically generates a migration based on the difference.
2. `migrate`, which runs any migrations not registered as having been ran in the current database.

These two commands are separate from the build/run command. It has always worked very well for me.

**Comment by tanner0101** [comment]
This change has been added in Fluent 4 for a while now. Migrations now longer run by default. You can run them the following ways:

- `vapor run migrate` from the CLI
- Adding `migrate` to the Run scheme's arguments in Xcode
- Add the `--auto-migrate` flag when running your application (Fluent 3 behavior)
- Use `app.autoMigrate().wait()` programatically (Good for testing)
