### ISSUE TITLE
Unable to set default text

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#548]
After the last upgrade this no longer works:

```swift
builder.field(for: \.password, type: .text, .default("abc"))
```

**Comment by grosch** [comment]
Any thoughts around this?

**Comment by rafiki270** [comment]
I remember Tanner mentioned some properties that you set on the field directly ... if I only remembered where I implemented this ... it was like the last param would take an array of all the possible optionals you could think of

**Comment by rafiki270** [comment]
needs to be one of the `SQLColumnConstraint` types I believe, various field methods are in `SchemaBuilder` and `SchemaBuilder+Field`

**Comment by tanner0101** [comment]
This should be possible in Fluent 4 using `.custom`:

```swift
builder.field("password", .string, .custom("DEFAULT 'foo'"))
```
