### ISSUE TITLE
`Type of expression is ambiguous without more context` in `FilterOperator` 

### ISSUE THREAD

**Issue by lukenewman** [vapor/fluent#551]
I'm trying to query my SQLite database but am running into the following error:

![screen shot 2018-07-25 at 5 43 45 pm](https://user-images.githubusercontent.com/5315645/43229300-4d09b466-9032-11e8-803c-ed4f15494a81.png)

However, I'm doing exactly what is outlined in the [docs](https://docs.vapor.codes/3.0/fluent/querying/) (see "Querying" section).

My `User` object is a proper `SQLiteModel`. I'm not sure what is causing the confusion. Any help is greatly appreciated!

**Comment by calebkleveter** [comment]
Have you imported Fluent? People often get this error if they forget that.

**Comment by lukenewman** [comment]
🤦🏻‍♂️ 

Thank you, @calebkleveter
