### ISSUE TITLE
Setting defaultDatabase makes Model unable to synthesize initializer

### ISSUE THREAD

**Issue by JohnCoates** [vapor/fluent#559]
Seems to be a Swift 4.1 bug, but figured I'd let you know about this error: 
```
fluentCodableBug.swift:8:13: error: class 'notAbleToSynthesize' has no initializers
final class notAbleToSynthesize: Codable, SQLiteModel {
            ^
fluentCodableBug.swift:10:9: note: stored property 'property' without initial value prevents synthesized initializers
    let property: String
        ^
```

Repo to reproduce: https://github.com/JohnCoatesOSS/fluentCodableBug

File one
```
import FluentSQLite

final class synthesizedCorrectly: Codable, SQLiteModel {
    var id: Int?
    let property: String
}

final class notAbleToSynthesize: Codable, SQLiteModel {
    var id: Int?
    let property: String
}

func localConfigure() {
    synthesizedCorrectly.defaultDatabase = .sqlite
}
```

File two
```
import FluentSQLite

func configure() {
    notAbleToSynthesize.defaultDatabase = .sqlite
}
```

**Comment by 0xTim** [comment]
@JohnCoates isn't that because `property` doesn't have a value set? So if you set it to `let property = "someString"` it works?

**Comment by JohnCoates** [comment]
Initializers are supposed to be synthesized regardless. Take a look at `synthesizedCorrectly`, why is that class's init function able to be synthesized correctly?

**Comment by grundoon** [comment]
Yeah, it's just compiler glitch (and @0xTim is correct) – with 4.1.2 I eventually (though not initially) get this:

<img width="864" alt="screen shot 2018-08-06 at 10 07 21" src="https://user-images.githubusercontent.com/876321/43730580-9f38aa12-9960-11e8-8784-aa6064659023.png">

**Comment by JohnCoates** [comment]
Ah okay, thanks for the heads up. I figured that inheriting Codable bypassed the need for a manual init in classes. Sad to see that's not the case.
