### ISSUE TITLE
Accept `DatabaseConnectionPool` as `DatabaseConnectable`

### ISSUE THREAD

**Issue by mcdappdev** [vapor/fluent#562]
Per Discord discussion, enabling this: 

```swift
struct MySQLUserRepository: UserRepository {
    let db: DatabaseConnectionPool<MySQLDatabase>
    init(_ db: DatabaseConnectionPool<MySQLDatabase>) {
        self.db = db
    }

    func all() -> Future<[User]> {
        User.query(on: db).all()
    }
}
```

**Comment by tanner0101** [comment]
Fluent 4's tests include some examples of how to achieve the repository pattern without needing to pass context into each method: https://github.com/vapor/fluent/blob/master/Tests/FluentTests/FluentRepositoryTests.swift
