### ISSUE TITLE
Make Bulk CRUD Operations a Single Query

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent#569]
As of opening this issue, it is not possible to save an array of models to a database with one operation. Instead, we have to map over the models and save each one:

```swift
models.map { $0.save(on: req) }.flatten(on: req)
```

https://github.com/vapor/fluent/pull/470 will allow saving an array with a single call on the developer's end, but it will still make multiple queries on the database. This should be changed to use a single query on the database, which should increase performance on the operation.

**Comment by tanner0101** [comment]
Fluent 4 has an extension on an array of models for creating them as a batch operation.

```swift
let earth = Planet(...)
let mars = Planet(...)
[earth, mars].create(on: db)
```

This executes as a single query.

**Comment by grennis** [comment]
@tanner0101 The example given does not execute as a single query. This can be verified by watching debug logs, where we see alternating "Fulfilling connection waitlist request" and "INSERT" statements logged. Checking the implementation of the array extension, it is the same as given in @calebkleveter example: it calls `create` on each model and then flattens the result. I think this issue should be re-opened.

**Comment by anonymouz4** [comment]
Bump @tanner0101

**Comment by 0xTim** [comment]
@anonymouz4 see https://docs.vapor.codes/fluent/query/#update

**Comment by grennis** [comment]
@0xTim I dont think that's what we are looking for though, because that's a query builder extension. It would be great to have a collection extension like there is for `create` - see https://github.com/vapor/fluent-kit/blob/main/Sources/FluentKit/Concurrency/Model%2BConcurrency.swift#L38

**Comment by 0xTim** [comment]
@grennis Ah I see, the reason why there's no equivalent for update is because there's no SQL syntax for that. Creating an array of models is one query. Updating an array of models with different values (as opposed to using the update) syntax is multiple queries, one for each row, so fluent doesn't provide that option. This is partially done to ensure end users make a conscious decision to do something that could potentially be very slow if updating a very large array

**Comment by grennis** [comment]
OK thanks @0xTim agreed, we can just loop over the array in the app and verify each update. Thanks
