### ISSUE TITLE
AND operator without previous WHERE

### ISSUE THREAD

**Issue by DesdeChaves** [vapor/fluent#572]
If I want to count to number of giant planets per galaxy the query is

```swift
 let query = try conn
                .select()
                .column(expression: .column(.keyPath(\Galaxy.name)))
                .column(.count(.all))
                .from(Galaxy.self)
                .join(\Galaxy.id, to:\Planet.galaxyID, method: .left)
                .where(try \Planet.mass >= 500)
                .groupBy(\Galaxy.id)
                .all(decoding: [String:Int].self)
 return query
```

In this output all galaxies that don't have giant planets are not reported because are NULL.  I want to translate the NULL to ZERO. To fix that I need to include the **AND** operator in the query, like this:

```swift
 let query = try conn
                .select()
                .column(expression: .column(.keyPath(\Galaxy.name)))
                .column(.count(.all))
                .from(Galaxy.self)
                .join(\Galaxy.id, to:\Planet.galaxyID, method: .left)
                .and(try \Planet.mass >= 500)
                .groupBy(\Galaxy.id)
                .all(decoding: [String:Int].self)
 return query
```

But there is **no AND** operator. I know that: **.join().where().where()** is translated in **JOIN ON WHERE AND** operators, but I do not know how to implement the **JOIN ON AND** operators without a previous **WHERE**.

**Comment by tanner0101** [comment]
@DesdeChaves this issue should be moved to [vapor/sql](https://github.com/vapor/sql). That's where all of the code you are referencing lives.

The `where` method on SQL query builders adds expressions to the query's `WHERE` statement. Hence the name. Joins do support arbitrary expressions  (see the [`SQLJoin`](https://github.com/vapor/sql/blob/master/Sources/SQL/SQLJoin.swift#L13) protocol), there is just no convenient way to build expressions there. I think that could be worth adding, though!

Please move this issue to the correct repo and we can continue discussing the feature request. Thanks!
