### ISSUE TITLE
Computed Column Values

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent#576]
At least some DB platforms support a computed property type column, where a cell's value can be the result of an operation between two other cells:

```mysql
CREATE TABLE [dbo].[Emp](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [Name] [varchar](50),
    [Price] [float] NULL,
    [Qty] [float] NULL,
    [total]  AS ([Price]*[Qty])
) ON [PRIMARY]
```

*[ref](https://stackoverflow.com/questions/21784599/create-a-table-column-as-a-sum-of-two-columns-in-sql)

Support for this kind of column would be a nice addition. You would probably have to have a custom type that supports it though. It might look something like this:

```swift
final class Item: Model {
    var price: Decimal
    var amount: Int
    let total = ComputedColumn(\.amount * \.price)
    // Other stuff...
}

let Item = Item(price: 1.50, amount: 12)
// Save, other operations...
print(item.total.value) // 18
```

**Comment by tanner0101** [comment]
+1 to this idea. I think you could achieve this currently in Fluent using vapor/sql to generate the table and then having the computed column be optional on your model (that way it can be `nil` when saving new instances of the model).

Making this easier to use / documented would be great though.

**Comment by tanner0101** [comment]
Track here https://github.com/vapor/fluent-kit/issues/76
