### ISSUE TITLE
join can pass compiler but throws error

### ISSUE THREAD

**Issue by andy1247008998** [vapor/fluent#578]
Let's say we have tableA and tableB.
In `func someFunc(_ req: Request) throws -> Future<[A.Public]>`

Code 1:
```
return A.query(on: req)
                .filter(\B.abc == A.abc)
                .join(\B.xyz, to: \A.xyz, method: MySQLJoinMethod.default)
                .decode(data: A.Public.self)
                .all()
```

Code 2:
```
return A.query(on: req)
                .filter(\B.abc == A.abc)
                .join(\A.xyz, to: \B.xyz, method: MySQLJoinMethod.default)
                .decode(data: A.Public.self)
                .all()
```

Code 3:
```
return B.query(on: req)
                .filter(\B.abc == A.abc)
                .join(\B.xyz, to: \A.xyz, method: MySQLJoinMethod.default)
                .decode(data: A.Public.self)
                .all()
```

Code1 works.
Code2 changes the order of parameters in `.join`'s from and to, won't work.
Code3 change the leading table from A to B, won't work.

Both code2 and code3 can pass the compiler, but generates unexpected behavior.

Error:
`[ ERROR ] MySQLError.server (1066): Not unique table/alias: 'TableName' (MySQLConnection.swift:90)`

**Comment by tanner0101** [comment]
I'm not sure there's much we can do to improve this. I think it's possible in SQL to [join a table to itself](http://www.sqlitetutorial.net/sqlite-self-join/). Even then, Swift has no way to do `!=` for generic constraints. 

Really all we can do here is verify that the columns being joined are of a matching type, which we already do. The rest is up to the SQL engine to determine whether or not the join is actually possible.
