### ISSUE TITLE
[Docs] Better explanation of how to set up Fluent without Vapor infrastructure

### ISSUE THREAD

**Issue by MrLotU** [vapor/fluent#583]
Right now the Docs only explain how to set up Fluent inside your Vapor application, the docs should also contains explanation of using Fluent without Vapor apps, so you can use it for general ORM purposes too

**Comment by MrLotU** [comment]
I'm still in the process of fully figuring this out, but once I get a hang of it, I'll submit a PR to the docs :)

**Comment by tanner0101** [comment]
Agreed, this would be nice. Especially going forward, as there are plans to decouple Fluent 4 even more from Vapor. (i.e., services, container, database-kit, etc). 

If you do come up with something for 3.0, I 'm happy to merge into docs. Otherwise, I think this is a good goal for 4.0.

**Comment by xeokeri** [comment]
I would appreciate this for a Vapor free command line tool as well. I have it partially working, but feel my solution is not the as bug free as I'd like it to be.

**Comment by tanner0101** [comment]
For Vapor 4 stuff, the driver packages' tests are a great reference for seeing how to configure Fluent without Vapor: https://github.com/vapor/fluent-sqlite-driver/blob/master/Tests/FluentSQLiteDriverTests/FluentSQLiteDriverTests.swift#L183-L188
vapor/fluent-kit and the drivers like vapor/fluent-postgres-driver, etc don't depend on Vapor. The dependency is only added in vapor/fluent which integrates fluent-kit + vapor.

**Comment by tanner0101** [comment]
Going forward, docs.vapor.codes will assume you are using the packages with Vapor. The package readmes will show docs on how to use the package standalone, for example: https://github.com/vapor/postgres-nio
