### ISSUE TITLE
Add HAVING Keyword Support

### ISSUE THREAD

**Issue by calebkleveter** [vapor/fluent#585]
The SQL `HAVING` keyword is used for filtering, but the difference is that `WHERE` is applied before `GROUP BY`, whereas `HAVING` is applied after and can filter on aggregates.

I'm opening this issue here because support would probably required changes in Fluent and Fluent integrations, along with the SQL repo.

**Comment by tanner0101** [comment]
Track here: https://github.com/vapor/fluent-kit/issues/31
