### ISSUE TITLE
Need an update method

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#592]
There should be a way to do an update without having to first do a select. It's not uncommon to do a select of a couple things, do a bunch of processing on them, and then have a couple UPDATE calls that need to be made.  

For example, after internal logic runs I know that the Person with id 15 needs to have their xyz property updated.  I shouldn't now have to query Person 15 again to make the change.  There should be some way to directly make the update call (without resorting to raw SQL of course)

**Comment by calebkleveter** [comment]
What about this?

```swift
Person.query(on: req).filter(\.id == 15).update(\.xyz, to: "Foo Bar").run()
```

**Comment by grosch** [comment]
But isn't that going to actually do a select call first?

**Comment by grosch** [comment]
Assuming that it doesn't query first...is there a way to get the future back instead of run(), which returns a void future?  I've got a bunch of these, so I'm building up an array of them and then doing a `flatten(on: conn)` type call.

**Comment by calebkleveter** [comment]
This does not do a `SELECT`. It is an actual `UPDATE` query.

> is there a way to get the future back instead of run(), which returns a void future?

Not really sure what you mean there. Do you have any examples?

**Comment by grosch** [comment]
```swift
return req.transaction(on: .psql) { conn in 
  var saves: [Future<WorkComplete>] = [];

  loop {
     if (isnew) {
       saves.append(WorkComplete...create(on: conn));
     } else {
       saves.append(WorkComplete...update(\.amount, to: 15));
     }
  }
}

return saves.flatten(on: conn).transform(to: .noContent)

**Comment by calebkleveter** [comment]
Because an `UPDATE` query doesn't return any data, you can't get a `WorkComplete` instance from it. You will either have to chain a `SELECT` query onto the future from the `.run()` call or pass the instance that updated into `.transform`. The second option doesn't give you back the updated model, so you might want to do the first.

**Comment by grosch** [comment]
So if I'm doing multiple updates, then I still need to have a select call is what I'm reading out of that.

**Comment by grosch** [comment]
@calebkleveter Finally getting back to this project again.  Can you expand on what you mean by the `.transform` please?  Here's my actual example of what I'm trying to do.  I don't know what to do with the "updates" part of this so that I don't have to do a query just to do the update.

```swift
    private func upsertOrderPoints(on conn: PostgreSQLConnection, for orderId: Order.ID, with orderPoints: [String: Double]) throws -> Future<Void> {
        _ = conn.select()
            .column(\OrderPoint.id)
            .column(\OrderPoint.amount)
            .column(\Point.abbrev)
            .column(\Point.amount)
            .column(.sum(\WorkComplete.amount), as: "complete")
            .from(OrderPoint.self)
            .join(\Point.id, to: \OrderPoint.pointID)
            .join(\WorkComplete.orderPointID, to: \OrderPoint.id, method: PostgreSQLJoinMethod.left)
            .where(\OrderPoint.orderID == orderId)
            .groupBy(\OrderPoint.id)
            .groupBy(\OrderPoint.amount)
            .groupBy(\Point.abbrev)
            .all(decoding: OrderPointData.self)
            .map { rows -> Future<Void> in
                var deletes: [Future<Void>] = [];
                var creates: [Future<OrderPoint>] = [];

                var mutableOrderPoints = orderPoints

                try rows.forEach { row in
                    guard let desiredAmount = orderPoints[row.abbrev] else {
                        // An existing abbrev type is no longer desired on the order
                        deletes.append(OrderPoint.query(on: conn).filter(\.id == row.orderPointId).delete())
                        return
                    }

                    mutableOrderPoints.removeValue(forKey: row.abbrev)

                    guard row.orderAmount != desiredAmount else {
                        // The existing abbrev type has the same amount as the new value
                        return
                    }

                    if let complete = row.complete, complete > desiredAmount {
                        throw Abort(.conflict, reason: "Already completed work for \(row.abbrev) exceeds new desired amount")
                    }

                    OrderPoint.query(on: conn).filter(\.id == row.orderPointId).update(\OrderPoint.amount, to: desiredAmount)
                }

                // Anything left in orderPoints are new types that need to be created
                Point.query(on: conn).all().flatMap { points in
                    var abbrevToPointId: [String: Point.ID] = [:]

                    points.forEach { point in
                        abbrevToPointId[point.abbrev] = point.id
                    }

                    mutableOrderPoints.forEach { abbrev, amount in
                        guard let pointId = abbrevToPointId[abbrev] else {
                            throw Abort(.badRequest, reason: "Abbrev \(abbrev) is not valid")
                        }

                        let op = OrderPoint(orderID: orderId, pointID: pointId, amount: amount)
                        creates.append(op.create(on: conn))
                    }

                    return creates.flatten(on: conn).flatMap { _ in
                        return deletes.flatten(on: conn).flatMap { _ in

                        }
                    }
                }
        }
    }
```

**Comment by calebkleveter** [comment]
`.transform(to:)` is a method that converts maps a future to an unrelated type. As example, I could do this:

```swift
User.query(on: req).delete().map { return HTTPStatus.ok }
```

But instead, I can call `.transform(to:)` on the future and pass in the instance I want to return:

```swift
User.query(on: req).delete().transform(to: HTTPStatus.ok)
```

**Comment by grosch** [comment]
Except `.update` doesn't have a `.transform` method available :(

**Comment by calebkleveter** [comment]
You have to run the query and get the future result before you can transform the result.

**Comment by grosch** [comment]
OK, I wasn't adding `.run()` to the end of the `.update()` call.  The run returns a future void, so I can `.flatten` that and then my issue is solved!  Thanks :)
