### ISSUE TITLE
Needed a query with alias

### ISSUE THREAD

**Issue by scinfu** [vapor/fluent#593]
I have a table ```File``` where can hame many ```TAG```
I'm trying to do a multiple join with table alias but i do not found how to do in Fluent
Here is a working query where i cant reproduce in Fluent
```
SELECT * FROM "File" 
INNER JOIN "File_Tag" ON "File"."id" = "File_Tag"."fileId" 
INNER JOIN "Tag" ON "File_Tag"."tagId" = "Tag"."id" 
INNER JOIN "File_Tag" AS File_Tag1  ON "File"."id" = File_Tag1."fileId" 
INNER JOIN "Tag" AS TAG1 ON File_Tag1."tagId" = TAG1."id" 
WHERE "Tag"."identifier" = "foo" AND TAG1."identifier" = "bar"
```

Any one can help me?

Thank you

**Comment by calebkleveter** [comment]
I don't think that is supported by fluent at the moment.I think your only options are to either figure out how to build it in and submit a PR or use a [raw query](https://docs.vapor.codes/3.0/fluent/getting-started/#raw-queries).

**Comment by tanner0101** [comment]
This is now possible with `ModelAlias`: https://github.com/vapor/fluent-kit/pull/75
