### ISSUE TITLE
JSON property manual migration crashes but auto migration works

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/fluent#594]
In the example below, `AutoTodo` migrates just fine and turns the `data` property into a `jsonb` column.

However, when trying to migrate `ManualTodo`, which manually specifies the fields in the migration, it crashes on [this line](
https://github.com/vapor/fluent/blob/master/Sources/Fluent/Query/FluentProperty.swift#L14). `Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ CoreError: 'TodoData' does not conform to 'ReflectionDecodable'.`

If the auto migration works, we should be able to specify it manually as well without issues.

```swift
struct TodoData: Codable {
    let title: String
}

final class AutoTodo: PostgreSQLModel, Migration {
    var id: Int?
    var data: TodoData
}

final class ManualTodo: PostgreSQLModel, Migration {
    var id: Int?
    var data: TodoData

    static func prepare(on conn: PostgreSQLConnection) -> Future<Void> {
        return Database.create(self, on: conn) { builder in
            builder.field(for: \.id, isIdentifier: true)
            builder.field(for: \.data, type: .jsonb)
        }
    }
}
```

**Comment by vzsg** [comment]
As a workaround, you can create a column definition manually, which seems to be what the automigration is doing behind the scenes:

```swift
final class ManualTodo: PostgreSQLModel, Migration {
    var id: Int?
    var data: TodoData

    static func prepare(on conn: PostgreSQLConnection) -> Future<Void> {
        return Database.create(self, on: conn) { builder in
            builder.field(for: \.id, isIdentifier: true)

            let col = PostgreSQLColumnDefinition.columnDefinition(.column(nil, "data"), .jsonb, [])
            builder.field(col)
        }
    }
}
```

**Comment by grahamburgsma** [comment]
Nice, thanks @vzsg. That's a good workaround for now!
