### ISSUE TITLE
Database may need Model information during encoding

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/fluent#597]
I am working on a mongo integration for Fluent.

In Fluent is possible to specify the `idKey` path for a specific `Model`.
For example:
```swift
struct User: Model {
  static var idKey: WritableKeyPath<User, UUID?> { return \.id }
  var id: UUID?
}
```
Problem is, in mongo, documents have a fixed `_id` field.

I want to `encode` my `User` model so that `id` becomes `_id` when encoded/decoded to the `Database.Output` type.

In general I think `Model`s should be free to define their `id` in whatever way they want, after all that's the purpose of having `fluentID` and `idKey` in the `Model`.

The database/driver should be in charge of transforming `id` to `_id` (in the above example).
Now this is not possible at the moment, because `Codable` delegates the serialisation to the model itself.

It feels that the database should be aware of the specific `Model` during encoding/decoding. In order to be able to access the `idKey` and modify the generated output accordingly.

From `QuerySupporting`:
`static func queryEncode<E>(_ encodable: E, entity: String) throws -> Output where E: Encodable`

@tanner0101 any idea?

**Comment by MrMage** [comment]
I'm not an expert in Fluent's serialization method, but would it be possible to declare a `CodingKey` enum (used by `Codable`) specifying that `id` should be encoded as `_id`?

**Comment by valeriomazzeo** [comment]
Yes, but then you'd have to to specify all the keys. As far as I know, it is not possible to just instruct Swift to specify manually one key and automatically synthesise the rest.

After talking with @tanner0101 he recommended to specify a custom model protocol that requires the `_id` variable.
