### ISSUE TITLE
Add DISTINCT to QueryBuilder

### ISSUE THREAD

**Issue by bygri** [vapor/fluent#599]
There appears to be no way, using Fluent, to create a `SELECT DISTINCT` query—or if there is, it is undocumented.

[Recent StackOverflow question](https://stackoverflow.com/questions/53030158)

Recent Discord conversation (31/10/2018):
mcdappdev: Anyone have an example of how to do a `DISTINCT` query?
jimmya92: Someone asked about it a few days ago so I looked into it. But it doesn't seem to be possible with Fluent as of yet.

**Comment by tanner0101** [comment]
Try this:

```swift
builder.query.distinct = .distinct
```

**Comment by grundoon** [comment]
Aside: I personally found that last night, but would it be possible to add a `distinct()` func analogous to its intimately related protocol partner `all()` into `Fluent`?

**Comment by bygri** [comment]
I can’t quite work that out using FluentMySQL:

```swift
var builder = MyObject.query(on: conn)
builder.query.distinct = .distinct
```

gives the error Value of type ‘MySQLDatabase.Query’ (aka ‘FluentMySQLQuery’) has no member ‘distinct’.

**Comment by grundoon** [comment]
Think it needs to be the `SQLSelectBuilder`?
 ```swift
 var select = MyObject.select(on: conn)
 select.distinct = .distinct
 ```

**Comment by tanner0101** [comment]
@bygri Ah yeah, sorry I forgot it would need to be added to [`FluentSQLQuery`](https://github.com/vapor/fluent/blob/master/Sources/FluentSQL/FluentSQLQuery.swift) first.

@grundoon using SQLKit directly would definitely work, since it knows about `SELECT DISTINCT`.

**Comment by bygri** [comment]
Thanks @tanner0101 and @grundoon. I have put in PRs to enable the behaviour `builder.query.distinct = .distinct`. I agree that `MyObject.query(on: worker).filter(…).distinct().all()` would be a further improvement but at least this will get me out of immediate trouble.
