### ISSUE TITLE
Joins use different ordering

### ISSUE THREAD

**Issue by grosch** [vapor/fluent#604]
When I'm using the "normal" querying methods, I do something like this:

```swift
Model.query(on: req)
    .join(\OtherModel.id, to: \Model.id)
```

Note how the *other* table comes first in the `join` call.  However, when I'm using the direct query methods, not the convenience ones, I do this:

```swift
conn.select()
   .from(Model.self)
   .join(\Model.id, to: \OtherModel.id)
```

The order of the parameters sent to the `join` are reversed.  It leads to annoying bugs that only appear at runtime.  The first one makes the most sense for somebody used to writing SQL, whereas the second method appears "wrong".  I don't want to join to myself.

**Comment by tanner0101** [comment]
Swift doesn't allow for `!=` generic constraints, so I don't think it would be possible to prevent this.
