### ISSUE TITLE
Support generic repositories (Facade Pattern)

### ISSUE THREAD

**Issue by fwgreen** [vapor/fluent#607]
With the current system one must create a repository for each entity in the domain.  This can be tedious when performing the same CRUD operations on each entity.  Support for generic repositories would really maximize code reuse and reduce copy/paste errors.  Maybe something along these lines could be possible in a future version:
```Swift
protocol AbstractRepository : ServiceType {
    associatedtype Entity : PostgreSQLModel
}

extension AbstractRepository {
    func find(id: Int) -> EventLoopFuture<Entity?> {
        return db.withConnection { conn in 
            return Entity.find(id, on: conn)
        }
    }

    func all() -> EventLoopFuture<[Entity]> {
        return db.withConnection { conn in
            return Entity.query(on: conn).all()
        }
    }
   //...
}

class Repository<E : PostgreSQLModel> : AbstractRepository {
    typealias Entity = E
}
```

**Comment by mcdappdev** [comment]
Hi @fwgreen! I agree with you, this would make life a lot easier for many people. It sounds like Fluent 4 is going to remove the generic constraint from models so it should make a life a whole lot easier when it comes to repositories. Until then there aren't a whole ton of ways around this except creating a new database model representation for each repository implementation (SQLite, Memory, MySQL, etc)

**Comment by tanner0101** [comment]
I agree. This should already be possible in Fluent 4's early dev branch, but I'll keep this issue open to make sure we test it.

**Comment by fwgreen** [comment]
This is now possible. Closing.
