### ISSUE TITLE
Pivot database not being prepared

### ISSUE THREAD

**Issue by BrettRToomey** [vapor/fluent#61]
# Overview
When using a `Pivot`, the entity will be prepared and everything will work the first time the app is ran, but any time after the database will fail to be set. This also happens if trying to save more than once in a single program execution.

My `Droplet` initialization looks like this 
```
let drop = Droplet(preparations: [User.self, Appointment.self, Pivot<User, Appointment>.self], providers: [VaporMySQL.Provider])
```
And the simple testing code I'm using is this
```
drop.post("appt")
{ req in
    guard
        let userId = req.data["user_id"].int,
        let user = try User.find(userId)
    else
    {
        throw Abort.badRequest
    }
    
    guard let appointment = try Appointment.find(1) else
    {
        throw Abort.serverError
    }
    
    var pivot = Pivot<User, Appointment>(user, appointment)
    
    try pivot.save()

    return appointment
}
```

# Workaround 
If this helps at all, manually calling `Pivot<User, Appointment>.database = drop.database` seems to fix all of the issues, but I was under the impression that adding the pivot as a preparation should do this for me.

# Comments
I talked with Tanner about this a little and he suspects that it may be due to the `Droplet` preparation code not casting the pivot as a `Model`.

**Comment by kdawgwilk** [comment]
I was looking for hours on how to do a many-to-many relationship with fluent and I could easily find what I needed to add to my models but had no idea how to get the relationship created and this SAVED me!  It would be nice to add these lines to the documentation:
```swift
var pivot = Pivot<User, Appointment>(user, appointment)
try pivot.save()
```
I was trying to use the create method on the `user.appts().create(appt)` and couldn't get it to work :(

I just submitted a PR vapor/documentation#68 to add to the docs
