### ISSUE TITLE
One-time default for migration

### ISSUE THREAD

**Issue by Blejwi** [vapor/fluent#612]
Hello,

Is this possible to provide a one-time default for my model migration?

I have following example model:
```swift
final class Todo: SQLiteModel {
    var id: Int?
    var title: String
}
```

And I would like to add the non-nullable field to model:
```swift
var description: String
```

But I don't want to set a default for all new records, just populate existing rows and every new row will require a description to be provided.

**Comment by tanner0101** [comment]
You usually do this in SQL by a multi step process where the column is altered in the second step. See: https://stackoverflow.com/questions/31807768/in-sql-how-to-add-values-after-add-a-new-column-in-the-existing-table

That said, it would be nice if Fluent had some helpers for this.

**Comment by calebkleveter** [comment]
In Fluent 4, the table structures could be tracked, and then if a new property is added, Fluent could automatically add the column to the existing table. If the field doesn't have a default value, Fluent could emit an error and exit.

```swift
class User: Model {
    // Existing columns here...

    // New column
    var metadata: Field<String> {
        return self.field(name: "metadata", type: .text, default: "This like to keep an air of mystery around them...")
    }
}
```

Fluent would automatically run this the next time the server boots:

```sql
ALTER TABLE `User` 
ADD 'metadata` 
TEXT NOT NULL DEFAULT(1) 
WITH VALUES 'This like to keep an air of mystery around them...' ;
```

If the type is an optional, the default value could automatically be `NULL`.

**Comment by Blejwi** [comment]
Yes, but this solution still adds default (in database) which cannot be deleted later according to https://github.com/vapor/fluent/issues/613.

Solutions that I can think of:
- Migrate data and schema using raw SQL
- Migrate schema be setting default in migration (using fluent) and delete default constraint using raw SQL `ALTER`.

Didn't test it yet, but does any of the solutions looks reasonable?

**Comment by tanner0101** [comment]
@Blejwi yeah that seems right to me.
