### ISSUE TITLE
Preserve the ability to set a model's default database in version 4.0

### ISSUE THREAD

**Issue by fwgreen** [vapor/fluent#622]
Looking through the new code, I didn't see `defaultDatabase` or some equivalent.  Either by intention or side-effect (the documentation was never clear), this feature allows one to use an existing database:
```Swift
Person.defaultDatabase = DatabaseIdentifier<PostgreSQLDatabase>.psql
```
This capability should be preserved in some form.

**Comment by tanner0101** [comment]
That will no longer be necessary in Fluent 4 since you will store a reference to your database on the controller (or wherever else you need it).

```swift
import Fluent
import Vapor

final class PlanetController {
    let db: Database
    func index(_ req: HTTPRequest) -> ELFuture<[Planet.Row]> {
        return Planet.query(on: self.db).all()
    }
}

let psql = container.connectionPool(to: .psql)
let planetController = PlanetController(db: psql)
```

That code isn't final yet, but hopefully it gives you an idea.
