### ISSUE TITLE
Feature Request: add `createdAt`, `updatedAt` and domain fields to `KeyedDatabaseCache`

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent#624]
(Or whatever that class will be called in the future.)

Motivation: So I can prune out old rows, and use the cache for more than one data type without losing my mind. (Currently, there is no way to tell what kind of data each row holds.)

**Comment by tanner0101** [comment]
Fluent 4 dropped the KeyedCache protocol in favor of using the session driver protocol directly now that Vapor is a dependency. This was the only thing keyed cache was used for internally and it was created as a workaround for the dependency structure. 

I've created an issue here to track whether we should introduce this protocol or not: https://github.com/vapor/vapor/issues/2375

If so, Fluent's conformance can take timestamps into consideration.
