### ISSUE TITLE
Update with data doesn't set updatedAt

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/fluent#625]
Using the `update(data: someEncodable)` doesn't set the `updatedAt` field.

Example:
```swift
User.query(on: conn).update(data: ["name": "Vapor"])
```

https://github.com/vapor/fluent/blob/3.1.3/Sources/Fluent/QueryBuilder/QueryBuilder%2BCRUD.swift#L28

**Comment by MrMage** [comment]
Personally I think there is a case to be made for updates that do not _want_ to update that field. Maybe it should be an option?

**Comment by grahamburgsma** [comment]
@MrMage that makes sense. Just the rest of the update methods _do_ set the `updatedAt` field and so I think this one instance is a bug.

**Comment by tanner0101** [comment]
Fluent 4 now updates timestamps when using the query builder directly.
