### ISSUE TITLE
Autoincrement to be defaulted to yes if Int, discarded if UUID [V4]

### ISSUE THREAD

**Issue by rafiki270** [vapor/fluent#643]
I give devs option which DB to use in which case I have to do something like `.field("id", .uuid, .identifier(auto: Webug.DbIdType.self == Int.self))` (please note the `.uuid` will be dynamic as well)

**Comment by tanner0101** [comment]
Dynamically changing what the schema builder does based on model is similar functionality to: https://github.com/vapor/fluent-kit/pull/139. Tim wrote a good response as to why Fluent wants to avoid doing that.
