### ISSUE TITLE
vapor-beta run migrate doesn't complete

### ISSUE THREAD

**Issue by rpstro02** [vapor/fluent#654]
After creating a project with the default template and a sqlite db, running a manual migration with `vapor-beta run migrate` in Terminal never completes after answering "Would you like to continue".  It appears the y or n response to the question is never registered.  Running `vapor-beta run --auto-migrate` on the same project results in a successful migration.

**Comment by tanner0101** [comment]
@rpstro02 could you try upgrading to the latest version of the toolbox? The latest patch should have fixed that.

**Comment by rpstro02** [comment]
You're right.  That fixed it.  Sorry.  I didn't check the toolbox version because I thought it was an issue with MigrateCommand.
