### ISSUE TITLE
Cannot decode Model with OptionalParent

### ISSUE THREAD

**Issue by jdanthinne** [vapor/fluent#655]
Here's a small User class I'm using to test Vapor 4, but the OptionalParent doesn't seem to work as expected.

```swift
final class User: Model, Content {
    static let schema = "users"

    @ID(key: "id") var id: Int?

    @Field(key: "email") var email: String

    @OptionalParent(key: "parent_id") var parent: User?
    @Children(for: \.$parent) var children: [User]

    init() { }

    init(id: Int? = nil, email: String, parentID: Int? = nil) {
        self.id = id
        self.email = email
        self.$parent.id = parentID
    }
}
```

If I submit `{"email": "john@appleseed.com"}`, I get the following error: `"Value required for key 'parent'."`.
And strangely, if I submit `{"email": "john@appleseed.com", "parent": null}` or `{"email": "john@appleseed.com", "parent_id": null}` (what is the rule, btw?), I get this one: `"The given data was not valid JSON. for key "`.

**Comment by 0xTim** [comment]
I think you need `"parent": {}` in your request

**Comment by jdanthinne** [comment]
Yes, that’s working, but is that the expected way to work, or a bug? From an API point of view, that’s strange and counterproductive.
If I now return the created User, I get 
```
{
  "id": 1,
  "email": "john@appleseed.com",
  "parent": {
    "id": null
  }
}
```
instead of 
```
{
  "id": 1,
  "email": "john@appleseed.com",
  "parent": null
}
```

**Comment by 0xTim** [comment]
It's to do with the way the `Parent` property wrapper overrides Codable.  It does look like it could be improved if the parent is nil

**Comment by jdanthinne** [comment]
Looking forward to seeing that coming… I've had a look at the implementation of the decoder, but I can't find which one is the right one (fluent-kit, sql-kit, …?).

**Comment by 0xTim** [comment]
This is the relevant code https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Properties/Parent.swift#L50

**Comment by jdanthinne** [comment]
Can you have have a look at https://github.com/vapor/fluent-kit/pull/138?

**Comment by tanner0101** [comment]
See https://github.com/vapor/fluent-kit/issues/224
