### ISSUE TITLE
ModelTokenAuthenticatable usage

### ISSUE THREAD

**Issue by massimodileonardo** [vapor/fluent#676]
If I setup an authentication system as explained in Vapor 4.0 -> Secutity -> Authentication

let tokenProtected = app.grouped(UserToken.authenticator())
tokenProtected.get("me") { req -> User in
    try req.auth.require(User.self)
}

 should the tokenProtected group block all requests with missing or wrong tokens, even without calling try req.auth.require(User.self)?

I can obtain this behavior only adding a guardMiddleware

let tokenProtected = app.grouped(UserToken.authenticator(), UserToken.guardMiddleware())

**Comment by 0xTim** [comment]
No, the `tokenProtected` group will only authenticate requests with the provided token. If the token doesn't exist or is invalid then it will just continue. This allows you to chain multiple authentication middlewares together.

If you want to block routes to unauthenticated users (which is a perfectly valid use case) then you need to use `GuardMiddleware` as you've seen.

**Comment by massimodileonardo** [comment]
Thanks for the explanation.
