### ISSUE TITLE
Make the Migration entity "__fluent" instead of "fluent"

### ISSUE THREAD

**Issue by NathanFlurry** [vapor/fluent#68]
# Name of Feature

* Author(s): [Nathan Flurry](https://github.com/NathanFlurry)
* Status: **[Awaiting review](#rationale)**

## Introduction

The Migration entity mainly stores metadata about migrations in Fluent. Therefor, the table name should not be `fluent` but something that denotes metadata like `__fluent`

## Motivation

Someone may one day com along and try and make a table called `fluent` and be very disappointed. However, that is quite unlikely. Just for clarity, it would be better to give the Migration entity a table name that sets it apart from normal tables. While this is fairly nit-picky, it's just something I feel should be done. 

## Proposed solution

I propose to give the table the name `__fluent` instead of `fluent`.

## Code snippets

_N/A_

## Impact

This will make Fluent re-prepare every model once the table name has been changed, since Fluent won't have a way to know if the entities are already prepared. This will also leave a redundant, unused table called `fluent` in everyone's database.

## Alternatives considered

It could also possibly be called something like `meta_fluent`.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tannernelson** [comment]
I was considering this, but Laravel for example calls their table `migrations` meaning you could never create a model `Migration`.

**Comment by tannernelson** [comment]
`_` isn't supported in Mongo, causes a crash. I think the chances of someone wanting to use `fluent` is very slim. Especially seeing as how `migrations` is taken in Laravel and I don't think that's been an issue for them. Closing this for now.
