### ISSUE TITLE
When updating existing table foreign key not assigned 

### ISSUE THREAD

**Issue by skyweb07** [vapor/fluent#681]
Hello!

I'm trying to add a new foreign key to an optional object after the main table is created but after running the migration the field gets created but the foreign key is not set in the new object 

<img width="1228" alt="Screenshot 2020-05-03 at 11 11 19" src="https://user-images.githubusercontent.com/747750/80910333-17c53180-8d2f-11ea-9b31-1c0cf7da3b07.png">

<img width="751" alt="Screenshot 2020-05-03 at 11 14 29" src="https://user-images.githubusercontent.com/747750/80910371-47743980-8d2f-11ea-8364-7f73105ad8b7.png">

This only happens when updating an existing table to add a new foreign key as when creating works perfectly. I've seen that on Fluent 3 this used to happen, maybe something to take a look at https://github.com/vapor/fluent/issues/491

**Comment by tanner0101** [comment]
I believe this was related to https://github.com/vapor/fluent-kit/issues/235 and has been fixed in https://github.com/vapor/fluent-kit/pull/270.

**Comment by skyweb07** [comment]
Yes, I've tested with the gm version and it's working now, thanks @tanner0101 and team!!
