### ISSUE TITLE
Updating migrations table to v4

### ISSUE THREAD

**Issue by KleMiX** [vapor/fluent#682]
As of now there is no support for databases and migrations created by previous version of fluent.
This process should be automated, or some scripts provided in documentation.
I was trying to make my sqlite database to work with fluent v4, this is what I did:
```
-- Rename old table for data export later
ALTER TABLE fluent RENAME TO fluent_old;
-- Create new table with different id field and renamed created/updated fields
CREATE TABLE "fluent"("id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "batch" INTEGER NOT NULL, "created_at" REAL, "updated_at" REAL);
-- Import old data to the new table
INSERT INTO fluent(name, batch, created_at, updated_at) SELECT name, batch, createdAt, updatedAt FROM fluent_old;
-- Add Create prefix to migration names in new table, so Todo becomes CreateTodo, this might differ for some people
UPDATE fluent SET name = 'Create'||name;
-- Remove old table
DROP TABLE fluent_old;
```

**Comment by tanner0101** [comment]
Transferring to vapor/fluent since this migration should be a part of the `_Fluent3` module. Now that `"id"` has returned to being `UUID` in Fluent 4, the only requirement should be renaming the timestamp columns. For migration names, I'd recommend setting the `Migration.name` property in code.

**Comment by foscomputerservices** [comment]
In digging into this and comparing with the FluentKit code as follows:

```
database.schema("_fluent_migrations")
    .field(.id, .uuid, .identifier(auto: false))
    .field("name", .string, .required)
    .field("batch", .int, .required)
    .field("created_at", .datetime)
    .field("updated_at", .datetime)
    .unique(on: "name")
    .ignoreExisting()
    .create()
```
It appears that we would need to add another constraint as follows:

`ALTER TABLE _fluent_migrations ADD UNIQUE (name)`

Is this correct?

**Comment by tanner0101** [comment]
@foscomputerservices yes good point. Migration names should definitely be unique as that's how Fluent identifies them.

**Comment by damirstuhec** [comment]
Any news around this? I'm upgrading an existing Vapor 3 project with existing migrations to Vapor 4 and getting stuck here. 🤔

**Comment by 0xTim** [comment]
There's a very hidden script in the [release notes for the Beta](https://github.com/vapor/fluent-kit/releases/tag/1.0.0-beta.5) when it actually changed. You can execute this before starting your V4 instance:

```sql
CREATE extension IF NOT EXISTS "uuid-ossp";
ALTER TABLE "fluent" DROP COLUMN "id";
ALTER TABLE "fluent" ADD "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4();
ALTER TABLE "fluent" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "fluent" RENAME TO "_fluent_migrations"
```

**Comment by damirstuhec** [comment]
Thanks @0xTim. After some testing, it turns out that the full instruction set is as follows:
```
CREATE extension IF NOT EXISTS "uuid-ossp";
ALTER TABLE "fluent" DROP COLUMN "id";
ALTER TABLE "fluent" ADD "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4();
ALTER TABLE "fluent" ALTER COLUMN "id" DROP DEFAULT;
DROP TABLE "_fluent_migrations";  /* only necessary if executed as migration instead of the script */
ALTER TABLE "fluent" RENAME TO "_fluent_migrations";
ALTER TABLE "_fluent_migrations" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "_fluent_migrations" RENAME COLUMN "updatedAt" TO "updated_at";
ALTER TABLE "_fluent_migrations" ADD UNIQUE ("name");
```

**Comment by 0xTim** [comment]
@damirstuhec awesome, glad to hear it's working. I'll close the issue.

If you'd like to create a PR with the above SQL commands into https://github.com/vapor/docs/blob/master/4.0/docs/upgrading.md that would be 🙌
