### ISSUE TITLE
ModelAuthenticatable Authentication issues

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/fluent#688]
When trying to use the 
```swift
public func authenticator(
        database: DatabaseID? = nil
    ) -> Authenticator {
        ModelAuthenticator<Self>(database: database)
    }
``` 
method, the `ModelAuthenticator` is not returned correctly making the ability to authenticate a user not possible. The method in `ModelAuthenticator`
```swift
func authenticate(
        basic: BasicAuthorization,
        for request: Request
    )
```
is not found.

**Comment by 0xTim** [comment]
I think this is because it's inside the private `ModelAuthenticator<User>` type - I don't know if this is a deliberate decision or not

**Comment by anthonycastelli** [comment]
Yeah, that's what I assume as well, but figured I would create a ticket and have @tanner0101 have a look at it in case there is something I am missing.

**Comment by tanner0101** [comment]
You can cast it as a `BasicAuthenticator` to get access to those methods. But it's meant to be used as a middleware:
```swift
public protocol Authenticator: Middleware { }
```
This guide has more info: https://docs.vapor.codes/4.0/authentication/#fluent
