### ISSUE TITLE
Hacks for supporting optionals in @Field

### ISSUE THREAD

**Issue by nashysolutions** [vapor/fluent#720]
There is a hack in the code which is highlighted via some annotation. 
FluentKit > Properties > Field.swift > line 124
Creating issue for visibility.

Great article [here](https://www.swiftbysundell.com/articles/property-wrappers-in-swift/) for using 'ExpressibleByNilLiteral' to handle optionals in property wrappers.

**Comment by 0xTim** [comment]
@nashysolutions what's the actual issue? You _can_ use `@Field` with optional fields but since there's a lot more going on that just `ExpressibleByNilLiteral` (like custom encoding and decoding for the database layer) you should use `@OptionalField`
