### ISSUE TITLE
Only expose some field with content

### ISSUE THREAD

**Issue by Jawtoch** [vapor/fluent#723]
With: Vapor 4.41.4, Fluent 1.11.0 

I wonder how to only expose certains field to the user after a db request, without creating a DTO struct

I have a `Employee` class:

```swift
final class Employee: Model, Content {
	
	typealias IDValue = Int
	
	static let schema = "employee"
	
	@ID(custom: "emp_id")
	var id: Int?

	@Field(key: "emp_filenbr")
	var file: Int
	
	@Field(key: "emp_firstname")
	var firstName: String
	
	/// Employee lastname
	@Field(key: "emp_lastname")
	var lastName: String

	@Parent(key: "wgr_id")
	var workGroup: WorkGroup
	
	init() { }
}
```

and the `WorkGroup` class:
```swift
final class WorkGroup: Model, Content {
	
	typealias IDValue = Int
	
	static let schema = "workgrp"
	
	@ID(custom: "wgr_id")
	var id: Int?
	
	@Field(key: "wgr_text")
	var title: String
	
	init() { }
}
```

Currently, I fetch the DB with
```swift
func index(req: Request) throws -> EventLoopFuture<[Employee]> {
	return Employee
		.query(on: req.db(.fbsql))
		.all()
		.map { $0.filter { $0.file > 0 }}
}
```

A request will give the output:
```json
[
    {
        "status": 0,
        "workGroup": {
            "id": 1
        },
        "firstName": "Foo",
        "id": 999,
        "file": 123456,
        "lastName": "Bar"
    }, …
]
```

But I want, for example, the following output:
```json
[
    {
        "workGroup": {
            "id": 1,
            "title": "Foobar"
        },
        "firstName": "Foo",
        "id": 999
    }, …
]
```

Is that possible with the `.field(_: )` API ? I tried with:
```swift
func index(req: Request) throws -> EventLoopFuture<[Employee]> {
	return Employee
		.query(on: req.db(.fbsql))
		.join(parent: \.$workGroup)
		.field(\.$firstName)
		.field(\.$id)
		.field(WorkGroup.self, \WorkGroup.$id)
		.field(WorkGroup.self, \WorkGroup.$title)
		.all()
}
```

As a result, I get a fatal error `Cannot access field before it is initialized or fetched: (a field of the Employee class)`.

I am using the `.field(_: )` right? It that possible?

**Comment by siemensikkema** [comment]
@Jawtoch The `field` API can only be used to control what goes _into_ the model, not how it is encoded. It can be used to optimize your database queries by not loading unnecessary data. 
What you're observing is that the fields that are not given any value are being accessed during encoding which causes the fatal error.

You'll have to use a separate Encodable value to determine what gets output.
