### ISSUE TITLE
Transaction with FluentMongoDriver?

### ISSUE THREAD

**Issue by Linkadi98** [vapor/fluent#724]
### Describe the bug

I'm trying to make a transaction with mongodb. I use `req.db.transaction()` to create new one, than simply I call `create(on:)` function on an instance of fluent model with the new database created from closure inside `req.db.transaction()`. FluentMongoDatabase does successfully create query but after that, database returns result back to server and it gets fail on assertion 
`assert(
                self.database.eventLoop.inEventLoop,
                "database driver output was not on eventloop"
            )`
 it says `self.database.eventLoop.inEventLoop` is false. I don't have no idea why because at start, it has `true` value.

### To Reproduce

Just try to create an simple instance model with `req.db.transaction()`, also use with FluentMongoDriver

### Expected behavior

Success when inserting document with MongoDB transaction

### Environment

* Vapor Framework version: latest
* Vapor Toolbox version:
* OS version: MacOS BigSur

### Additional context
I asked on Discord but not find any answers.

**Comment by Linkadi98** [comment]
It could be a bug, but I'm not sure so I create an bug issue if it is

**Comment by Linkadi98** [comment]
@Joannis

**Comment by Joannis** [comment]
This is either a bug in the MongoKitten driver or (more likely) the FluentMongoDriver. I know where to look :) Just to verify, this happens on _inserts_ in a transaction, right? Or are there other operations you're doing, too?

**Comment by Linkadi98** [comment]
yes, on inserts in a transaction, I just tried only on `insertMany` and I got that bug.

**Comment by Linkadi98** [comment]
One more thing I've just figured out, when used `save(on:)` on transaction, it shown an message 
`Given transaction number -1 does not match any in-progress transactions. The active transaction number is 1`

I searched and come to this: `https://developer.mongodb.com/community/forums/t/given-transaction-number-does-not-match-any-in-progress-transactions/703`, not sure this is a bug or I did something wrong, but I just used `save(on:)` function and this bug appeared.

**Comment by Joannis** [comment]
Can you let me know which version of MongoKitten is being resolved in your project?

**Comment by Linkadi98** [comment]
MongoKitten version is 6.6.5

**Comment by 0xTim** [comment]
Fixed in [MongoKitten 6.6.6](https://github.com/OpenKitten/MongoKitten/releases/tag/6.6.6)
