### ISSUE TITLE
SQL logging

### ISSUE THREAD

**Issue by finestructure** [vapor/fluent#726]
As part of a recent package update that transitioned to PostgresNIO 1.5.0 I noticed that SQL queries aren't logged anymore at log level `debug`. My understanding is that the change was motivated by logging guidelines which moved SQL logging from debug to `trace`.

While using trace should work for most of our typical debugging use cases, it would be great if there was perhaps an option to log SQL from Fluent at `debug` level, so that the SQL doesn't get drowned out it trace.

**Comment by 0xTim** [comment]
Duplicate of vapor/fluent-postgres-driver#181
