### ISSUE TITLE
No exact matches in call to instance method **'filter'**

### ISSUE THREAD

**Issue by BackWorld** [vapor/fluent#734]
### Describe the bug

build errors always in below codes:
```swift
let planets = try await Planet.query(on: req.db).filter(\.$name == "Earth")
            .all()
```

### Environment

* Xcode13.1
* Swift 5.5
* macOS 12
* Fluent 4.4

### Additional context
<img width="834" alt="截屏2021-11-21 下午4 32 19" src="https://user-images.githubusercontent.com/13940548/142755243-c0f9003b-a177-46b5-ab93-e35c52c2ce1a.png">

**Comment by 0xTim** [comment]
Have you got `import Fluent` in the file?

**Comment by BackWorld** [comment]
@0xTim Of course.

**Comment by BackWorld** [comment]
@0xTim You are genius bro and tks!
