### ISSUE TITLE
How to export data to a file

### ISSUE THREAD

**Issue by vcxk** [vapor/fluent#735]
Help, I want to export select data to a file in Postgres

\o /path/to/file 
select * from table 
\o 

and ,how can I do this in fluent;
Thank you

**Comment by 0xTim** [comment]
This is not something Fluent supports and is out of scope for the library. You can either run a Fluent query to get the data you want and save that using [FileIO](https://docs.vapor.codes/4.0/files/#write) or shell out to something like `pgdump`.
