### ISSUE TITLE
How to compare Date?

### ISSUE THREAD

**Issue by iWECon** [vapor/fluent#738]
Model:
```swift
  final class Record: Model {
      static var schema: String = "records"
      
      @ID(key: .id)
      var id: UUID?
      
      @Field(key: "name")
      var name: String
      
      @Timestamp(key: "date", on: .create, format: .default)
      var date: Date?
      
      @Field(key: "times")
      var times: Int
      
      init() { }
      
      init(name: String) {
          self.name = name
      }
  }
```

Use:
```swift
let date = Date()

try await Record.query(db: req.db)
                .filter(\.$date == date) // can't compare
                .first()
```

Can't compare date, and I saw the log, the $date bind property is Optional...
```
[ DEBUG ] SELECT "records"."id" AS "records_id", "records"."name" AS "records_name", "records"."date" AS "records_date", "records"."times" AS "records_times" FROM "records" WHERE "records"."name" = $1 AND "records"."date" = $2 LIMIT 1 ["AppleReleaseNotesCron", Optional(2022-04-10 15:21:00 +0000)] [database-id: server-health] (FluentPostgresDriver/FluentPostgresDatabase.swift:29)
```

⚠️ `["AppleReleaseNotesCron", Optional(2022-04-10 15:21:00 +0000)]` 

I found a way to use, but I think it is very inconvenient to use:
```swift
.filter(\.$date == .custom("'\(date)'"))
```
Is there any other way to handle properly?

**Comment by iWECon** [comment]
@tanner0101

**Comment by 0xTim** [comment]
```swift
let date = Date()

try await Record.query(db: req.db)
                .filter(\.$date == date) // can't compare
                .first()
```
Should work. Have you got `import Fluent` in the file?

**Comment by iWECon** [comment]
@0xTim Yes, I got `import Fluent` in the file.

Details:
<img width="603" alt="CleanShot 2022-04-11 at 19 02 53@2x" src="https://user-images.githubusercontent.com/16604027/162727237-4825def1-19c4-4ec8-a686-28f81ddbf6b2.png">

Database:
<img width="742" alt="CleanShot 2022-04-11 at 19 03 24@2x" src="https://user-images.githubusercontent.com/16604027/162727310-7c7b1f0e-fce2-4514-a6c4-0f20b16944bb.png">

**Comment by 0xTim** [comment]
What does your migration look like?

**Comment by iWECon** [comment]
of course,

`Record Model`:
<img width="383" alt="CleanShot 2022-04-12 at 00 15 09@2x" src="https://user-images.githubusercontent.com/16604027/162784809-eba59ef5-afd8-4123-a71f-02ad5635e976.png">

`Record Migration`:
<img width="424" alt="CleanShot 2022-04-12 at 00 14 44@2x" src="https://user-images.githubusercontent.com/16604027/162784746-03026240-24ba-48bf-b95d-ebfa5c4cc6c0.png">

`ReleaseNotes Model`:
<img width="615" alt="CleanShot 2022-04-12 at 00 15 44@2x" src="https://user-images.githubusercontent.com/16604027/162784938-8337b176-0cfe-4ad0-a583-08b0fc48ec8e.png">

`ReleaseNotes Migration`:
<img width="545" alt="CleanShot 2022-04-12 at 00 16 11@2x" src="https://user-images.githubusercontent.com/16604027/162785003-6f8c43d5-186f-466b-98dd-ece0d226a57b.png">

**Comment by 0xTim** [comment]
In the migration you should be using `.datetime` and not `.date`

**Comment by 0xTim** [comment]
Migrations will be run more than once. There's no way for Vapor to know how the user wants to convert existing data. So you either need to wipe the DB and start from scratch (recommended), do it manually (not recommended) or write a new migration to change the column type (which you should do if you have existing data you can't lose or recreate easily

**Comment by iWECon** [comment]
OK, I got it.

thank you ~

**Comment by iWECon** [comment]
I have an idea:

Is it possible to save the information of `prepare` to the `_fluent_migrations table`?

If possible, we will be able to compare data with new data in the table(_fluent_migrations) next time.

**Comment by 0xTim** [comment]
That's a lot of random information to store and compare. One day it may be possible to automate but for now it's how it is

**Comment by 0xTim** [comment]
Is your problem now fixed?

**Comment by iWECon** [comment]
It seems that there is no repair, the problem still exists
@0xTim 

<img width="587" alt="CleanShot 2022-04-12 at 00 58 38@2x" src="https://user-images.githubusercontent.com/16604027/162791914-2c3035a2-75d4-4534-95da-157020d1860e.png">

<img width="993" alt="CleanShot 2022-04-12 at 00 59 08@2x" src="https://user-images.githubusercontent.com/16604027/162791995-d4090b0f-7bab-4f38-b75f-d041700589bc.png">

I have deleted data and recreated using migrate.

**Comment by iWECon** [comment]
After replacing `.date` with `.datetime`, it looks even worse.
I only need to compare the year, month and day, the hours, minutes and seconds can be ignored.

**Comment by iWECon** [comment]
Ok, use the accurate time to work properly

**Comment by iWECon** [comment]
do you mean use date `>= 00:00:00` and `<= 23:59:59`.
If this is, I think .date is more suitable for my needs.

**Comment by iWECon** [comment]
so be it, I'm going to sleep...
have a happy day for you~

**Comment by 0xTim** [comment]
There's no native way in Swift to store just a date, which makes things awkward. What you could do is a raw query value, or custom query or use calendar to get the start and end of a day. 

The final option is a new custom type `DateOnly` that works with the DB and Swift but that's a lot of work

**Comment by iWECon** [comment]
uhhh, I found a related issue: [fluent-kit/issues/273](https://github.com/vapor/fluent-kit/issues/273)
but it was discussed in 2018-2020, I'm not sure if the feature was done at that time. (I'm busy with other things now, I'll keep reading about it when I'm free)

**Comment by 0xTim** [comment]
Yeah there's been no movement due to no native Swift type. I'm going to close this in favour of that issue, so feel free to comment on that issue. (I'm assuming the underlying issue of comparing dates is solved, you either need to use date time and a date range or a raw query value
