### ISSUE TITLE
Custom Character Sets

### ISSUE THREAD

**Issue by NathanFlurry** [vapor/fluent#74]
# Feature, Enhancement, or Optimization
# Name of Feature
- Author(s): [Nathan Flurry](https://github.com/NathanFlurry)
- Status: **[Awaiting review](#rationale)**
## Introduction

People need custom encodings and character sets in their databases to do things such as supporting unicode in MySQL. (Let's be honest here, those _very_ emojis are important.)
## Motivation

Fluent need the ability to add custom encodings. I have already added support for reading and writing with custom encodings to all three MySQL libraries.
## Proposed solution

Add custom character sets and collations to tables and columns.
## Code snippets

 A MySQL table with a `utf8mb4` encoding on the `text` column would loo like this:

``` sql
CREATE TABLE `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
## Impact

This will not have any impact on existing code.
## Alternatives considered

The alternative it to let users continue altering tables after being created with raw queries.
## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by tannernelson** [comment]
This is probably different when using different types of SQL right? We need some generic enum that can represent different character encodings then each driver would have to choose whether to support them.

**Comment by tannernelson** [comment]
Moving this to a future version of Fluent.

**Comment by tanner0101** [comment]
The driver-based solution to this problem seems to be working well. For mysql you can set the encoding in [Config/mysql.json](https://github.com/vapor/mysql-provider/blob/master/Sources/MySQLProvider/Driver%2BConfig.swift#L33), other databases/SQL flavors can follow suit with their own custom encoding types. Closing this for now.
