### ISSUE TITLE
Unable to specify which field to filter on within a self-relating sibling

### ISSUE THREAD

**Issue by wibed** [vapor/fluent#750]
i try to filter on a sibling of a table pointing toward itself.

User <- Friend -> User

I fail to distinguish inbetween parent and children siblings.

similar issue:
https://github.com/vapor/vapor/issues/1932
https://stackoverflow.com/questions/54157167/how-do-i-declare-a-siblings-extension-on-a-fluent-model-in-vapor-3-where-the-bas

**Comment by 0xTim** [comment]
The docs have an example of how to use a `ModelAlias` for this purpose

**Comment by wibed** [comment]
huh, it hasn't been obvious to use a Model alias to differentiate between parent and children 
given a manual join.

@0xTim thanks for the hint
