### ISSUE TITLE
Concurrency Swift 5.7 - Any plans to include AsyncMap

### ISSUE THREAD

**Issue by CristianCardosoA** [vapor/fluent#754]
Hello, I'm trying to create a query to obtain "courses" table and "sections", but I need to call `map $sections.load(database)` to obtain those records.

Is there any option to achieve this  instead of calling `map` with `load()` ?

Note: `asyncMap` is a custom extension, otherwise I need to change return type to: `[EventLoopFuture<[Course]>]`

```
struct CourseRepository {
    
    let database: Database

    func getCourseByLang(lang: Language) async throws -> [Course] {
        let courses = try await Course.query(on: database)
            .filter(\.$lang == lang.rawValue)
            .all()
        
          //NEED TO DO THIS TO GET CHILD
        _ = try await courses.asyncMap { course in
            try await course.$sections.load(on: database)
        }
        
        return courses
    }
}
```

Versions:
```
.package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
.package(url: "https://github.com/vapor/fluent.git", from: "4.0.0"),
.package(url: "https://github.com/vapor/fluent-mysql-driver.git", from: "4.0.0"),


```

**Comment by 0xTim** [comment]
Why not just eager load the children?

**Comment by CristianCardosoA** [comment]
I would need to to this instead:

```
for course in courses {
     try await course.$sections.load(on: database)
}
```

**Comment by CristianCardosoA** [comment]
` let courses = try await Course.query(on: database)
            .filter(\.$lang == lang.rawValue)
            .sort(\.$title)
            .with(\.$sections)
            .all()`
