### ISSUE TITLE
Where is .alsoDecode ?

### ISSUE THREAD

**Issue by Samsv77** [vapor/fluent#759]
**Is your feature request related to a problem? Please describe.**

Older releases of Fluent had `.alsoDecode()` to decode an object from a Left/Right/Inner join, this is particular useful when we have 1 to 1 mapping between the records.
`.alsoDecode()` is no longer available in Fluent 4, what is the alternative to load a child without running a separate query ?

Example of alsoDecode:
https://github.com/vapor/fluent/issues/547

**Comment by 0xTim** [comment]
@Samsv77 See [the docs](https://docs.vapor.codes/fluent/query/#join) for how to get joined models from a query
