### ISSUE TITLE
Regarding table association by specifying field names

### ISSUE THREAD

**Issue by lz990377023** [vapor/fluent#777]
I encountered a problem. It seems that Fluent related table query can only specify id for related query. My current situation is that I need to use other fields for related query. For example, in the following code, username is used to bind the parent-child relationship, and username is used to associate the table. Query, but the final query still uses id by default. Is there a correct way?
<img width="1120" alt="截屏2024-07-15 09 30 23" src="https://github.com/user-attachments/assets/3c910bc7-0766-46ee-be43-f97fe4d3c3eb">

**Comment by 0xTim** [comment]
Fluent's relationship property wrappers don't support querying by anything other than ID. If you want that behaviour you'll need to either perform the queries manually or write a custom property wrapper
