### ISSUE TITLE
Creating an entry with id, do not fail and do not save

### ISSUE THREAD

**Issue by Casperhr** [vapor/fluent#80]
https://github.com/vapor/fluent/blob/master/Sources/Fluent/Query/Query.swift#L165

I think it should be possible to insert entries with a forced id (this is used when seeding data fx)

But at least it should fail, right now you think it got stored, but nothing is to be found in the db

(MySQL)

**Comment by tannernelson** [comment]
Ah interesting. There will need to be some sort of `isPersisted` flag then.

**Comment by NathanFlurry** [comment]
@tannernelson I implemented this about a week ago for MySQL. https://github.com/vapor/mysql-driver/blob/master/Sources/FluentMySQL/MySQLDriver.swift#L13
I was going to look into adding official support in fluent (in addition to being able to do something like `database.raw("<query>", [ <parameters> ], newConnection: true)`), but never got around to it. I do like the `isPersistent` flag/parameter name better.
