### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Casperhr** [vapor/fluent#84]
Like the collection, just with options for page=2 query

Add a pagination object to the response with
- next page url
- previous page url
- current page
- total pages
- total count
- count per page

**Comment by mludi** [comment]
That would be awesome.

**Comment by seivan** [comment]
What's you're looking for is something like .limit()
This isn't something that should be in what is essentially the ORM.

**Comment by tannernelson** [comment]
Fluent has limit already. Some web frameworks do even more in terms of paging though.

**Comment by hhanesand** [comment]
Maybe this is a bug better filed on Vapor's repository? Maybe some sort of middleware can be created that automatically adds pagination objects to the responses of certain requests?

**Comment by Casperhr** [comment]
@BrettRToomey Is working on this, should be ready soon!

**Comment by davidvpe** [comment]
For some people that is having trouble with this, I just have made a simple workaround for my object named Offer being pageQuantity the quantity of elements per page and the pageNumber the one received on the request

            let count = try Offer.query().count()
            let amountOfPages = count/pageQuantity
            let limit = pageQuantity*pageNumber
            let query = try Offer.query().limit(limit)
            query.limit?.offset = (pageNumber-1)*pageQuantity
            let results = try query.run()

This approach actually performs two fetches to the DB, one for having the total amount of pages

Printing description of statement:
"SELECT COUNT(*) as _fluent_count FROM `offers`"
Printing description of statement:
"SELECT `offers`.* FROM `offers` LIMIT 20, 30"

**Comment by mludi** [comment]
I made a simple wrapper around it few weeks ago [https://github.com/mludi/VaporSimplePagination](url) I'm currently working on a new version :)

**Comment by BrettRToomey** [comment]
Here's what we ended up releasing at Nodes: https://github.com/nodes-vapor/paginator
